import { BankQuestion } from './nctb_bangla_bank.js';

// =========================================================================
// 1. BRITISH CURRICULUM (CAMBRIDGE CAIE & PEARSON EDEXCEL O & A LEVEL)
// =========================================================================
export const BRITISH_BANK: BankQuestion[] = [
  {
    questionText: 'Which equation correctly expresses Newton’s second law of motion for a system with constant mass?',
    optionA: 'F = m / a',
    optionB: 'F = ma',
    optionC: 'F = m v²',
    optionD: 'F = 1/2 m a²',
    correctOption: 'b',
    explanation: 'Net resultant force equals mass multiplied by acceleration in the direction of the force (F = ma).',
  },
  {
    questionText: 'What is the SI unit of gravitational field strength?',
    optionA: 'N kg⁻¹',
    optionB: 'N m⁻¹',
    optionC: 'J kg⁻¹',
    optionD: 'kg m s⁻²',
    correctOption: 'a',
    explanation: 'Gravitational field strength is defined as force per unit mass (g = F / m), having unit N kg⁻¹ or m s⁻².',
  },
  {
    questionText: 'Which particle is emitted during positive beta (β⁺) radioactive decay?',
    optionA: 'Electron',
    optionB: 'Positron and electron neutrino',
    optionC: 'Alpha particle',
    optionD: 'Neutron',
    correctOption: 'b',
    explanation: 'In β⁺ decay, a proton converts into a neutron, emitting a positron (e⁺) and an electron neutrino (ν_e).',
  },
  {
    questionText: 'What is the pH of a 0.01 mol dm⁻³ aqueous solution of hydrochloric acid (HCl) at 25 °C?',
    optionA: '1.0',
    optionB: '2.0',
    optionC: '7.0',
    optionD: '12.0',
    correctOption: 'b',
    explanation: 'HCl completely dissociates: [H⁺] = 0.01 = 10⁻² mol dm⁻³. pH = -log₁₀(10⁻²) = 2.0.',
  },
  {
    questionText: 'Which enthalpy change is defined as the enthalpy change when 1 mole of a compound is formed from its elements in their standard states?',
    optionA: 'Standard enthalpy change of combustion',
    optionB: 'Standard enthalpy change of formation',
    optionC: 'Standard enthalpy change of neutralization',
    optionD: 'Standard enthalpy change of atomization',
    correctOption: 'b',
    explanation: 'By definition, ΔH°_f represents the enthalpy change of formation under standard conditions.',
  },
  {
    questionText: 'What is the function of the restriction endonuclease enzyme in genetic engineering?',
    optionA: 'Joining DNA fragments together',
    optionB: 'Cutting DNA at specific palindromic recognition sequences',
    optionC: 'Synthesizing complementary RNA from DNA',
    optionD: 'Unwinding the DNA double helix',
    correctOption: 'b',
    explanation: 'Restriction enzymes cleave phosphodiester bonds within DNA at specific recognition nucleotide sequences.',
  },
  {
    questionText: 'Which stage of cellular respiration takes place in the matrix of mitochondria?',
    optionA: 'Glycolysis',
    optionB: 'Krebs cycle (Citric acid cycle)',
    optionC: 'Fermentation',
    optionD: 'Photophosphorylation',
    correctOption: 'b',
    explanation: 'The Krebs cycle and link reaction take place in the mitochondrial matrix; glycolysis occurs in the cytoplasm.',
  },
  {
    questionText: 'What is the derivative of e^(2x) with respect to x?',
    optionA: 'e^(2x)',
    optionB: '2 e^(2x)',
    optionC: '1/2 e^(2x)',
    optionD: '2x e^(2x)',
    correctOption: 'b',
    explanation: 'Using the chain rule: d/dx [e^(2x)] = e^(2x) · d/dx(2x) = 2 e^(2x).',
  },
  {
    questionText: 'In computer science, what is the worst-case time complexity of binary search on a sorted array of n elements?',
    optionA: 'O(1)',
    optionB: 'O(log n)',
    optionC: 'O(n)',
    optionD: 'O(n log n)',
    correctOption: 'b',
    explanation: 'Binary search halves the search space at each comparison, yielding O(log₂ n) logarithmic complexity.',
  },
  {
    questionText: 'What market structure is characterized by a few interdependent dominant firms producing differentiated or homogeneous goods?',
    optionA: 'Monopoly',
    optionB: 'Perfect competition',
    optionC: 'Oligopoly',
    optionD: 'Monopolistic competition',
    correctOption: 'c',
    explanation: 'An oligopoly is an industry dominated by a small number of large sellers exhibiting mutual interdependence.',
  },
  {
    questionText: 'Which macroeconomic indicator measures the responsiveness of quantity demanded to a change in consumer income?',
    optionA: 'Price elasticity of demand (PED)',
    optionB: 'Income elasticity of demand (YED)',
    optionC: 'Cross elasticity of demand (XED)',
    optionD: 'Price elasticity of supply (PES)',
    correctOption: 'b',
    explanation: 'YED measures the percentage change in quantity demanded divided by the percentage change in income.',
  },
  {
    questionText: 'In double-entry bookkeeping, what is the accounting effect of purchasing office equipment on credit?',
    optionA: 'Debit Office Equipment, Credit Accounts Payable',
    optionB: 'Debit Cash, Credit Office Equipment',
    optionC: 'Debit Accounts Payable, Credit Office Equipment',
    optionD: 'Debit Capital, Credit Cash',
    correctOption: 'a',
    explanation: 'Office equipment (asset) increases with a debit; Accounts payable (liability) increases with a credit.',
  },
  {
    questionText: 'Which logical fallacy assumes that because event B occurred after event A, event A must have caused event B?',
    optionA: 'Ad hominem',
    optionB: 'Post hoc ergo propter hoc',
    optionC: 'Straw man fallacy',
    optionD: 'Slippery slope',
    correctOption: 'b',
    explanation: 'Post hoc fallacy improperly conflates mere temporal sequence with causal connection.',
  },
  {
    questionText: 'What is the speed of light in a vacuum according to the international system of units?',
    optionA: '3.00 × 10⁶ m s⁻¹',
    optionB: '3.00 × 10⁸ m s⁻¹',
    optionC: '3.00 × 10¹⁰ m s⁻¹',
    optionD: '9.81 × 10⁸ m s⁻¹',
    correctOption: 'b',
    explanation: 'c = 299,792,458 m s⁻¹ ≈ 3.00 × 10⁸ m s⁻¹.',
  },
  {
    questionText: 'Which organelle is responsible for post-translational modification and sorting of proteins in eukaryotic cells?',
    optionA: 'Endoplasmic reticulum',
    optionB: 'Golgi apparatus',
    optionC: 'Nucleolus',
    optionD: 'Peroxisome',
    correctOption: 'b',
    explanation: 'The Golgi apparatus modifies, packages, and sorts macromolecules for exocytosis or delivery to other organelles.',
  },
];

// =========================================================================
// 2. IB WORLD SCHOOL (DIPLOMA PROGRAMME & MIDDLE YEARS PROGRAMME)
// =========================================================================
export const IB_BANK: BankQuestion[] = [
  {
    questionText: 'In IB Biology, what is the primary role of DNA helicase during transcription and replication?',
    optionA: 'Synthesizing RNA primers',
    optionB: 'Unwinding and breaking hydrogen bonds between complementary base pairs',
    optionC: 'Joining Okazaki fragments on the lagging strand',
    optionD: 'Proofreading newly synthesized nucleotide chains',
    correctOption: 'b',
    explanation: 'Helicase unwinds the double helix by breaking hydrogen bonds holding complementary nucleotide bases together.',
  },
  {
    questionText: 'In IB Chemistry, which transition metal complex is square planar and used as an effective anti-cancer chemotherapeutic drug?',
    optionA: 'Cisplatin [Pt(NH₃)₂Cl₂]',
    optionB: 'Ferrocene [Fe(C₅H₅)₂]',
    optionC: 'Hemoglobin',
    optionD: 'Potassium permanganate [KMnO₄]',
    correctOption: 'a',
    explanation: 'Cisplatin is a square planar platinum(II) complex that crosslinks purine bases in tumor DNA.',
  },
  {
    questionText: 'In IB Physics, what is de Broglie wavelength λ for a particle with momentum p?',
    optionA: 'λ = h / p',
    optionB: 'λ = p / h',
    optionC: 'λ = h · p',
    optionD: 'λ = h / (2p)',
    correctOption: 'a',
    explanation: 'The wave-particle duality relation states that de Broglie wavelength equals Planck’s constant divided by momentum (λ = h / p).',
  },
  {
    questionText: 'In IB Mathematics AA, what is the sum of an infinite convergent geometric series with first term a and common ratio |r| < 1?',
    optionA: 'S_∞ = a / (1 - r)',
    optionB: 'S_∞ = a(1 - rⁿ) / (1 - r)',
    optionC: 'S_∞ = a / (r - 1)',
    optionD: 'S_∞ = a · r / (1 - r)',
    correctOption: 'a',
    explanation: 'For |r| < 1, as n approaches infinity, rⁿ approaches zero, simplifying the sum formula to S_∞ = a / (1 - r).',
  },
  {
    questionText: 'In IB Theory of Knowledge (TOK), what is defined as the experiential and procedural understanding gained through direct practice and reflection?',
    optionA: 'Shared knowledge',
    optionB: 'Personal knowledge',
    optionC: 'Dogmatic knowledge',
    optionD: 'Empirical bias',
    correctOption: 'b',
    explanation: 'Personal knowledge includes practical skills, subjective experience, and individual reflections distinct from collective shared knowledge.',
  },
  {
    questionText: 'In IB Environmental Systems and Societies (ESS), which system state is maintained when outputs of matter or energy feed back into the system to counteract change?',
    optionA: 'Positive feedback loop',
    optionB: 'Negative feedback loop',
    optionC: 'Chaotic equilibrium',
    optionD: 'Static system state',
    correctOption: 'b',
    explanation: 'Negative feedback mechanisms stabilize ecological and environmental systems by counteracting perturbations and returning towards equilibrium.',
  },
  {
    questionText: 'In IB Psychology, which neuroimaging technique measures brain activity by detecting associated changes in cerebral blood oxygenation (BOLD signal)?',
    optionA: 'Electroencephalography (EEG)',
    optionB: 'Functional Magnetic Resonance Imaging (fMRI)',
    optionC: 'Computerized Tomography (CT)',
    optionD: 'Positron Emission Tomography (PET)',
    correctOption: 'b',
    explanation: 'fMRI uses magnetic resonance to map brain activity via the blood-oxygen-level-dependent (BOLD) contrast mechanism.',
  },
  {
    questionText: 'In IB Business Management, what is the formula for calculating the payback period for an investment with equal annual net cash inflows?',
    optionA: 'Initial Investment / Annual Net Cash Inflow',
    optionB: 'Annual Net Cash Inflow / Total Cost',
    optionC: 'Net Present Value / Discount Factor',
    optionD: 'Average Annual Profit / Initial Capital Cost × 100',
    correctOption: 'a',
    explanation: 'Payback period = Initial investment cost divided by the consistent annual net cash inflow generated.',
  },
  {
    questionText: 'In IB Computer Science, which data structure operates strictly on the Last-In, First-Out (LIFO) access principle?',
    optionA: 'Queue',
    optionB: 'Stack',
    optionC: 'Linked list',
    optionD: 'Binary search tree',
    correctOption: 'b',
    explanation: 'Stacks push and pop elements from the top, strictly enforcing LIFO behavior.',
  },
  {
    questionText: 'In IB MYP Integrated Sciences, which cell organelle contains digestive enzymes to break down engulfed pathogens and cellular debris?',
    optionA: 'Ribosome',
    optionB: 'Lysosome',
    optionC: 'Endoplasmic reticulum',
    optionD: 'Vacuole',
    correctOption: 'b',
    explanation: 'Lysosomes contain hydrolytic enzymes functioning in intracellular digestion and autolytic recycling.',
  },
];
