import { BankQuestion } from './nctb_bangla_bank.js';

// =========================================================================
// 1. ENGLISH VERSION - GENERAL & HIGHER MATHEMATICS (SSC & HSC EV)
// =========================================================================
export const EV_MATH_BANK: BankQuestion[] = [
  {
    questionText: 'If A = {1, 2, 3} and B = {2, 3, 4}, what is A ∩ B?',
    optionA: '{1, 4}',
    optionB: '{2, 3}',
    optionC: '{1, 2, 3, 4}',
    optionD: '∅',
    correctOption: 'b',
    explanation: 'The intersection set A ∩ B contains only elements common to both sets, which are 2 and 3.',
  },
  {
    questionText: 'If the radius of a circle is 7 cm, what is its circumference? (π = 22/7)',
    optionA: '22 cm',
    optionB: '44 cm',
    optionC: '88 cm',
    optionD: '154 cm',
    correctOption: 'b',
    explanation: 'Circumference = 2πr = 2 × (22/7) × 7 = 44 cm.',
  },
  {
    questionText: 'What is the discriminant of the quadratic equation 2x² - 4x + 2 = 0?',
    optionA: '0',
    optionB: '4',
    optionC: '-4',
    optionD: '16',
    correctOption: 'a',
    explanation: 'Discriminant D = b² - 4ac = (-4)² - 4(2)(2) = 16 - 16 = 0.',
  },
  {
    questionText: 'What is the value of log₁₀(1000)?',
    optionA: '1',
    optionB: '2',
    optionC: '3',
    optionD: '10',
    correctOption: 'c',
    explanation: 'Since 10³ = 1000, log₁₀(1000) = 3.',
  },
  {
    questionText: 'What is the sum of the interior angles of a quadrilateral?',
    optionA: '180°',
    optionB: '270°',
    optionC: '360°',
    optionD: '540°',
    correctOption: 'c',
    explanation: 'The sum of all four interior angles of any simple planar quadrilateral is always 360°.',
  },
  {
    questionText: 'If sin θ = 3/5, what is the value of cos θ for an acute angle θ?',
    optionA: '4/5',
    optionB: '3/4',
    optionC: '5/4',
    optionD: '2/5',
    correctOption: 'a',
    explanation: 'cos² θ = 1 - sin² θ = 1 - (3/5)² = 16/25, hence cos θ = 4/5.',
  },
  {
    questionText: 'What is the area of an equilateral triangle with side length 6 cm?',
    optionA: '6√3 cm²',
    optionB: '9√3 cm²',
    optionC: '12√3 cm²',
    optionD: '36√3 cm²',
    correctOption: 'b',
    explanation: 'Area = (√3 / 4) a² = (√3 / 4) × 36 = 9√3 cm².',
  },
  {
    questionText: 'What is the 10th term of the arithmetic sequence 3, 7, 11, 15, ...?',
    optionA: '35',
    optionB: '39',
    optionC: '43',
    optionD: '47',
    correctOption: 'b',
    explanation: 'a = 3, d = 4. T₁₀ = a + (10 - 1)d = 3 + 9(4) = 3 + 36 = 39.',
  },
  {
    questionText: 'What is the derivative of f(x) = x³ with respect to x?',
    optionA: '3x',
    optionB: '3x²',
    optionC: 'x²',
    optionD: 'x⁴ / 4',
    correctOption: 'b',
    explanation: 'Using power rule d/dx(xⁿ) = n xⁿ⁻¹, d/dx(x³) = 3x².',
  },
  {
    questionText: 'What is the value of ∫ 2x dx?',
    optionA: 'x² + c',
    optionB: '2x² + c',
    optionC: 'x + c',
    optionD: '2 + c',
    correctOption: 'a',
    explanation: '∫ 2x dx = 2 (x² / 2) + c = x² + c.',
  },
  {
    questionText: 'What is the slope of the straight line 3x - 4y + 8 = 0?',
    optionA: '3/4',
    optionB: '-3/4',
    optionC: '4/3',
    optionD: '-4/3',
    correctOption: 'a',
    explanation: 'Rewriting in slope-intercept form: 4y = 3x + 8 ⇒ y = (3/4)x + 2. Slope m = 3/4.',
  },
  {
    questionText: 'What is the determinant of the 2x2 matrix [[2, 3], [1, 4]]?',
    optionA: '5',
    optionB: '6',
    optionC: '8',
    optionD: '11',
    correctOption: 'a',
    explanation: 'det = (2 × 4) - (3 × 1) = 8 - 3 = 5.',
  },
  {
    questionText: 'If a die is rolled once, what is the probability of getting an even prime number?',
    optionA: '1/6',
    optionB: '1/3',
    optionC: '1/2',
    optionD: '2/3',
    correctOption: 'a',
    explanation: 'The only even prime number on a standard die is 2. Probability = 1/6.',
  },
  {
    questionText: 'What is the length of the diagonal of a square having an area of 50 cm²?',
    optionA: '5 cm',
    optionB: '10 cm',
    optionC: '10√2 cm',
    optionD: '25 cm',
    correctOption: 'b',
    explanation: 'Side a = √50 = 5√2 cm. Diagonal d = a√2 = (5√2) × √2 = 10 cm.',
  },
  {
    questionText: 'What is the value of tan(45°)?',
    optionA: '0',
    optionB: '1/2',
    optionC: '1',
    optionD: '√3',
    correctOption: 'c',
    explanation: 'By standard trigonometric ratios, tan(45°) = 1.',
  },
];

// =========================================================================
// 2. ENGLISH VERSION - PHYSICS (SSC & HSC EV)
// =========================================================================
export const EV_PHYSICS_BANK: BankQuestion[] = [
  {
    questionText: 'What is the SI unit of electric potential difference (voltage)?',
    optionA: 'Ampere',
    optionB: 'Volt',
    optionC: 'Ohm',
    optionD: 'Watt',
    correctOption: 'b',
    explanation: 'The SI unit of electric potential difference and electromotive force is the Volt (V).',
  },
  {
    questionText: 'What is the kinetic energy of an object of mass 4 kg moving with velocity 5 m/s?',
    optionA: '10 J',
    optionB: '20 J',
    optionC: '50 J',
    optionD: '100 J',
    correctOption: 'c',
    explanation: 'Kinetic energy E_k = 1/2 m v² = 0.5 × 4 × (5)² = 2 × 25 = 50 Joules.',
  },
  {
    questionText: 'Which electromagnetic wave has the longest wavelength?',
    optionA: 'Gamma rays',
    optionB: 'X-rays',
    optionC: 'Ultraviolet rays',
    optionD: 'Radio waves',
    correctOption: 'd',
    explanation: 'Radio waves have the lowest frequency and longest wavelength in the electromagnetic spectrum.',
  },
  {
    questionText: 'What type of mirror is used as a rear-view mirror in vehicles?',
    optionA: 'Concave mirror',
    optionB: 'Convex mirror',
    optionC: 'Plane mirror',
    optionD: 'Parabolic mirror',
    correctOption: 'b',
    explanation: 'Convex mirrors always form erect, diminished virtual images and offer a wider field of view.',
  },
  {
    questionText: 'What is the speed of sound in a vacuum?',
    optionA: '332 m/s',
    optionB: '3 × 10⁸ m/s',
    optionC: '0 m/s',
    optionD: '1500 m/s',
    correctOption: 'c',
    explanation: 'Sound is a mechanical wave requiring a material medium; it cannot travel through a vacuum.',
  },
  {
    questionText: 'Which physical quantity represents the rate of change of momentum?',
    optionA: 'Work',
    optionB: 'Force',
    optionC: 'Power',
    optionD: 'Energy',
    correctOption: 'b',
    explanation: 'According to Newton’s second law of motion, force is directly proportional to the rate of change of momentum (F = dp/dt).',
  },
  {
    questionText: 'What is the acceleration due to gravity (g) at the center of the Earth?',
    optionA: '9.8 m/s²',
    optionB: 'Infinity',
    optionC: '0 m/s²',
    optionD: '4.9 m/s²',
    correctOption: 'c',
    explanation: 'At the geometric center of Earth, gravitational forces cancel out uniformly in all directions, making g = 0.',
  },
  {
    questionText: 'What is the power of a convex lens with focal length 0.25 meters?',
    optionA: '+2 D',
    optionB: '+4 D',
    optionC: '-4 D',
    optionD: '+0.25 D',
    correctOption: 'b',
    explanation: 'Power P = 1 / f(m) = 1 / 0.25 = +4 Dioptres.',
  },
  {
    questionText: 'Which law states that induced electromotive force is proportional to the rate of change of magnetic flux?',
    optionA: 'Ohm’s Law',
    optionB: 'Ampere’s Law',
    optionC: 'Faraday’s Law of Electromagnetic Induction',
    optionD: 'Coulomb’s Law',
    correctOption: 'c',
    explanation: 'Faraday’s law of induction states that ε = -dΦ_B/dt.',
  },
  {
    questionText: 'What is the escape velocity from the surface of the Earth approximately?',
    optionA: '9.8 km/s',
    optionB: '11.2 km/s',
    optionC: '30 km/s',
    optionD: '150 km/s',
    correctOption: 'b',
    explanation: 'Escape velocity v_e = √(2gR) ≈ 11.2 km/s.',
  },
];

// =========================================================================
// 3. ENGLISH VERSION - CHEMISTRY (SSC & HSC EV)
// =========================================================================
export const EV_CHEMISTRY_BANK: BankQuestion[] = [
  {
    questionText: 'Which element has the highest electronegativity value on the Pauling scale?',
    optionA: 'Chlorine (Cl)',
    optionB: 'Oxygen (O)',
    optionC: 'Fluorine (F)',
    optionD: 'Nitrogen (N)',
    correctOption: 'c',
    explanation: 'Fluorine has an electronegativity of 4.0, the highest among all known elements.',
  },
  {
    questionText: 'What is the hybridization of carbon in the methane (CH₄) molecule?',
    optionA: 'sp',
    optionB: 'sp²',
    optionC: 'sp³',
    optionD: 'dsp²',
    correctOption: 'c',
    explanation: 'Carbon forms four equivalent single sigma bonds in a tetrahedral geometry, exhibiting sp³ hybridization.',
  },
  {
    questionText: 'If the hydrogen ion concentration [H⁺] of a solution is 1 × 10⁻⁴ mol/L, what is its pH?',
    optionA: '2',
    optionB: '4',
    optionC: '7',
    optionD: '10',
    correctOption: 'b',
    explanation: 'pH = -log₁₀[H⁺] = -log₁₀(10⁻⁴) = 4.',
  },
  {
    questionText: 'What is the primary constituent of natural gas in Bangladesh?',
    optionA: 'Methane (CH₄)',
    optionB: 'Ethane (C₂H₆)',
    optionC: 'Propane (C₃H₈)',
    optionD: 'Butane (C₄H₁₀)',
    correctOption: 'a',
    explanation: 'Over 95% to 99% of Bangladeshi natural gas consists of methane (CH₄).',
  },
  {
    questionText: 'What volume does 1 mole of an ideal gas occupy at standard temperature and pressure (STP)?',
    optionA: '20.0 L',
    optionB: '22.4 L',
    optionC: '24.8 L',
    optionD: '44.8 L',
    correctOption: 'b',
    explanation: 'At STP (0 °C and 1 atm), 1 mole of any ideal gas occupies 22.4 liters.',
  },
  {
    questionText: 'What is the oxidation number of sulfur in sulfuric acid (H₂SO₄)?',
    optionA: '+2',
    optionB: '+4',
    optionC: '+6',
    optionD: '+8',
    correctOption: 'c',
    explanation: '2(+1) + S + 4(-2) = 0 ⇒ 2 + S - 8 = 0 ⇒ S = +6.',
  },
  {
    questionText: 'Which law relates the volume and temperature of an ideal gas at constant pressure?',
    optionA: 'Boyle’s Law',
    optionB: 'Charles’s Law',
    optionC: 'Avogadro’s Law',
    optionD: 'Dalton’s Law',
    correctOption: 'b',
    explanation: 'Charles’s Law states that at constant pressure, volume is directly proportional to absolute temperature (V ∝ T).',
  },
  {
    questionText: 'What is the chemical formula of washing soda?',
    optionA: 'NaHCO₃',
    optionB: 'Na₂CO₃·10H₂O',
    optionC: 'CaCO₃',
    optionD: 'NaOH',
    correctOption: 'b',
    explanation: 'Washing soda is hydrated sodium carbonate decahydrate (Na₂CO₃·10H₂O).',
  },
  {
    questionText: 'Which functional group characterizes alcohols?',
    optionA: '-CHO',
    optionB: '-COOH',
    optionC: '-OH',
    optionD: '-CO-',
    correctOption: 'c',
    explanation: 'The hydroxyl group (-OH) is the characteristic functional group of alcohols.',
  },
  {
    questionText: 'What is absolute zero temperature in degrees Celsius?',
    optionA: '0 °C',
    optionB: '-100 °C',
    optionC: '-273.15 °C',
    optionD: '-373.15 °C',
    correctOption: 'c',
    explanation: '0 Kelvin corresponds precisely to -273.15 °C.',
  },
];

// =========================================================================
// 4. ENGLISH VERSION - BIOLOGY & ICT & COMMERCE & HUMANITIES
// =========================================================================
export const EV_GENERAL_BANK: BankQuestion[] = [
  {
    questionText: 'Which cellular organelle is called the powerhouse of the cell?',
    optionA: 'Golgi apparatus',
    optionB: 'Mitochondrion',
    optionC: 'Ribosome',
    optionD: 'Lysosome',
    correctOption: 'b',
    explanation: 'Mitochondria generate most of the chemical energy needed by the cell through ATP production.',
  },
  {
    questionText: 'How many pairs of chromosomes are present in normal human somatic cells?',
    optionA: '21 pairs',
    optionB: '22 pairs',
    optionC: '23 pairs',
    optionD: '46 pairs',
    correctOption: 'c',
    explanation: 'Human somatic cells contain 23 pairs (46 individual) chromosomes.',
  },
  {
    questionText: 'Which blood group is universally known as the universal recipient?',
    optionA: 'Blood Group A',
    optionB: 'Blood Group B',
    optionC: 'Blood Group AB',
    optionD: 'Blood Group O',
    correctOption: 'c',
    explanation: 'Group AB individuals lack anti-A and anti-B antibodies and can receive red cells from all ABO groups.',
  },
  {
    questionText: 'Which HTML tag is used to define an internal stylesheet?',
    optionA: '<css>',
    optionB: '<script>',
    optionC: '<style>',
    optionD: '<design>',
    correctOption: 'c',
    explanation: 'The <style> tag within the <head> element contains CSS style definitions.',
  },
  {
    questionText: 'What is the binary equivalent of decimal number 13?',
    optionA: '1011',
    optionB: '1101',
    optionC: '1110',
    optionD: '1001',
    correctOption: 'b',
    explanation: '13 = 8 + 4 + 1 = 2³ + 2² + 2⁰ = (1101)₂.',
  },
  {
    questionText: 'Which network topology connects all nodes directly to a central hub or switch?',
    optionA: 'Bus topology',
    optionB: 'Star topology',
    optionC: 'Ring topology',
    optionD: 'Mesh topology',
    correctOption: 'b',
    explanation: 'Star topology organizes communication around a central central switch or hub device.',
  },
  {
    questionText: 'What is the fundamental accounting equation?',
    optionA: 'Assets = Liabilities + Owner’s Equity',
    optionB: 'Revenue = Expenses + Profit',
    optionC: 'Assets = Cash + Inventory',
    optionD: 'Liabilities = Assets + Capital',
    correctOption: 'a',
    explanation: 'The foundation of double-entry bookkeeping: Assets = Liabilities + Owner’s Equity.',
  },
  {
    questionText: 'Which authority is exclusively responsible for issuing currency notes and monetary policy in Bangladesh?',
    optionA: 'Ministry of Finance',
    optionB: 'Bangladesh Bank',
    optionC: 'Sonali Bank',
    optionD: 'Planning Commission',
    correctOption: 'b',
    explanation: 'Bangladesh Bank serves as the central bank of the nation and regulator of the financial system.',
  },
  {
    questionText: 'In economics, opportunity cost is best defined as:',
    optionA: 'The total monetary expense of an investment',
    optionB: 'The value of the next best alternative forgone',
    optionC: 'The sunk costs in production',
    optionD: 'The market price of raw materials',
    correctOption: 'b',
    explanation: 'Opportunity cost represents the lost benefits from choosing one alternative over the next best alternative.',
  },
  {
    questionText: 'What atmospheric layer is closest to the Earth’s surface where all weather events occur?',
    optionA: 'Troposphere',
    optionB: 'Stratosphere',
    optionC: 'Mesosphere',
    optionD: 'Thermosphere',
    correctOption: 'a',
    explanation: 'The troposphere extends from the surface up to about 10-15 km and contains almost all atmospheric water vapor.',
  },
];
