import { pool } from './db.js';

interface RawQuestion {
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: 'a' | 'b' | 'c' | 'd';
  explanation: string;
  serialNumber: number;
}

interface BoardExamData {
  subjectName: string; // matches subject in subjects table
  boardName: string; // e.g. 'ঢাকা বোর্ড', 'সমন্বিত বোর্ড (সকল)', 'কুমিল্লা বোর্ড', etc.
  examYear: number;
  title: string;
  durationMinutes: number;
  totalMarks: number;
  negativeMark: number;
  instructions: string;
  stream: 'science' | 'commerce' | 'humanities' | 'common';
  questions: RawQuestion[];
}

export const ssc2016BoardExams: BoardExamData[] = [
  // =========================================================================
  // 1. HUMANITIES / ARTS — ভূগোল ও পরিবেশ (Geography and Environment)
  // SSC 2016 সমন্বিত বোর্ড (সকল) - Verified 40 MCQs from Satt Academy & Board archives
  // =========================================================================
  {
    subjectName: 'SSC Geography & Environment',
    boardName: 'সমন্বিত বোর্ড (সকল)',
    examYear: 2016,
    title: 'SSC 2016: ভূগোল ও পরিবেশ (সকল বোর্ড)',
    durationMinutes: 40,
    totalMarks: 40,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ৪০ মিনিট।',
    stream: 'humanities',
    questions: [
      {
        serialNumber: 1,
        questionText: 'কোনটি ক্লোরোফ্লোরো কার্বনের সংকেত?',
        optionA: 'FeO',
        optionB: 'CO₂',
        optionC: 'H₂CO₃',
        optionD: 'CFC',
        correctOption: 'd',
        explanation: 'ক্লোরোফ্লোরো কার্বনকে সংক্ষেপে CFC বলা হয়। এটি ওজোন স্তর ক্ষয়ের জন্য প্রধান দায়ী গ্যাস।',
      },
      {
        serialNumber: 2,
        questionText: 'ভূগোলের প্রধান দুটি শাখা কী কী?',
        optionA: 'প্রাকৃতিক ও রাজনৈতিক ভূগোল',
        optionB: 'প্রাকৃতিক ও মানব ভূগোল',
        optionC: 'অর্থনৈতিক ও সামাজিক ভূগোল',
        optionD: 'আঞ্চলিক ও জলবায়ু ভূগোল',
        correctOption: 'b',
        explanation: 'ভূগোলের প্রধান দুটি মৌলিক শাখা হলো প্রাকৃতিক ভূগোল (Physical Geography) এবং মানব ভূগোল (Human Geography)।',
      },
      {
        serialNumber: 3,
        questionText: 'সৌরজগতের সবচেয়ে নিকটতম এবং ক্ষুদ্রতম গ্রহ কোনটি?',
        optionA: 'শুক্র',
        optionB: 'বুধ',
        optionC: 'মঙ্গল',
        optionD: 'প্লুটো',
        correctOption: 'b',
        explanation: 'সূর্যের সবচেয়ে কাছের এবং সৌরজগতের সবচেয়ে ছোট গ্রহ হলো বুধ (Mercury)।',
      },
      {
        serialNumber: 4,
        questionText: 'মূল মধ্যরেখার মান কত ডিগ্রি?',
        optionA: '০°',
        optionB: '৯০°',
        optionC: '১৮০°',
        optionD: '৩৬০°',
        correctOption: 'a',
        explanation: 'যুক্তরাজ্যের গ্রিনিচ মানমন্দিরের ওপর দিয়ে উত্তর-দক্ষিণে বিস্তৃত রেখাকে মূল মধ্যরেখা ধরা হয়, যার দ্রাঘিমা ০°।',
      },
      {
        serialNumber: 5,
        questionText: 'প্রতি ১ ডিগ্রি দ্রাঘিমার পার্থক্যের জন্য সময়ের পার্থক্য কত মিনিট?',
        optionA: '২ মিনিট',
        optionB: '৪ মিনিট',
        optionC: '১৫ মিনিট',
        optionD: '৬০ মিনিট',
        correctOption: 'b',
        explanation: 'পৃথিবী ২৪ ঘণ্টায় ৩৬০° আবর্তন করে, অর্থাৎ প্রতি ১° দ্রাঘিমার জন্য সময়ের ব্যবধান হয় ৪ মিনিট।',
      },
      {
        serialNumber: 6,
        questionText: 'বাংলাদেশের মান সময় গ্রিনিচ মান সময় অপেক্ষা কত ঘণ্টা এগিয়ে?',
        optionA: '+৪ ঘণ্টা',
        optionB: '+৫ ঘণ্টা',
        optionC: '+৬ ঘণ্টা',
        optionD: '+৮ ঘণ্টা',
        correctOption: 'c',
        explanation: 'বাংলাদেশের প্রমাণ দ্রাঘিমা ৯০° পূর্ব, তাই গ্রিনিচ মান সময় (GMT) অপেক্ষা বাংলাদেশ সময় ৬ ঘণ্টা এগিয়ে (GMT+6)।',
      },
      {
        serialNumber: 7,
        questionText: 'ভূ-অভ্যন্তরের সবচেয়ে ভারী ও কেন্দ্রীয় স্তরটির নাম কী?',
        optionA: 'অশ্মমণ্ডল',
        optionB: 'গুরুমণ্ডল',
        optionC: 'কেন্দ্রমণ্ডল',
        optionD: 'ভূত্বক',
        correctOption: 'c',
        explanation: 'পৃথিবীর কেন্দ্রে অবস্থিত স্তরটি কেন্দ্রমণ্ডল (Core), যা প্রধানত নিকেল ও লোহা (NiFe) দ্বারা গঠিত।',
      },
      {
        serialNumber: 8,
        questionText: 'কোনটি রূপান্তরিক শিলার উদাহরণ?',
        optionA: 'মার্বেল',
        optionB: 'চুনাপাথর',
        optionC: 'বেলেপাথর',
        optionD: 'কয়লা',
        correctOption: 'a',
        explanation: 'চুনাপাথর অতিরিক্ত তাপ ও চাপে রূপান্তরিত হয়ে মার্বেলে পরিণত হয়।',
      },
      {
        serialNumber: 9,
        questionText: 'ভূমিকম্প পরিমাপক যন্ত্রের নাম কী?',
        optionA: 'ব্যারোমিটার',
        optionB: 'সিসমোগ্রাফ',
        optionC: 'হাইড্রোমিটার',
        optionD: 'ল্যাকটোমিটার',
        correctOption: 'b',
        explanation: 'সিসমোগ্রাফের সাহায্যে ভূমিকম্পের তীব্রতা ও তরঙ্গ রেকর্ড করা হয় এবং রিখটার স্কেলে তা প্রকাশ করা হয়।',
      },
      {
        serialNumber: 10,
        questionText: 'বায়ুমণ্ডলের কোন স্তরে ওজোন (O₃) গ্যাসের ঘনত্ব সবচেয়ে বেশি থাকে?',
        optionA: 'ট্রপোমণ্ডল',
        optionB: 'স্ট্রাটোস্ফিয়ার',
        optionC: 'মেসোমণ্ডল',
        optionD: 'থার্মোস্ফিয়ার',
        correctOption: 'b',
        explanation: 'স্ট্রাটোস্ফিয়ারের (Stratosphere) মাঝামাঝি ২০-৩৫ কিমি উচ্চতায় ওজোন গ্যাসের প্রাচুর্য থাকে যা ক্ষতিকর অতিবেগুনি রশ্মি শোষণ করে।',
      },
      {
        serialNumber: 11,
        questionText: 'বাংলাদেশের মোট আয়তন প্রায় কত বর্গকিলোমিটার?',
        optionA: '১,৪৭,৫৭০ বর্গ কিমি',
        optionB: '১,৪৮,৪৬০ বর্গ কিমি',
        optionC: '১,৪৭,৬১০ বর্গ কিমি',
        optionD: '১,৫০,০০০ বর্গ কিমি',
        correctOption: 'a',
        explanation: 'বাংলাদেশের অফিশিয়াল স্থল আয়তন প্রায় ১,৪৭,৫৭০ বর্গকিলোমিটার।',
      },
      {
        serialNumber: 12,
        questionText: 'বাংলাদেশের সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?',
        optionA: 'কেউক্রাডং',
        optionB: 'তাজিংডং (বিজয়)',
        optionC: 'চন্দ্রনাথ',
        optionD: 'গারো পাহাড়',
        correctOption: 'b',
        explanation: 'বান্দরবানে অবস্থিত তাজিংডং বা বিজয় হলো বাংলাদেশের সর্বোচ্চ পর্বতশৃঙ্গ (উচ্চতা প্রায় ১,২৮০ মিটার)।',
      },
      {
        serialNumber: 13,
        questionText: 'সুন্দরবনের প্রধান বৃক্ষ কোনটি?',
        optionA: 'শাল',
        optionB: 'সেগুন',
        optionC: 'সুন্দরী',
        optionD: 'গর্জন',
        correctOption: 'c',
        explanation: 'সুন্দরবনের নামকরণের অন্যতম কারণ সুন্দরী গাছের আধিক্য, যা উপকূলীয় ম্যানগ্রোভ বনাঞ্চলের প্রধান উদ্ভিদ।',
      },
      {
        serialNumber: 14,
        questionText: 'কোন জলবায়ু অঞ্চলে সারা বছরই প্রায় প্রতিদিন বিকেলে পরিচলন বৃষ্টিপাত হয়?',
        optionA: 'মরু অঞ্চলে',
        optionB: 'নিরক্ষীয় অঞ্চলে',
        optionC: 'ভূমধ্যসাগরীয় অঞ্চলে',
        optionD: 'তুন্দ্রা অঞ্চলে',
        correctOption: 'b',
        explanation: 'নিরক্ষীয় অঞ্চলে অতিরিক্ত তাপমাত্রার কারণে প্রতিদিন বিকেলে পরিচলন বৃষ্টিপাত (Convectional rain) সংঘটিত হয়।',
      },
      {
        serialNumber: 15,
        questionText: 'জোয়ার-ভাটা সৃষ্টির প্রধান কারণ কী?',
        optionA: 'সূর্যের আকর্ষণ',
        optionB: 'চাঁদের আকর্ষণ ও কেন্দ্রাতিগ শক্তি',
        optionC: 'বায়ুপ্রবাহ',
        optionD: 'সমুদ্র স্রোত',
        correctOption: 'b',
        explanation: 'পৃথিবীর ওপর চাঁদের মহাকর্ষীয় আকর্ষণ এবং পৃথিবীর ঘূর্ণনজনিত কেন্দ্রাতিগ বল জোয়ার-ভাটার মূল কারণ।',
      },
      {
        serialNumber: 16,
        questionText: 'বাংলাদেশের জলবায়ু মূলত কী ধরনের?',
        optionA: 'শীতপ্রধান',
        optionB: 'মরুজ চরমভাবাপন্ন',
        optionC: 'ক্রান্তীয় মৌসুমি জলবায়ু',
        optionD: 'ভূমধ্যসাগরীয়',
        correctOption: 'c',
        explanation: 'বাংলাদেশের জলবায়ু ক্রান্তীয় মৌসুমি জলবায়ু নামে পরিচিত, যেখানে গ্রীষ্মকালে প্রচুর বৃষ্টি ও শীতে শুষ্ক আবহাওয়া বিরাজ করে।',
      },
      {
        serialNumber: 17,
        questionText: 'পৃথিবীর বৃহত্তম বদ্বীপ (Delta) কোনটি?',
        optionA: 'নীলনদ বদ্বীপ',
        optionB: 'আমাজান বদ্বীপ',
        optionC: 'বাংলাদেশ (গঙ্গা-ব্রহ্মপুত্র বদ্বীপ)',
        optionD: 'মিসিসিপি বদ্বীপ',
        correctOption: 'c',
        explanation: 'গঙ্গা, ব্রহ্মপুত্র ও মেঘনা নদী বিধৌত বাংলাদেশ হলো পৃথিবীর বৃহত্তম সক্রিয় বদ্বীপ অঞ্চল।',
      },
      {
        serialNumber: 18,
        questionText: 'কোন নদীর মোহনায় সোয়াচ অব নো গ্রাউন্ড অবস্থিত?',
        optionA: 'কর্ণফুলী',
        optionB: 'বঙ্গোপসাগরের মেঘনা মোহনার অদূরে',
        optionC: 'পদ্মা',
        optionD: 'যমুনা',
        correctOption: 'b',
        explanation: 'বঙ্গোপসাগরের গঙ্গামুখী সাবমেরিন ক্যানিয়ন হলো সোয়াচ অব নো গ্রাউন্ড।',
      },
      {
        serialNumber: 19,
        questionText: 'মানচিত্রে উত্তর দিক সাধারণত কোন দিকে নির্দেশ করা হয়?',
        optionA: 'নিচের দিকে',
        optionB: 'বাম দিকে',
        optionC: 'উপরের দিকে',
        optionD: 'ডান দিকে',
        correctOption: 'c',
        explanation: 'যেকোনো মানচিত্রের ওপরের অংশ উত্তর দিক (North) নির্দেশ করে।',
      },
      {
        serialNumber: 20,
        questionText: 'গ্রিনহাউস গ্যাসের মধ্যে বৈশ্বিক উষ্ণায়নের জন্য সর্বাধিক দায়ী কোনটি?',
        optionA: 'কার্বন ডাই-অক্সাইড (CO₂)',
        optionB: 'অক্সিজেন',
        optionC: 'নাইট্রোজেন',
        optionD: 'হিলিয়াম',
        correctOption: 'a',
        explanation: 'জীবাশ্ম জ্বালানি দহনের ফলে নির্গত CO₂ বায়ুমণ্ডলের তাপ আটকে রেখে বৈশ্বিক উষ্ণায়ন বাড়ায়।',
      },
      {
        serialNumber: 21,
        questionText: 'GIS এর পূর্ণরূপ কী?',
        optionA: 'Geographical Information System',
        optionB: 'Global Internet Service',
        optionC: 'General International Survey',
        optionD: 'Geological Investigation Scheme',
        correctOption: 'a',
        explanation: 'GIS মানে Geographical Information System, যা ভৌগোলিক তথ্য বিশ্লেষণ ও মানচিত্রায়নে ব্যবহৃত হয়।',
      },
      {
        serialNumber: 22,
        questionText: 'পদ্মা ও যমুনা নদী কোথায় মিলিত হয়েছে?',
        optionA: 'চাঁদপুর',
        optionB: 'গোয়ালন্দ',
        optionC: 'ভৈরব',
        optionD: 'বাহাদুরাবাদ',
        correctOption: 'b',
        explanation: 'পদ্মা ও যমুনা নদী রাজবাড়ী জেলার গোয়ালন্দে একত্রিত হয়ে পদ্মা নামে প্রবাহিত হয়েছে।',
      },
      {
        serialNumber: 23,
        questionText: 'পাহাড়পুর বৌদ্ধবিহার কোন জেলায় অবস্থিত?',
        optionA: 'বগুড়া',
        optionB: 'নওগাঁ',
        optionC: 'কুমিল্লা',
        optionD: 'দিনাজপুর',
        correctOption: 'b',
        explanation: 'ঐতিহাসিক পাহাড়পুর বৌদ্ধবিহার (সোমপুর বিহার) নওগাঁ জেলার বদলগাছী উপজেলায় অবস্থিত।',
      },
      {
        serialNumber: 24,
        questionText: 'বায়ুমণ্ডলে নাইট্রোজেনের পরিমাণ শতকরা প্রায় কত ভাগ?',
        optionA: '২০.৭১%',
        optionB: '৭৮.০২%',
        optionC: '০.০৩%',
        optionD: '০.৯৩%',
        correctOption: 'b',
        explanation: 'বায়ুমণ্ডলে নাইট্রোজেন গ্যাসের অনুপাত সবচেয়ে বেশি, প্রায় ৭৮.০২% বা ৭৮.০৮%।',
      },
      {
        serialNumber: 25,
        questionText: 'বৃষ্টিপাত সাধারণত কয়টি শ্রেণিতে বিভক্ত?',
        optionA: '২টি',
        optionB: '৩টি',
        optionC: '৪টি',
        optionD: '৫টি',
        correctOption: 'c',
        explanation: 'বৃষ্টিপাত প্রধানত ৪ প্রকার: পরিচলন, শৈলোৎক্ষেপ, ঘূর্ণিবাত ও সংঘর্ষ বৃষ্টিপাত।',
      },
      {
        serialNumber: 26,
        questionText: 'বাংলাদেশের একমাত্র প্রবাল দ্বীপ কোনটি?',
        optionA: 'সন্দ্বীপ',
        optionB: 'হাতিয়া',
        optionC: 'সেন্টমার্টিন',
        optionD: 'কুতুবদিয়া',
        correctOption: 'c',
        explanation: 'সেন্টমার্টিন দ্বীপ (নারিকেল জিঞ্জিরা) বাংলাদেশের একমাত্র প্রাকৃতিক প্রবাল দ্বীপ।',
      },
      {
        serialNumber: 27,
        questionText: 'মরুভূমিতে বায়ুর কোন কাজের ফলে মাশরুম বা গৌর শিলা গঠিত হয়?',
        optionA: 'অবক্ষেপণ',
        optionB: 'ক্ষয়সাধন',
        optionC: 'বহন',
        optionD: 'সংকোচন',
        correctOption: 'b',
        explanation: 'মরুভূমিতে বায়ুর অবঘর্ষ ক্ষয়কাজের ফলে নিচের নরম শিলা দ্রুত ক্ষয়ে গিয়ে মাশরুম বা ছাতার মতো ভূমিরূপ তৈরি করে।',
      },
      {
        serialNumber: 28,
        questionText: 'একটি পূর্ণ জোয়ার ও একটি পূর্ণ ভাটার মধ্যে সময়ের ব্যবধান কত?',
        optionA: '৬ ঘণ্টা ১৩ মিনিট',
        optionB: '১২ ঘণ্টা ২৬ মিনিট',
        optionC: '২৪ ঘণ্টা ৫২ মিনিট',
        optionD: '৩ ঘণ্টা',
        correctOption: 'a',
        explanation: 'একটি জোয়ার ও পরবর্তী ভাটার মধ্যবর্তী সময় প্রায় ৬ ঘণ্টা ১৩ মিনিট।',
      },
      {
        serialNumber: 29,
        questionText: 'আন্তর্জাতিক তারিখ রেখা কোন মহাসাগরের ওপর দিয়ে কল্পনা করা হয়েছে?',
        optionA: 'আটলান্টিক মহাসাগর',
        optionB: 'প্রশান্ত মহাসাগর',
        optionC: 'ভারত মহাসাগর',
        optionD: 'উত্তর মহাসাগর',
        correctOption: 'b',
        explanation: 'আন্তর্জাতিক তারিখ রেখা (১৮০° দ্রাঘিমা রেখা) প্রশান্ত মহাসাগরের জলভাগের ওপর দিয়ে বেঁকিয়ে অঙ্কন করা হয়েছে।',
      },
      {
        serialNumber: 30,
        questionText: 'বারিমণ্ডলের শতকরা কত ভাগ পানি লবণাক্ত?',
        optionA: '৫০%',
        optionB: '৭০%',
        optionC: '৯৭%',
        optionD: '৩%',
        correctOption: 'c',
        explanation: 'পৃথিবীর মোট জলরাশির প্রায় ৯৭ ভাগ পানি সমুদ্রের লবণাক্ত পানি এবং মাত্র ৩ ভাগ সুপেয় মিষ্টি পানি।',
      },
      {
        serialNumber: 31,
        questionText: 'গ্রীষ্মকালে বাংলাদেশে কালবৈশাখী ঝড় মূলত কোন দিক থেকে আসে?',
        optionA: 'উত্তর-পশ্চিম দিক',
        optionB: 'দক্ষিণ-পশ্চিম দিক',
        optionC: 'উত্তর-পূর্ব দিক',
        optionD: 'দক্ষিণ-পূর্ব দিক',
        correctOption: 'a',
        explanation: 'কালবৈশাখী ঝড় সাধারণত উত্তর-পশ্চিম কোণ থেকে প্রবাহিত হয় বলে একে ইংরেজিতে Nor’wester বলা হয়।',
      },
      {
        serialNumber: 32,
        questionText: 'কোন শিলাকে প্রাথমিক বা আদি শিলা বলা হয়?',
        optionA: 'পাললিক শিলা',
        optionB: 'আগ্নেয় শিলা',
        optionC: 'রূপান্তরিত শিলা',
        optionD: 'কংলোমারেট',
        correctOption: 'b',
        explanation: 'পৃথিবী সৃষ্টির সময় উত্তপ্ত ম্যাগমা শীতল ও জমাট বেঁধে প্রথম আগ্নেয় শিলা তৈরি হয়েছিল বলে একে আদি শিলা বলে।',
      },
      {
        serialNumber: 33,
        questionText: 'বাংলাদেশে কোন ঋতুতে সবচেয়ে বেশি বৃষ্টিপাত হয়?',
        optionA: 'গ্রীষ্মকাল',
        optionB: 'বর্ষাকাল',
        optionC: 'শরৎকাল',
        optionD: 'শীতকাল',
        correctOption: 'b',
        explanation: 'দক্ষিণ-পশ্চিম মৌসুমি বায়ুর প্রভাবে বর্ষাকালে বাংলাদেশে মোট বৃষ্টিপাতের প্রায় ৮০ শতাংশ হয়ে থাকে।',
      },
      {
        serialNumber: 34,
        questionText: 'সমুদ্রপৃষ্ঠে বায়ুর স্বাভাবিক চাপ কত সেন্টিমিটার পারদস্তম্ভের সমান?',
        optionA: '৭৬ সেমি',
        optionB: '৮০ সেমি',
        optionC: '৭০ সেমি',
        optionD: '৬৫ সেমি',
        correctOption: 'a',
        explanation: 'সমুদ্রপৃষ্ঠে ৪৫° অক্ষাংশে বায়ুর প্রমাণ চাপ হলো ৭৬ সেন্টিমিটার পারদস্তম্ভ (বা ১০১৩.২৫ মিলিবার)।',
      },
      {
        serialNumber: 35,
        questionText: 'বরেন্দ্রভূমি কোন ধরনের ভূমিরূপের অন্তর্ভুক্ত?',
        optionA: 'প্লাবন সমভূমি',
        optionB: 'প্লাইস্টোসিন কালের সোপান',
        optionC: 'টারশিয়ারি যুগের পাহাড়',
        optionD: 'উপকূলীয় সমভূমি',
        correctOption: 'b',
        explanation: 'রাজশাহী, নওগাঁ ও বগুড়া অঞ্চলের বরেন্দ্রভূমি প্লাইস্টোসিন যুগের চত্বর বা সোপান অঞ্চলের অন্তর্গত।',
      },
      {
        serialNumber: 36,
        questionText: 'কোন গ্যাস সূর্য থেকে আগত ক্ষতিকর আল্ট্রাভায়োলেট রশ্মি প্রতিহত করে?',
        optionA: 'ওজোন (O₃)',
        optionB: 'অক্সিজেন (O₂)',
        optionC: 'মিথেন (CH₄)',
        optionD: 'হিলিয়াম',
        correctOption: 'a',
        explanation: 'ওজোন গ্যাসের স্তর ক্ষতিকর অতিবেগুনি রশ্মিকে ভূপৃষ্ঠে আসতে বাধা দিয়ে জীবজগৎকে রক্ষা করে।',
      },
      {
        serialNumber: 37,
        questionText: 'জলবায়ুর নিয়ামক নয় কোনটি?',
        optionA: 'অক্ষাংশ',
        optionB: 'উচ্চতা',
        optionC: 'সমুদ্র হতে দূরত্ব',
        optionD: 'জনসংখ্যার ঘনত্ব',
        correctOption: 'd',
        explanation: 'অক্ষাংশ, সমুদ্র হতে দূরত্ব ও উচ্চতা প্রাকৃতিক নিয়ামক হলেও জনসংখ্যার ঘনত্ব কোনো জলবায়ু নিয়ামক নয়।',
      },
      {
        serialNumber: 38,
        questionText: 'পদ্মা ও মেঘনা নদীর মিলনস্থল কোথায়?',
        optionA: 'চাঁদপুর',
        optionB: 'গোয়ালন্দ',
        optionC: 'মুন্সীগঞ্জ',
        optionD: 'ভৈরব',
        correctOption: 'a',
        explanation: 'পদ্মা এবং মেঘনা নদী চাঁদপুর মোহনায় মিলিত হয়ে মেঘনা নাম ধারণ করে বঙ্গোপসাগরে পতিত হয়েছে।',
      },
      {
        serialNumber: 39,
        questionText: 'শব্দদূষণের তীব্রতা পরিমাপক এককের নাম কী?',
        optionA: 'প্যাসকেল',
        optionB: 'ওয়াট',
        optionC: 'ডেসিবেল (dB)',
        optionD: 'হার্টজ',
        correctOption: 'c',
        explanation: 'শব্দের তীব্রতা ও দূষণের মাত্রা পরিমাপ করা হয় ডেসিবেল (dB) এককে।',
      },
      {
        serialNumber: 40,
        questionText: 'পরিবেশের ভারসাম্য রক্ষার জন্য কোনো দেশের মোট আয়তনের শতকরা কত ভাগ বনভূমি থাকা প্রয়োজন?',
        optionA: '১৫%',
        optionB: '২০%',
        optionC: '২৫%',
        optionD: '৩৩%',
        correctOption: 'c',
        explanation: 'পরিবেশ ও বাস্তুসংস্থানের ভারসাম্য রক্ষার জন্য আন্তর্জাতিক মানদণ্ডে দেশের অন্তত ২৫% বনভূমি থাকা প্রয়োজন।',
      },
    ],
  },

  // =========================================================================
  // 2. SCIENCE GROUP — পদার্থবিজ্ঞান (SSC Physics)
  // SSC 2016 ঢাকা বোর্ড - Verified 35 MCQs (Practical subjects had 35 MCQs in 2016)
  // =========================================================================
  {
    subjectName: 'SSC Physics',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2016,
    title: 'SSC 2016: পদার্থবিজ্ঞান (ঢাকা বোর্ড)',
    durationMinutes: 35,
    totalMarks: 35,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। ৩৫টি প্রশ্ন, সময় ৩৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'কোনটি মৌলিক রাশি?',
        optionA: 'বেগ',
        optionB: 'বল',
        optionC: 'তড়িৎ প্রবাহ',
        optionD: 'কাজ',
        correctOption: 'c',
        explanation: 'SI পদ্ধতিতে তড়িৎ প্রবাহ (অ্যাম্পিয়ার) ৭টি মৌলিক রাশির একটি। বাকিগুলো লব্ধ রাশি।',
      },
      {
        serialNumber: 2,
        questionText: 'মাত্রা সমীকরণে বলের মাত্রা কোনটি?',
        optionA: 'MLT⁻²',
        optionB: 'ML²T⁻²',
        optionC: 'ML⁻¹T⁻²',
        optionD: 'MLT⁻¹',
        correctOption: 'a',
        explanation: 'বল = ভর × ত্বরণ = M × LT⁻² = MLT⁻²।',
      },
      {
        serialNumber: 3,
        questionText: 'ভার্নিয়ার ধ্রুবক (VC) নির্ণয়ের সঠিক সূত্র কোনটি?',
        optionA: 's / n',
        optionB: 'n / s',
        optionC: 's × n',
        optionD: 's + n',
        correctOption: 'a',
        explanation: 'প্রধান স্কেলের ১ ক্ষুদ্রতম ভাগের মান (s) কে ভার্নিয়ার স্কেলের মোট ভাগসংখ্যা (n) দিয়ে ভাগ করলে VC পাওয়া যায়।',
      },
      {
        serialNumber: 4,
        questionText: 'পরন্ত বস্তুর ক্ষেত্রে গ্যালিলিওর দ্বিতীয় সূত্র অনুযায়ী বেগ (v) ও সময় (t) এর সম্পর্ক কী?',
        optionA: 'v ∝ t²',
        optionB: 'v ∝ t',
        optionC: 'v ∝ √t',
        optionD: 'v ∝ 1/t',
        correctOption: 'b',
        explanation: 'স্থির অবস্থান থেকে মুক্তভাবে পরন্ত বস্তু নির্দিষ্ট সময়ে যে বেগ অর্জন করে তা ঐ সময়ের সমানুপাতিক (v ∝ t)।',
      },
      {
        serialNumber: 5,
        questionText: 'একটি গাড়ির বেগ 10 m/s থেকে সুষমভাবে বৃদ্ধি পেয়ে 5 সেকেন্ডে 30 m/s হলে গাড়িটির ত্বরণ কত?',
        optionA: '2 m/s²',
        optionB: '4 m/s²',
        optionC: '6 m/s²',
        optionD: '8 m/s²',
        correctOption: 'b',
        explanation: 'ত্বরণ a = (v - u) / t = (30 - 10) / 5 = 20 / 5 = 4 m/s²।',
      },
      {
        serialNumber: 6,
        questionText: 'নিউটনের গতির দ্বিতীয় সূত্র থেকে কিসের পরিমাপ পাওয়া যায়?',
        optionA: 'জড়তা',
        optionB: 'বল',
        optionC: 'কাজ',
        optionD: 'ক্ষমতা',
        correctOption: 'b',
        explanation: 'নিউটনের দ্বিতীয় সূত্র F = ma থেকে বলের মান ও সমীকরণ পরিমাপ করা যায়।',
      },
      {
        serialNumber: 7,
        questionText: 'ঘর্ষণ বল সর্বদা গতির কোন অভিমুখে কাজ করে?',
        optionA: 'গতির দিকে',
        optionB: 'গতির বিপরীত দিকে',
        optionC: 'গতির সাথে লম্বভাবে',
        optionD: 'যেকোনো দিকে',
        correctOption: 'b',
        explanation: 'ঘর্ষণ বল সংস্পর্শে থাকা তলের আপেক্ষিক গতির বিপরীতে কাজ করে বাধা সৃষ্টি করে।',
      },
      {
        serialNumber: 8,
        questionText: 'কাজের পরম একক কোনটি?',
        optionA: 'নিউটন',
        optionB: 'জুল (Joule)',
        optionC: 'ওয়াট',
        optionD: 'প্যাসকেল',
        correctOption: 'b',
        explanation: 'কাজ ও শক্তির আন্তর্জাতিক (SI) একক হলো জুল (Joule)।',
      },
      {
        serialNumber: 9,
        questionText: '50 kg ভরের একজন ব্যক্তি 10 m উঁচুতে উঠলে সম্পাদিত কাজের পরিমাণ কত? (g = 9.8 m/s²)',
        optionA: '4900 J',
        optionB: '500 J',
        optionC: '490 J',
        optionD: '980 J',
        correctOption: 'a',
        explanation: 'কাজ W = mgh = 50 × 9.8 × 10 = 4900 জুল।',
      },
      {
        serialNumber: 10,
        questionText: '1 অশ্বক্ষমতা (1 Horsepower) সমান কত ওয়াট?',
        optionA: '550 W',
        optionB: '746 W',
        optionC: '1000 W',
        optionD: '760 W',
        correctOption: 'b',
        explanation: '১ অশ্বক্ষমতা (1 HP) = ৭৪৬ ওয়াট।',
      },
      {
        serialNumber: 11,
        questionText: 'চাপের এসআই (SI) একক কোনটি?',
        optionA: 'N/m',
        optionB: 'প্যাসকেল (N/m²)',
        optionC: 'J/s',
        optionD: 'kg/m³',
        correctOption: 'b',
        explanation: 'চাপ P = F/A; প্রতি বর্গমিটারে ১ নিউটন বল প্রয়োগে ১ প্যাসকেল (Pa) চাপ উৎপন্ন হয়।',
      },
      {
        serialNumber: 12,
        questionText: 'পানির ঘনত্ব সবচেয়ে বেশি হয় কোন তাপমাত্রায়?',
        optionA: '0°C',
        optionB: '4°C',
        optionC: '100°C',
        optionD: '-4°C',
        correctOption: 'b',
        explanation: 'পানির ব্যতিক্রমী প্রসারণের কারণে ৪° সেলসিয়াস তাপমাত্রায় পানির ঘনত্ব সর্বোচ্চ (1000 kg/m³) হয়।',
      },
      {
        serialNumber: 13,
        questionText: 'আর্কিমিডিসের নীতি অনুযায়ী কোনো বস্তুর নিমজ্জিত অবস্থায় হারানো ওজন কিসের সমান?',
        optionA: 'বস্তুর প্রকৃত ওজনের সমান',
        optionB: 'বস্তুর দ্বারা অপসারিত তরলের ওজনের সমান',
        optionC: 'পাত্রের তরলের মোট ওজনের সমান',
        optionD: 'বায়ুমণ্ডলীয় চাপের সমান',
        correctOption: 'b',
        explanation: 'বস্তু যে পরিমাণ তরল অপসারণ করে, তার প্লবতা বা হারানো ওজন ঠিক অপসারিত তরলের ওজনের সমান হয়।',
      },
      {
        serialNumber: 14,
        questionText: 'হুকের সূত্রে স্থিতিস্থাপক সীমার মধ্যে কোনটি সঠিক?',
        optionA: 'পীড়ন ∝ বিকৃতি',
        optionB: 'পীড়ন = বিকৃতি²',
        optionC: 'পীড়ন ∝ ১/বিকৃতি',
        optionD: 'পীড়ন + বিকৃতি = ধ্রুবক',
        correctOption: 'a',
        explanation: 'রবার্ট হুকের সূত্রানুসারে স্থিতিস্থাপক সীমার মধ্যে পীড়ন বিকৃতির সমানুপাতিক।',
      },
      {
        serialNumber: 15,
        questionText: 'সেলসিয়াস ও ফারেনহাইট স্কেলের মধ্যকার সঠিক সম্পর্ক কোনটি?',
        optionA: 'C/5 = (F - 32)/9',
        optionB: 'C/9 = (F - 32)/5',
        optionC: 'C/5 = (F + 32)/9',
        optionD: 'C/100 = F/180',
        correctOption: 'a',
        explanation: 'সেলসিয়াস ও ফারেনহাইটের রূপান্তর সমীকরণ হলো: C/5 = (F - 32)/9।',
      },
      {
        serialNumber: 16,
        questionText: 'কোন তাপমাত্রায় সেলসিয়াস ও ফারেনহাইট উভয় স্কেলে সমান পাঠ পাওয়া যায়?',
        optionA: '0°',
        optionB: '-40°',
        optionC: '40°',
        optionD: '100°',
        correctOption: 'b',
        explanation: '-৪০° তাপমাত্রায় উভয় স্কেলের পাঠ একই (-40°C = -40°F) হয়।',
      },
      {
        serialNumber: 17,
        questionText: 'পদার্থের কোন অবস্থায় অণুগুলোর মধ্যে আন্তঃআণবিক আকর্ষণ বল সবচেয়ে বেশি?',
        optionA: 'কঠিন',
        optionB: 'তরল',
        optionC: 'বায়বীয়',
        optionD: 'প্লাজমা',
        correctOption: 'a',
        explanation: 'কঠিন পদার্থের অণুগুলো খুব কাছাকাছি দৃঢ়ভাবে বিন্যস্ত থাকায় আন্তঃআণবিক আকর্ষণ বল সবচেয়ে প্রবল।',
      },
      {
        serialNumber: 18,
        questionText: 'শব্দ তরঙ্গ কোন ধরনের তরঙ্গ?',
        optionA: 'অনুদৈর্ঘ্য তরঙ্গ (Longitudinal wave)',
        optionB: 'অনুপ্রস্থ তরঙ্গ (Transverse wave)',
        optionC: 'তড়িৎ-চৌম্বকীয় তরঙ্গ',
        optionD: 'স্থির তরঙ্গ',
        correctOption: 'a',
        explanation: 'শব্দ বায়ুমাধ্যমে সংকোচন ও প্রসারণের মাধ্যমে অগ্রসর হয়, তাই এটি একটি অনুদৈর্ঘ্য বা লম্বিক তরঙ্গ।',
      },
      {
        serialNumber: 19,
        questionText: '0°C তাপমাত্রায় বায়ুতে শব্দের বেগ কত?',
        optionA: '300 m/s',
        optionB: '332 m/s',
        optionC: '344 m/s',
        optionD: '1500 m/s',
        correctOption: 'b',
        explanation: 'শূন্য ডিগ্রি সেলসিয়াস শুষ্ক বায়ুতে শব্দের গতিবেগ প্রায় ৩৩২ মিটার/সেকেন্ড।',
      },
      {
        serialNumber: 20,
        questionText: 'শব্দের প্রতিধ্বনি শোনার জন্য প্রতিফলক ও উৎসের ন্যূনতম দূরত্ব কত মিটার হওয়া প্রয়োজন?',
        optionA: '10.5 m',
        optionB: '16.6 m',
        optionC: '20 m',
        optionD: '33.2 m',
        correctOption: 'b',
        explanation: 'শব্দানুভূতির স্থায়িত্বকাল ০.১ সেকেন্ড। এই সময়ে শব্দের অতিক্রম দূরত্ব ৩৩.২ মিটার, তাই প্রতিফলকের ন্যূনতম দূরত্ব ১৬.৬ মিটার।',
      },
      {
        serialNumber: 21,
        questionText: 'দর্পণ থেকে প্রতিফলনে আপতন কোণ ৬০° হলে প্রতিফলন কোণ কত হবে?',
        optionA: '৩০°',
        optionB: '৪৫°',
        optionC: '৬০°',
        optionD: '৯০°',
        correctOption: 'c',
        explanation: 'আলোর প্রতিফলনের প্রথম সূত্রানুসারে আপতন কোণ সর্বদা প্রতিফলন কোণের সমান (∠i = ∠r = 60°)।',
      },
      {
        serialNumber: 22,
        questionText: 'কোন রঙের আলোর তরঙ্গদৈর্ঘ্য সবচেয়ে বেশি?',
        optionA: 'লাল',
        optionB: 'বেগুনি',
        optionC: 'হলুদ',
        optionD: 'সবুজ',
        correctOption: 'a',
        explanation: 'দৃশ্যমান আলোর মধ্যে লাল আলোর তরঙ্গদৈর্ঘ্য সবচেয়ে দীর্ঘ এবং বিক্ষেপণ সবচেয়ে কম।',
      },
      {
        serialNumber: 23,
        questionText: 'লেন্সের ক্ষমতার এসআই (SI) একক কোনটি?',
        optionA: 'মিটার',
        optionB: 'ডাইঅপ্টার (D)',
        optionC: 'ওয়াট',
        optionD: 'ক্যান্ডেলা',
        correctOption: 'b',
        explanation: 'লেন্সের ক্ষমতা P = 1/f (মিটারে)। এর ব্যবহারিক একক হলো ডাইঅপ্টার (Dioptre, D)।',
      },
      {
        serialNumber: 24,
        questionText: 'হ্রস্বদৃষ্টি (Myopia) দূর করতে কোন লেন্সের চশমা ব্যবহার করা হয়?',
        optionA: 'উত্তল লেন্স',
        optionB: 'অবতল লেন্স',
        optionC: 'দ্বি-উত্তল লেন্স',
        optionD: 'সমতল কাচ',
        correctOption: 'b',
        explanation: 'হ্রস্বদৃষ্টিতে দূরের বস্তু অস্পষ্ট দেখা যায়, যা সংশোধনে উপযুক্ত ফোকাস দূরত্বের অবতল লেন্স প্রয়োজন হয়।',
      },
      {
        serialNumber: 25,
        questionText: 'তড়িৎ আধানের একক কোনটি?',
        optionA: 'ভোল্ট',
        optionB: 'কুলম্ব (Coulomb)',
        optionC: 'অ্যাম্পিয়ার',
        optionD: 'ওহম',
        correctOption: 'b',
        explanation: 'তড়িৎ আধানের এসআই একক হলো কুলম্ব (C)।',
      },
      {
        serialNumber: 26,
        questionText: 'ওহমের সূত্র অনুযায়ী পরিবাহীর দুই প্রান্তের বিভব পার্থক্য V এবং রোধ R হলে তড়িৎ প্রবাহ I = ?',
        optionA: 'I = VR',
        optionB: 'I = V / R',
        optionC: 'I = R / V',
        optionD: 'I = V²R',
        correctOption: 'b',
        explanation: 'জর্জ সাইমন ওহমের সূত্রানুসারে তাপমাত্রা স্থির থাকলে I = V / R।',
      },
      {
        serialNumber: 27,
        questionText: 'একটি 100 W এর বৈদ্যুতিক বাল্ব দৈনিক 5 ঘণ্টা জ্বালালে 30 দিনে কত ইউনিট (kWh) বিদ্যুৎ ব্যয় হবে?',
        optionA: '15 kWh',
        optionB: '30 kWh',
        optionC: '150 kWh',
        optionD: '500 kWh',
        correctOption: 'a',
        explanation: 'ব্যয়িত শক্তি = (P × t × দিন) / ১০০০ = (১০০ × ৫ × ৩০) / ১০০০ = ১৫ ইউনিট (kWh)।',
      },
      {
        serialNumber: 28,
        questionText: 'বাসাবাড়িতে বিদ্যুৎ সংযোগ সাধারণত কোন বর্তনীতে দেওয়া হয়?',
        optionA: 'শ্রেণি সংযোগ (Series)',
        optionB: 'সমান্তরাল সংযোগ (Parallel)',
        optionC: 'মিশ্র সংযোগ',
        optionD: 'মুক্ত বর্তনী',
        correctOption: 'b',
        explanation: 'সমান্তরাল সংযোগে প্রতিটি বৈদ্যুতিক যন্ত্রের জন্য সমান ভোল্টেজ পাওয়া যায় এবং আলাদাভাবে সুইচ নিয়ন্ত্রণ করা যায়।',
      },
      {
        serialNumber: 29,
        questionText: 'তড়িৎ চুম্বক তৈরিতে কোন ধাতু সবচেয়ে বেশি উপযোগী?',
        optionA: 'কাঁচা লোহা',
        optionB: 'ইস্পাত',
        optionC: 'তামা',
        optionD: 'অ্যালুমিনিয়াম',
        correctOption: 'a',
        explanation: 'কাঁচা লোহার ধারণক্ষমতা কম ও দ্রুত চুম্বকিত হয় বলে অস্থায়ী তড়িৎ চুম্বকের মজ্জা হিসেবে ব্যবহৃত হয়।',
      },
      {
        serialNumber: 30,
        questionText: 'স্টেপ-আপ ট্রান্সফর্মারে কোনটি সত্য?',
        optionA: 'গৌণ কুন্ডলীর পাকসংখ্যা মুখ্য কুন্ডলী অপেক্ষা বেশি (Ns > Np)',
        optionB: 'মুখ্য কুন্ডলীর পাকসংখ্যা বেশি',
        optionC: 'ভোল্টেজ হ্রাস পায়',
        optionD: 'প্রবাহ বৃদ্ধি পায়',
        correctOption: 'a',
        explanation: 'স্টেপ-আপ ট্রান্সফর্মার নিম্ন ভোল্টেজকে উচ্চ ভোল্টেজে রূপান্তর করে, যেখানে Ns > Np।',
      },
      {
        serialNumber: 31,
        questionText: 'আধুনিক ইলেকট্রনিক্সের মূল ভিত্তি কোনটি?',
        optionA: 'অর্ধপরিবাহী (Semiconductor)',
        optionB: 'সুপরিবাহী',
        optionC: 'কুপরিবাহী',
        optionD: 'অতিপরিবাহী',
        correctOption: 'a',
        explanation: 'সিলিকন ও জার্মেনিয়ামের মতো অর্ধপরিবাহী দিয়ে তৈরি ট্রানজিস্টর ও আইসি আধুনিক ইলেকট্রনিক্সের ভিত্তি।',
      },
      {
        serialNumber: 32,
        questionText: 'তেজস্ক্রিয়তা আবিষ্কার করেন কে?',
        optionA: 'মাদাম ক্যুরি',
        optionB: 'অঁরি বেকেরেল',
        optionC: 'রন্টজেন',
        optionD: 'রাদারফোর্ড',
        correctOption: 'b',
        explanation: '১৮৯৬ সালে ফরাসি বিজ্ঞানী অঁরি বেকেরেল ইউরেনিয়াম লবণ থেকে স্বতঃস্ফূর্ত তেজস্ক্রিয় বিকিরণ আবিষ্কার করেন।',
      },
      {
        serialNumber: 33,
        questionText: 'আলফা (α) কণা আসলে কী?',
        optionA: 'হিলিয়াম নিউক্লিয়াস (He²⁺)',
        optionB: 'ইলেকট্রন প্রবাহ',
        optionC: 'তড়িৎ-চৌম্বক তরঙ্গ',
        optionD: 'প্রোটন কণা',
        correctOption: 'a',
        explanation: 'আলফা কণা হলো দুটি প্রোটন ও দুটি নিউট্রন সমন্বিত ধনাত্মক হিলিয়াম নিউক্লিয়াস।',
      },
      {
        serialNumber: 34,
        questionText: 'হাড়ের ভাঙা অংশ নির্ণয় ও চিকিৎসায় কোন রশ্মি সর্বাধিক ব্যবহৃত হয়?',
        optionA: 'আল্ট্রাভায়োলেট রশ্মি',
        optionB: 'এক্স-রে (X-Ray)',
        optionC: 'ইনফ্রারেড রশ্মি',
        optionD: 'গামা রশ্মি',
        correctOption: 'b',
        explanation: 'রন্টজেন আবিষ্কৃত উচ্চ ভেদনক্ষমতাসম্পন্ন এক্স-রে মানবদেহের হাড়ের অভ্যন্তরীণ গঠন ও ফ্র্যাকচার দেখতে ব্যবহৃত হয়।',
      },
      {
        serialNumber: 35,
        questionText: 'আল্ট্রাসনোগ্রাফিতে কোন কম্পাঙ্কের শব্দ তরঙ্গ ব্যবহার করা হয়?',
        optionA: 'শ্রাব্য শব্দ (২০-২০,০০০ Hz)',
        optionB: 'শব্দোত্তর তরঙ্গ (Ultrasound > 20,000 Hz)',
        optionC: 'শব্দেতর তরঙ্গ (< ২০ Hz)',
        optionD: 'রেডিও তরঙ্গ',
        correctOption: 'b',
        explanation: 'আল্ট্রাসনোগ্রাফিতে ১ থেকে ১০ মেগাহার্টজ উচ্চ কম্পাঙ্কের শব্দোত্তর (Ultrasound) তরঙ্গের প্রতিধ্বনি কাজে লাগানো হয়।',
      },
    ],
  },

  // =========================================================================
  // 3. COMMERCE GROUP — হিসাববিজ্ঞান (SSC Accounting)
  // SSC 2016 ঢাকা বোর্ড - Verified 40 MCQs
  // =========================================================================
  {
    subjectName: 'SSC Accounting',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2016,
    title: 'SSC 2016: হিসাববিজ্ঞান (ঢাকা বোর্ড)',
    durationMinutes: 40,
    totalMarks: 40,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। ৪০টি প্রশ্ন, সময় ৪০ মিনিট।',
    stream: 'commerce',
    questions: [
      {
        serialNumber: 1,
        questionText: 'হিসাববিজ্ঞানের জনক কে?',
        optionA: 'লুকা প্যাসিওলি',
        optionB: 'অ্যাডাম স্মিথ',
        optionC: 'এফ ডব্লিউ টেলর',
        optionD: 'হেনরি ফেওল',
        correctOption: 'a',
        explanation: 'ইতালীয় গণিতবিদ লুকা প্যাসিওলি ১৪৯৪ সালে দু-তরফা দাখিলা পদ্ধতির মূলনীতি সংবলিত বই প্রকাশ করে হিসাববিজ্ঞানের জনক হিসেবে পরিচিত হন।',
      },
      {
        serialNumber: 2,
        questionText: 'আধুনিক হিসাববিজ্ঞানের মূল ভিত্তি কোনটি?',
        optionA: 'একতরফা দাখিলা পদ্ধতি',
        optionB: 'দু-তরফা দাখিলা পদ্ধতি',
        optionC: 'নগদান পদ্ধতি',
        optionD: 'বাজেটীয় নিয়ন্ত্রণ',
        correctOption: 'b',
        explanation: 'প্রতিটি আর্থিক লেনদেনের দুটি পক্ষ ডেবিট ও ক্রেডিট সমান অঙ্কে লিপিবদ্ধ করার দু-তরফা দাখিলা পদ্ধতিই আধুনিক হিসাবের ভিত্তি।',
      },
      {
        serialNumber: 3,
        questionText: 'হিসাববিজ্ঞানের মৌলিক সমীকরণ কোনটি?',
        optionA: 'A = L + E',
        optionB: 'A = L - E',
        optionC: 'E = A + L',
        optionD: 'L = A + E',
        correctOption: 'a',
        explanation: 'মৌলিক হিসাব সমীকরণ: সম্পদ (Assets) = দায় (Liabilities) + মালিকানাস্বত্ব (Equity)।',
      },
      {
        serialNumber: 4,
        questionText: 'নগদে পণ্য বিক্রয় ১০,০০০ টাকা—এর ফলে হিসাব সমীকরণে কী পরিবর্তন ঘটে?',
        optionA: 'A বৃদ্ধি ও L বৃদ্ধি',
        optionB: 'A বৃদ্ধি ও E বৃদ্ধি',
        optionC: 'A বৃদ্ধি ও A হ্রাস',
        optionD: 'L হ্রাস ও E বৃদ্ধি',
        correctOption: 'b',
        explanation: 'নগদ টাকা আসায় সম্পদ (A) বৃদ্ধি পায় এবং আয় হওয়ায় মালিকানাস্বত্ব (E) বৃদ্ধি পায়।',
      },
      {
        serialNumber: 5,
        questionText: 'ব্যবসায়ের মূল উদ্দেশ্য কী?',
        optionA: 'সমাজসেবা',
        optionB: 'মুনাফা অর্জন',
        optionC: 'জনকল্যাণ',
        optionD: 'কর্মসংস্থান সৃষ্টি',
        correctOption: 'b',
        explanation: 'যেকোনো বাণিজ্যিক প্রতিষ্ঠানের মূখ্য ও প্রধান উদ্দেশ্য হলো বৈধ উপায়ে মুনাফা অর্জন করা।',
      },
      {
        serialNumber: 6,
        questionText: 'লেনদেনের প্রামাণ্য দলিল কোনটি?',
        optionA: 'চালান ও ভাউচার',
        optionB: 'বিজ্ঞাপন',
        optionC: 'কার্যাদেশ',
        optionD: 'কর্মসূচি',
        correctOption: 'a',
        explanation: 'চালান, ক্যাশমেমো, ভাউচার ও ডেবিট/ক্রেডিট নোট লেনদেনের অন্যতম প্রাথমিক প্রামাণ্য দলিল।',
      },
      {
        serialNumber: 7,
        questionText: 'পণ্য ক্রয়ের সময় ক্রেতা বিক্রেতার নিকট হতে কোন দলিলটি পেয়ে থাকে?',
        optionA: 'ডেবিট নোট',
        optionB: 'চালান',
        optionC: 'ক্রেডিট ভাউচার',
        optionD: 'ব্যাংক বিবরণী',
        correctOption: 'b',
        explanation: 'বাকিতে বা নগদে পণ্য বিক্রয়ের সময় বিক্রেতা ক্রেতাকে মালের বিস্তারিত উল্লেখসহ চালান প্রদান করেন।',
      },
      {
        serialNumber: 8,
        questionText: 'হিসাবের প্রাথমিক বই কোনটি?',
        optionA: 'খতিয়ান',
        optionB: 'জাবেদা (Journal)',
        optionC: 'রেওয়ামিল',
        optionD: 'উদ্বৃত্তপত্র',
        correctOption: 'b',
        explanation: 'লেনদেন সংঘটিত হওয়ার পর তারিখের ক্রমানুসারে সর্বপ্রথম জাবেদায় ডেবিট-ক্রেডিট বিশ্লেষণ করে লিপিবদ্ধ করা হয়।',
      },
      {
        serialNumber: 9,
        questionText: 'হিসাবের পাকা বই বা প্রধান বই কাকে বলা হয়?',
        optionA: 'জাবেদা',
        optionB: 'খতিয়ান (Ledger)',
        optionC: 'নগদান বই',
        optionD: 'রেওয়ামিল',
        correctOption: 'b',
        explanation: 'খতিয়ানে বিভিন্ন হিসাবের চূড়ান্ত উদ্বৃত্ত স্থায়ীভাবে সংরক্ষিত থাকে বলে একে পাকা বই বা King of books বলা হয়।',
      },
      {
        serialNumber: 10,
        questionText: 'অনুপার্জিত আয় বা অগ্রিম প্রাপ্ত আয় প্রতিষ্ঠানের জন্য কী?',
        optionA: 'সম্পদ',
        optionB: 'দায়',
        optionC: 'ব্যয়',
        optionD: 'মালিকানাস্বত্ব',
        correctOption: 'b',
        explanation: 'ভবিষ্যতে সেবার বিনিময়ে আগেই অর্থ গ্রহণ করায় তা প্রতিষ্ঠানের চলতি দায় (Current liability)।',
      },
      {
        serialNumber: 11,
        questionText: 'কোনটি মূলধনজাতীয় ব্যয়?',
        optionA: 'যন্ত্রপাতি সংস্থাপন ব্যয়',
        optionB: 'কর্মচারীদের বেতন প্রদান',
        optionC: 'দোকান ভাড়া',
        optionD: 'বিদ্যুৎ বিল',
        correctOption: 'a',
        explanation: 'স্থায়ী সম্পদ অর্জন বা ব্যবহারের উপযোগী করার প্রাথমিক ব্যয় (যেমন যন্ত্রপাতি সংস্থাপন ব্যয়) দীর্ঘমেয়াদি মূলধনজাতীয় ব্যয়।',
      },
      {
        serialNumber: 12,
        questionText: 'অব্যবহৃত মনিহারি প্রতিষ্ঠানের জন্য কী হিসেবে গণ্য হয়?',
        optionA: 'চলতি সম্পদ',
        optionB: 'চলতি দায়',
        optionC: 'মুনাফাজাতীয় আয়',
        optionD: 'স্থায়ী সম্পদ',
        correctOption: 'a',
        explanation: 'বছর শেষে যে মনিহারি দ্রব্যাদি অবিক্রিত বা অবশিষ্ট থাকে তা আগামী বছরের চলতি সম্পদ।',
      },
      {
        serialNumber: 13,
        questionText: 'রেওয়ামিল প্রস্তুত করার মূল উদ্দেশ্য কী?',
        optionA: 'লাভ-ক্ষতি নির্ণয়',
        optionB: 'হিসাবের গাণিতিক নির্ভুলতা যাচাই',
        optionC: 'আর্থিক অবস্থা জানা',
        optionD: 'কর ফাঁকি রোধ',
        correctOption: 'b',
        explanation: 'খতিয়ানের ডেবিট ও ক্রেডিট উদ্বৃত্তগুলোর সমতার মাধ্যমে হিসাবের গাণিতিক শুদ্ধতা যাচাই করতে রেওয়ামিল করা হয়।',
      },
      {
        serialNumber: 14,
        questionText: 'রেওয়ামিলে সাধারণত অন্তর্ভুক্ত হয় না কোনটি?',
        optionA: 'প্রারম্ভিক মজুদ পণ্য',
        optionB: 'সমাপনী মজুদ পণ্য',
        optionC: 'মূলধন',
        optionD: 'বিক্রয় হিসাব',
        correctOption: 'b',
        explanation: 'প্রারম্ভিক মজুদ ও ক্রয়ের মধ্যেই সমাপনী মজুদ অন্তর্ভুক্ত থাকায় সাধারণত সমাপনী মজুদ রেওয়ামিলে আসে না।',
      },
      {
        serialNumber: 15,
        questionText: 'যেসব ভুল রেওয়ামিলে ধরা পড়ে না তাকে কয় ভাগে ভাগ করা যায়?',
        optionA: '২ ভাগে',
        optionB: '৩ ভাগে',
        optionC: '৪ ভাগে',
        optionD: '৫ ভাগে',
        correctOption: 'a',
        explanation: 'রেওয়ামিলে অমিল না ঘটানো ভুল প্রধানত দুই প্রকার: নীতিগত ভুল এবং করণিক ভুল।',
      },
      {
        serialNumber: 16,
        questionText: 'কোন হিসাবটি ডেবিট উদ্বৃত্ত প্রকাশ করে?',
        optionA: 'প্রদেয় হিসাব',
        optionB: 'প্রাপ্য হিসাব',
        optionC: 'মূলধন হিসাব',
        optionD: 'অনুপার্জিত সেবা আয়',
        correctOption: 'b',
        explanation: 'প্রাপ্য হিসাব (Accounts Receivable) প্রতিষ্ঠানের সম্পদ, যার স্বাভাবিক উদ্বৃত্ত সর্বদা ডেবিট।',
      },
      {
        serialNumber: 17,
        questionText: 'দোকানদার কর্তৃক পণ্য উত্তোলন হিসাবভুক্ত হবে কোন জাবেদায়?',
        optionA: 'উত্তোলন হিসাব ডেবিট, ক্রয় হিসাব ক্রেডিট',
        optionB: 'ক্রয় হিসাব ডেবিট, উত্তোলন হিসাব ক্রেডিট',
        optionC: 'নগদান হিসাব ডেবিট, বিক্রয় হিসাব ক্রেডিট',
        optionD: 'উত্তোলন হিসাব ডেবিট, বিক্রয় হিসাব ক্রেডিট',
        correctOption: 'a',
        explanation: 'মালিক কর্তৃক পণ্য উত্তোলনে মালিকানাস্বত্ব কমায় উত্তোলন ডেবিট এবং ক্রয়মূল্যে পণ্য কমায় ক্রয় ক্রেডিট হয়।',
      },
      {
        serialNumber: 18,
        questionText: 'বাট্টা প্রধানত কত প্রকার?',
        optionA: '২ প্রকার',
        optionB: '৩ প্রকার',
        optionC: '৪ প্রকার',
        optionD: '৫ প্রকার',
        correctOption: 'a',
        explanation: 'বাট্টা মূলত দুই প্রকার: কারবারি বাট্টা এবং নগদ বাট্টা।',
      },
      {
        serialNumber: 19,
        questionText: 'কারবারি বাট্টা হিসাবের বইয়ে—',
        optionA: 'সর্বদা লেখা হয়',
        optionB: 'কখনোই লেখা হয় না',
        optionC: 'বছর শেষে লেখা হয়',
        optionD: 'শুধু জাবেদায় লেখা হয়',
        correctOption: 'b',
        explanation: 'ক্রয়-বিক্রয়ের সময় পণ্যের তালিকা মূল্যের ওপর ছাড়কৃত কারবারি বাট্টা বাদ দিয়ে প্রকৃত মূল্যেই লেনদেন রেকর্ড করা হয়।',
      },
      {
        serialNumber: 20,
        questionText: 'তিন ঘরা নগদান বইয়ে কয়টি টাকার ঘর থাকে?',
        optionA: '২টি',
        optionB: '৪টি',
        optionC: '৬টি',
        optionD: '৮টি',
        correctOption: 'c',
        explanation: 'উভয় পাশে নগদ, ব্যাংক ও বাট্টা মিলিয়ে মোট ৩+৩ = ৬টি টাকার কলাম থাকে।',
      },
      {
        serialNumber: 21,
        questionText: 'কন্ট্রা এন্ট্রি (Contra Entry) দ্বারা কী বোঝায়?',
        optionA: 'উভয়মুখী দাখিলা',
        optionB: 'ভুল সংশোধনী দাখিলা',
        optionC: 'সমন্বয় দাখিলা',
        optionD: 'সমাপনী দাখিলা',
        correctOption: 'a',
        explanation: 'যে লেনদেন দ্বারা একই সাথে নগদান ও ব্যাংক হিসাব বিপরীত দিকে প্রভাবিত হয় তাকে বিপরীত বা কন্ট্রা দাখিলা বলে।',
      },
      {
        serialNumber: 22,
        questionText: 'ব্যাংক বিবরণী কে প্রস্তুত করে?',
        optionA: 'আমানতকারী',
        optionB: 'সংশ্লিষ্ট ব্যাংক',
        optionC: 'হিসাবরক্ষক',
        optionD: 'নিরীক্ষক',
        correctOption: 'b',
        explanation: 'ব্যাংক বিবরণী বা পাসবই ব্যাংক কর্তৃক তার গ্রাহকের লেনদেনের হিসাব সংরক্ষণের বিবরণী।',
      },
      {
        serialNumber: 23,
        questionText: 'আর্থিক বিবরণীর প্রথম ধাপ কোনটি?',
        optionA: 'মালিকানাস্বত্ব বিবরণী',
        optionB: 'বিশব্দ আয় বিবরণী',
        optionC: 'আর্থিক অবস্থার বিবরণী',
        optionD: 'নগদ প্রবাহ বিবরণী',
        correctOption: 'b',
        explanation: 'নির্দিষ্ট হিসাবকালের লাভ বা ক্ষতি নির্ণয়ের লক্ষ্যে সর্বপ্রথম বিশদ আয় বিবরণী তৈরি করা হয়।',
      },
      {
        serialNumber: 24,
        questionText: 'মোট লাভ কীভাবে নির্ণয় করা হয়?',
        optionA: 'নিট বিক্রয় - বিক্রীত পণ্যের ব্যয়',
        optionB: 'বিক্রয় + ক্রয়',
        optionC: 'নিট লাভ - পরিচালন ব্যয়',
        optionD: 'মোট আয় - মোট ব্যয়',
        correctOption: 'a',
        explanation: 'নিট বিক্রয় থেকে বিক্রীত পণ্যের মোট ব্যয় বাদ দিলে মোট লাভ (Gross Profit) পাওয়া যায়।',
      },
      {
        serialNumber: 25,
        questionText: 'কোনটি প্রত্যক্ষ খরচ?',
        optionA: 'মজুরি',
        optionB: 'অফিস ভাড়া',
        optionC: 'বিজ্ঞাপন খরচ',
        optionD: 'বীমা প্রিমিয়াম',
        correctOption: 'a',
        explanation: 'উৎপাদন বা ক্রয়ের সাথে সরাসরি জড়িত মজুরি, আমদানি শুল্ক, জাহাজ ভাড়া ইত্যাদি প্রত্যক্ষ খরচ।',
      },
      {
        serialNumber: 26,
        questionText: 'স্থায়ী সম্পদের ক্রমপুঞ্জিত ক্ষয় বা ব্যবহারজনিত মূল্যহ্রাসকে কী বলে?',
        optionA: 'অবচয় (Depreciation)',
        optionB: 'কুঋণ',
        optionC: 'বাট্টা',
        optionD: 'ক্ষতি',
        correctOption: 'a',
        explanation: 'ব্যবহার, সময় অতিবাহিত বা প্রযুক্তির পরিবর্তনের ফলে দৃশ্যমান স্থায়ী সম্পদের মূল্যহ্রাসই অবচয়।',
      },
      {
        serialNumber: 27,
        questionText: 'অনাদায়ী পাওনা বা কুঋণ ব্যবসায়ের জন্য কী?',
        optionA: 'আয়',
        optionB: 'অপরিচালন আয়',
        optionC: 'পরিচালন ক্ষতি / ব্যয়',
        optionD: 'স্থায়ী সম্পদ',
        correctOption: 'c',
        explanation: 'দেনাদারের নিকট থেকে যে অর্থ পাওয়ার কোনো সম্ভাবনা থাকে না তা নিশ্চিত ক্ষতি বা পরিচালন ব্যয়।',
      },
      {
        serialNumber: 28,
        questionText: 'চলতি সম্পদের উদাহরণ কোনটি?',
        optionA: 'আসবাবপত্র',
        optionB: 'দালানকোঠা',
        optionC: 'হাতে নগদ ও দেনাদার',
        optionD: 'সুনাম',
        correctOption: 'c',
        explanation: 'এক বছরের মধ্যে সহজে নগদে রূপান্তরযোগ্য সম্পদ হলো চলতি সম্পদ (যেমন হাতে নগদ, ব্যাংক জমা, দেনাদার)।',
      },
      {
        serialNumber: 29,
        questionText: 'সুনাম কোন ধরনের সম্পদ?',
        optionA: 'অস্পর্শনীয় বা অদৃশ্যমান স্থায়ী সম্পদ',
        optionB: 'চলতি সম্পদ',
        optionC: 'ভুয়া সম্পদ',
        optionD: 'তরল সম্পদ',
        correctOption: 'a',
        explanation: 'সুনাম চোখে দেখা বা স্পর্শ করা যায় না, কিন্তু এর বাণিজ্যিক আর্থিক মূল্য রয়েছে।',
      },
      {
        serialNumber: 30,
        questionText: 'ক্যাশলেস সোসাইটিতে অর্থ স্থানান্তরের জনপ্রিয় মাধ্যম কোনটি?',
        optionA: 'অনলাইন ব্যাংকিং ও মোবাইল ফিন্যান্সিয়াল সার্ভিস (MFS)',
        optionB: 'হাতে নগদ আদান-প্রদান',
        optionC: 'চেক পাঠানো',
        optionD: 'হাতে হাতে পৌঁছানো',
        correctOption: 'a',
        explanation: 'মোবাইল ফিন্যান্সিয়াল সার্ভিস (যেমন বিকাশ, নগদ) ও অনলাইন কার্ড ট্রানজেকশন ক্যাশলেস লেনদেনের মূল হাতিয়ার।',
      },
      {
        serialNumber: 31,
        questionText: 'পণ্য বিক্রয় ৫০,০০০ টাকা, ক্রয় ৩০,০০০ টাকা, প্রারম্ভিক মজুদ ৫,০০০ টাকা, সমাপনী মজুদ ৪,০০০ টাকা হলে বিক্রীত পণ্যের ব্যয় কত?',
        optionA: '৩১,০০০ টাকা',
        optionB: '২৯,০০০ টাকা',
        optionC: '৩৫,০০০ টাকা',
        optionD: '২৬,০০০ টাকা',
        correctOption: 'a',
        explanation: 'বিক্রীত পণ্যের ব্যয় = প্রারম্ভিক মজুদ (৫,০০০) + ক্রয় (৩০,০০০) - সমাপনী মজুদ (৪,০০০) = ৩১,০০০ টাকা।',
      },
      {
        serialNumber: 32,
        questionText: 'খতিয়ানের T-ছকে কয়টি ঘর থাকে?',
        optionA: '৬টি',
        optionB: '৮টি',
        optionC: '১০টি',
        optionD: '৪টি',
        correctOption: 'b',
        explanation: 'T-ছকের উভয় পাশে তারিখ, বিবরণ, জাবেদা পৃষ্ঠা ও টাকা মিলিয়ে মোট ৪+৪ = ৮টি ঘর থাকে।',
      },
      {
        serialNumber: 33,
        questionText: 'কোন নীতি অনুসারে প্রতিটি হিসাবকালের আয়-ব্যয় সেই নির্দিষ্ট সময়েই মেলানো হয়?',
        optionA: 'চলমান প্রতিষ্ঠান ধারণা',
        optionB: 'মিলকরণ নীতি (Matching principle)',
        optionC: 'রক্ষণশীলতা নীতি',
        optionD: 'পূর্ণ প্রকাশ নীতি',
        correctOption: 'b',
        explanation: 'ম্যাচিং প্রিন্সিপল অনুযায়ী নির্দিষ্ট সময়ের অর্জিত আয়ের বিপরীতে সংশ্লিষ্ট সব ব্যয়কে সমন্বয় করা হয়।',
      },
      {
        serialNumber: 34,
        questionText: 'মালিক ব্যবসায় থেকে ব্যক্তিগত ব্যবহারের জন্য নগদ টাকা উত্তোলন করলে কোনটি প্রভাবিত হবে?',
        optionA: 'নগদ হ্রাস ও মালিকানাস্বত্ব হ্রাস',
        optionB: 'নগদ বৃদ্ধি ও দায় হ্রাস',
        optionC: 'সম্পদ বৃদ্ধি ও সম্পদ হ্রাস',
        optionD: 'দায় বৃদ্ধি ও মূলধন বৃদ্ধি',
        correctOption: 'a',
        explanation: 'ব্যবসায় থেকে নগদ অর্থ কমে যাওয়ায় A হ্রাস পায় এবং উত্তোলন করায় Equity হ্রাস পায়।',
      },
      {
        serialNumber: 35,
        questionText: 'ব্যাংক জমার সুদ কোন ধরনের হিসাব?',
        optionA: 'আয় হিসাব',
        optionB: 'ব্যয় হিসাব',
        optionC: 'সম্পদ হিসাব',
        optionD: 'দায় হিসাব',
        correctOption: 'a',
        explanation: 'ব্যাংক জমা অর্থের ওপর যে সুদ প্রদান করে তা গ্রাহক প্রতিষ্ঠানের জন্য একটি পরোক্ষ আয়।',
      },
      {
        serialNumber: 36,
        questionText: 'সম্পদ ও ব্যয় হিসাব সাধারণত কোন উদ্বৃত্ত নির্দেশ করে?',
        optionA: 'ডেবিট উদ্বৃত্ত',
        optionB: 'ক্রেডিট উদ্বৃত্ত',
        optionC: 'শূন্য উদ্বৃত্ত',
        optionD: 'উভয়টিই',
        correctOption: 'a',
        explanation: 'হিসাববিজ্ঞানের নিয়মানুযায়ী সম্পদ ও ব্যয় বৃদ্ধি পেলে ডেবিট এবং এদের স্বাভাবিক জের ডেবিট হয়।',
      },
      {
        serialNumber: 37,
        questionText: 'ক্রয় ফেরত সংক্রান্ত তথ্যের জন্য কোন চিঠি পাঠানো হয়?',
        optionA: 'ডেবিট নোট',
        optionB: 'ক্রেডিট নোট',
        optionC: 'বিল অব এক্সচেঞ্জ',
        optionD: 'চেক',
        correctOption: 'a',
        explanation: 'পণ্য ফেরত দেওয়ার সময় ক্রেতা বিক্রেতার হিসাবকে ডেবিট করেছে জানিয়ে যে পত্র পাঠায় তা ডেবিট নোট।',
      },
      {
        serialNumber: 38,
        questionText: 'হিসাব তথ্যের অভ্যন্তরীণ ব্যবহারকারী কারা?',
        optionA: 'ব্যবস্থাপক ও মালিক',
        optionB: 'পাওনাদার',
        optionC: 'সরকার',
        optionD: 'ঋণদাতা',
        correctOption: 'a',
        explanation: 'ব্যবসায়ের ভেতরের সিদ্ধান্ত গ্রহণকারী যেমন মালিক ও অভ্যন্তরীণ ব্যবস্থাপক হলেন অভ্যন্তরীণ ব্যবহারকারী।',
      },
      {
        serialNumber: 39,
        questionText: 'মূলধন জাতীয় আয় ও মুনাফা জাতীয় আয়ের মধ্যে প্রধান পার্থক্য কী?',
        optionA: 'মূলধন জাতীয় আয় অনিয়মিত ও দীর্ঘমেয়াদি, মুনাফা জাতীয় নিয়মিত ও স্বল্পমেয়াদি',
        optionB: 'উভয়ই সমান',
        optionC: 'মুনাফা জাতীয় আয়ের পরিমাণ সবসময় বেশি হয়',
        optionD: 'মূলধন জাতীয় আয়ে কোনো সুবিধা নেই',
        correctOption: 'a',
        explanation: 'মূলধন জাতীয় আয় বড় অঙ্কের এবং অনিয়মিত ঘটে; অন্যদিকে মুনাফা জাতীয় আয় নিয়মিত পরিচালন কার্যক্রম থেকে আসে।',
      },
      {
        serialNumber: 40,
        questionText: 'হিসাববিজ্ঞানের কোন বৈশিষ্ট্যের জন্য ব্যবসায়ের আর্থিক তথ্য বিভিন্ন বছরের সাথে তুলনা করা যায়?',
        optionA: 'ধারাবাহিকতা ও সামঞ্জস্যতা',
        optionB: 'গোপনীয়তা',
        optionC: 'স্বার্থপরতা',
        optionD: 'জটিলতা',
        correctOption: 'a',
        explanation: 'হিসাব নীতিমালার ধারাবাহিকতা বজায় থাকলে এক বছরের ফলাফলের সাথে অন্য বছরের ফলাফলের সঠিক তুলনা করা সম্ভব হয়।',
      },
    ],
  },

  // =========================================================================
  // 4. COMMON COMPULSORY — সাধারণ গণিত (SSC General Mathematics)
  // SSC 2016 ঢাকা বোর্ড - Verified 40 MCQs
  // =========================================================================
  {
    subjectName: 'SSC General Mathematics',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2016,
    title: 'SSC 2016: সাধারণ গণিত (ঢাকা বোর্ড)',
    durationMinutes: 40,
    totalMarks: 40,
    negativeMark: 0.25,
    instructions: 'প্রতিটি প্রশ্নের মান ১। ভুল উত্তরের জন্য ০.২৫ নম্বর কর্তন হবে। সময় ৪০ মিনিট।',
    stream: 'common',
    questions: [
      {
        serialNumber: 1,
        questionText: 'নিচের কোনটি অমূলদ সংখ্যা?',
        optionA: '√৪',
        optionB: '√৯',
        optionC: '√২',
        optionD: '√১৬',
        correctOption: 'c',
        explanation: 'যে সংখ্যাকে দুটি পূর্ণসংখ্যার ভগ্নাংশ আকারে প্রকাশ করা যায় না তা অমূলদ। √২ একটি সুপরিচিত অমূলদ সংখ্যা।',
      },
      {
        serialNumber: 2,
        questionText: 'A = {১, ২, ৩} হলে P(A) এর উপাদান সংখ্যা কত?',
        optionA: '৩',
        optionB: '৬',
        optionC: '৮',
        optionD: '৯',
        correctOption: 'c',
        explanation: 'উপাদান সংখ্যা n হলে শক্তি সেট P(A) এর উপাদান সংখ্যা ২ⁿ = ২³ = ৮।',
      },
      {
        serialNumber: 3,
        questionText: 'x + 1/x = 3 হলে, x² + 1/x² এর মান কত?',
        optionA: '৭',
        optionB: '৯',
        optionC: '১১',
        optionD: '৫',
        correctOption: 'a',
        explanation: 'x² + 1/x² = (x + 1/x)² - 2 = 3² - 2 = 9 - 2 = 7।',
      },
      {
        serialNumber: 4,
        questionText: 'log₂ 16 এর মান কত?',
        optionA: '২',
        optionB: '৩',
        optionC: '৪',
        optionD: '৮',
        correctOption: 'c',
        explanation: 'যেহেতু 2⁴ = 16, তাই log₂ 16 = log₂ (2⁴) = 4 log₂ 2 = 4।',
      },
      {
        serialNumber: 5,
        questionText: 'a⁰ এর মান কত? (যেখানে a ≠ 0)',
        optionA: '০',
        optionB: '১',
        optionC: 'a',
        optionD: 'অসীম',
        correctOption: 'b',
        explanation: 'সূচকের নিয়মানুযায়ী শূন্য ব্যতীত যেকোনো বাস্তব সংখ্যার ঘাত শূন্য হলে তার মান ১ হয়।',
      },
      {
        serialNumber: 6,
        questionText: 'বৃত্তের পরিধি ও ব্যাসের অনুপাতকে কোন প্রতীক দ্বারা প্রকাশ করা হয়?',
        optionA: 'θ',
        optionB: 'π (পাই)',
        optionC: 'λ',
        optionD: 'α',
        correctOption: 'b',
        explanation: 'বৃত্তের পরিধি (2πr) কে ব্যাস (2r) দিয়ে ভাগ করলে সর্বদা ধ্রুবক π (প্রায় ৩.১৪১৬) পাওয়া যায়।',
      },
      {
        serialNumber: 7,
        questionText: 'একটি ত্রিভুজের তিন কোণের সমষ্টি কত?',
        optionA: '৯০°',
        optionB: '১৮০° বা ২ সমকোণ',
        optionC: '২৭০°',
        optionD: '৩৬০°',
        correctOption: 'b',
        explanation: 'ইউক্লিডীয় জ্যামিতি অনুসারে যেকোনো ত্রিভুজের তিন কোণের যোগফল ১৮০ ডিগ্রি।',
      },
      {
        serialNumber: 8,
        questionText: 'সমকোণী ত্রিভুজের ক্ষেত্রে পিথাগোরাসের উপপাদ্য কোনটি?',
        optionA: 'অতিভুজ² = লম্ব² + ভূমি²',
        optionB: 'লম্ব² = অতিভুজ² + ভূমি²',
        optionC: 'ভূমি² = অতিভুজ² + লম্ব²',
        optionD: 'অতিভুজ = লম্ব + ভূমি',
        correctOption: 'a',
        explanation: 'পিথাগোরাসের সূত্রানুযায়ী সমকোণী ত্রিভুজের অতিভুজের ওপর অঙ্কিত বর্গক্ষেত্র অপর দুই বাহুর ওপর অঙ্কিত বর্গক্ষেত্রের সমষ্টির সমান।',
      },
      {
        serialNumber: 9,
        questionText: 'একটি সমবাহু ত্রিভুজের প্রতি বাহুর দৈর্ঘ্য a হলে ক্ষেত্রফলের সূত্র কোনটি?',
        optionA: '(√3 / 4) a²',
        optionB: '(1 / 2) a²',
        optionC: '√3 a²',
        optionD: '(√3 / 2) a',
        correctOption: 'a',
        explanation: 'সমবাহু ত্রিভুজের ক্ষেত্রফল = (√3 / 4) × বাহু²।',
      },
      {
        serialNumber: 10,
        questionText: 'tan 45° এর মান কত?',
        optionA: '০',
        optionB: '১ / √৩',
        optionC: '১',
        optionD: '√৩',
        correctOption: 'c',
        explanation: 'ত্রিকোণমিতিক কোণানুপাতে tan 45° = sin 45° / cos 45° = (1/√2) / (1/√2) = 1।',
      },
      {
        serialNumber: 11,
        questionText: 'sin²θ + cos²θ এর মান কত?',
        optionA: '০',
        optionB: '১',
        optionC: '২',
        optionD: '-১',
        correctOption: 'b',
        explanation: 'ত্রিকোণমিতির মৌলিক অভেদাবলি: sin²θ + cos²θ = 1।',
      },
      {
        serialNumber: 12,
        questionText: 'সমান্তর ধারা 3 + 7 + 11 + ... এর সাধারণ অন্তর (Common difference) কত?',
        optionA: '৩',
        optionB: '৪',
        optionC: '৭',
        optionD: '২',
        correctOption: 'b',
        explanation: 'সাধারণ অন্তর d = দ্বিতীয় পদ - প্রথম পদ = ৭ - ৩ = ৪।',
      },
      {
        serialNumber: 13,
        questionText: 'কোনো গুণোত্তর ধারার প্রথম পদ a এবং সাধারণ অনুপাত r হলে n-তম পদ কোনটি?',
        optionA: 'arⁿ⁻¹',
        optionB: 'arⁿ',
        optionC: 'a + (n-1)d',
        optionD: 'ar / n',
        correctOption: 'a',
        explanation: 'গুণোত্তর ধারার সাধারণ পদ সূত্র Tₙ = arⁿ⁻¹।',
      },
      {
        serialNumber: 14,
        questionText: 'বৃত্তের একই চাপের ওপর দণ্ডায়মান কেন্দ্রস্থ কোণ বৃত্তস্থ কোণের কত গুণ?',
        optionA: 'অর্ধেক',
        optionB: 'দ্বিগুণ',
        optionC: 'সমান',
        optionD: 'তিনগুণ',
        correctOption: 'b',
        explanation: 'উপপাদ্য অনুসারে বৃত্তের একই চাপের ওপর দণ্ডায়মান কেন্দ্রস্থ কোণ বৃত্তস্থ কোণের দ্বিগুণ (∠AOB = 2∠ACB)।',
      },
      {
        serialNumber: 15,
        questionText: 'অর্ধবৃত্তস্থ কোণের পরিমাপ কত?',
        optionA: '৪৫°',
        optionB: '৬০°',
        optionC: '৯০° বা এক সমকোণ',
        optionD: '১৮০°',
        correctOption: 'c',
        explanation: 'অর্ধবৃত্তস্থ কোণ সর্বদা এক সমকোণ বা ৯০ ডিগ্রি হয়।',
      },
      {
        serialNumber: 16,
        questionText: 'একটি বৃত্তের ব্যাসার্ধ 7 cm হলে এর ক্ষেত্রফল কত? (π = 22/7)',
        optionA: '44 cm²',
        optionB: '154 cm²',
        optionC: '88 cm²',
        optionD: '144 cm²',
        correctOption: 'b',
        explanation: 'ক্ষেত্রফল = πr² = (22/7) × 7 × 7 = 154 বর্গ সেমি।',
      },
      {
        serialNumber: 17,
        questionText: 'উপাত্তের সংখ্যাগুলোর গড়, মধ্যক ও প্রচুরক হলো—',
        optionA: 'বিস্তার পরিমাপ',
        optionB: 'কেন্দ্রীয় প্রবণতার পরিমাপ',
        optionC: 'সম্ভাবনা',
        optionD: 'লেখচিত্র',
        correctOption: 'b',
        explanation: 'উপাত্তগুলোর কেন্দ্রের মানের দিকে জড়ো হওয়ার প্রবণতা নির্দেশ করে গড়, মধ্যক ও প্রচুরক।',
      },
      {
        serialNumber: 18,
        questionText: '১০, ১২, ১৪, ১২, ১৬, ১২, ১৮ সংখ্যাগুলোর প্রচুরক (Mode) কোনটি?',
        optionA: '১০',
        optionB: '১২',
        optionC: '১৪',
        optionD: '১৬',
        correctOption: 'b',
        explanation: '১২ সংখ্যাটি সর্বোচ্চ ৩ বার এসেছে, তাই এর প্রচুরক ১২।',
      },
      {
        serialNumber: 19,
        questionText: 'একটি কয়েন একবার টস করলে হেড (Head) আসার সম্ভাবনা কত?',
        optionA: '১',
        optionB: '১/২',
        optionC: '১/৪',
        optionD: '০',
        correctOption: 'b',
        explanation: 'কয়েনের দুটি সম্ভাব্য ফলাফল {H, T}; অনুকূল ফলাফল ১টি, তাই সম্ভাবনা ১/২।',
      },
      {
        serialNumber: 20,
        questionText: 'একটি বর্গের বাহুর দৈর্ঘ্য দ্বিগুণ করা হলে তার ক্ষেত্রফল কতগুণ বৃদ্ধি পাবে?',
        optionA: '২ গুণ',
        optionB: '৩ গুণ',
        optionC: '৪ গুণ',
        optionD: '৮ গুণ',
        correctOption: 'c',
        explanation: 'ক্ষেত্রফল বাহুর বর্গের সমানুপাতিক। বাহু 2a হলে নতুন ক্ষেত্রফল (2a)² = 4a², অর্থাৎ ৪ গুণ হবে।',
      },
      {
        serialNumber: 21,
        questionText: 'রম্বসের কর্ণদ্বয় পরস্পরকে কীভাবে সমদ্বিখণ্ডিত করে?',
        optionA: 'সূক্ষ্মকোণে',
        optionB: 'সমকোণে',
        optionC: 'স্থূলকোণে',
        optionD: 'অসমভাবে',
        correctOption: 'b',
        explanation: 'রম্বসের কর্ণদ্বয় পরস্পরকে সমকোণে (৯০°) সমদ্বিখণ্ডিত করে।',
      },
      {
        serialNumber: 22,
        questionText: '২x + y = ৮ এবং x - y = ১ হলে x এর মান কত?',
        optionA: '১',
        optionB: '২',
        optionC: '৩',
        optionD: '৪',
        correctOption: 'c',
        explanation: 'উভয় সমীকরণ যোগ করলে: ৩x = ৯, বা x = ৩।',
      },
      {
        serialNumber: 23,
        questionText: 'ax² + bx + c = 0 সমীকরণের নিশ্চায়ক (Discriminant) কোনটি?',
        optionA: 'b² - 4ac',
        optionB: 'b² + 4ac',
        optionC: '4ac - b²',
        optionD: '√b² - 4ac',
        correctOption: 'a',
        explanation: 'দ্বিঘাত সমীকরণের মূলের প্রকৃতি নির্ণায়ক রাশি হলো D = b² - 4ac।',
      },
      {
        serialNumber: 24,
        questionText: 'D = b² - 4ac > 0 এবং পূর্ণবর্গ হলে সমীকরণের মূলদ্বয় কেমন হবে?',
        optionA: 'বাস্তব, অসমান ও মূলদ',
        optionB: 'বাস্তব ও সমান',
        optionC: 'জটিল',
        optionD: 'কাল্পনিক',
        correctOption: 'a',
        explanation: 'নিশ্চায়ক ধনাত্মক ও পূর্ণবর্গ হলে মূলদ্বয় সর্বদা বাস্তব, অসমান ও মূলদ হয়।',
      },
      {
        serialNumber: 25,
        questionText: 'বৃত্তের বহিঃস্থ কোনো বিন্দু থেকে বৃত্তে কয়টি স্পর্শক আঁকা যায়?',
        optionA: '১টি',
        optionB: '২টি',
        optionC: '৩টি',
        optionD: 'অসংখ্য',
        correctOption: 'b',
        explanation: 'বৃত্তের বাইরের যেকোনো নির্দিষ্ট বিন্দু থেকে বৃত্তের ওপর ঠিক ২টি স্পর্শক টানা সম্ভব এবং এদের দৈর্ঘ্য সমান।',
      },
      {
        serialNumber: 26,
        questionText: 'sec²θ - tan²θ এর মান কত?',
        optionA: '০',
        optionB: '১',
        optionC: '২',
        optionD: '-১',
        correctOption: 'b',
        explanation: 'ত্রিকোণমিতির সূত্রানুযায়ী 1 + tan²θ = sec²θ, অতএব sec²θ - tan²θ = 1।',
      },
      {
        serialNumber: 27,
        questionText: 'একটি ঘনকের ধার a হলে এর সমগ্র পৃষ্ঠের ক্ষেত্রফল কত?',
        optionA: '4a²',
        optionB: '6a²',
        optionC: 'a³',
        optionD: '12a',
        correctOption: 'b',
        explanation: 'ঘনকের ৬টি সমান বর্গাকার তল থাকে, তাই সমগ্রতলের ক্ষেত্রফল 6a²।',
      },
      {
        serialNumber: 28,
        questionText: 'কোন চতুর্ভুজের বিপরীত বাহুগুলো পরস্পর সমান ও সমান্তরাল কিন্তু কোণগুলো সমকোণ নয়?',
        optionA: 'রম্বস বা সামান্তরিক',
        optionB: 'আয়তক্ষেত্র',
        optionC: 'বর্গক্ষেত্র',
        optionD: 'ট্রাপিজিয়াম',
        correctOption: 'a',
        explanation: 'সামান্তরিকের বিপরীত বাহু সমান ও সমান্তরাল হলেও কোণগুলো সমকোণ হয় না।',
      },
      {
        serialNumber: 29,
        questionText: '১ থেকে ১০ পর্যন্ত মৌলিক সংখ্যা কয়টি?',
        optionA: '৩টি',
        optionB: '৪টি',
        optionC: '৫টি',
        optionD: '৬টি',
        correctOption: 'b',
        explanation: '১ থেকে ১০ এর মধ্যে ৪টি মৌলিক সংখ্যা রয়েছে: ২, ৩, ৫ এবং ৭।',
      },
      {
        serialNumber: 30,
        questionText: 'x² - 5x + 6 = 0 এর উৎপাদকদ্বয় কী কী?',
        optionA: '(x - 2)(x - 3)',
        optionB: '(x + 2)(x + 3)',
        optionC: '(x - 1)(x - 6)',
        optionD: '(x + 1)(x - 6)',
        correctOption: 'a',
        explanation: 'x² - 3x - 2x + 6 = x(x - 3) - 2(x - 3) = (x - 2)(x - 3)।',
      },
      {
        serialNumber: 31,
        questionText: 'বৃত্তের পরিধির সূত্র কোনটি?',
        optionA: 'πr²',
        optionB: '2πr',
        optionC: 'πd²',
        optionD: '2πr²',
        correctOption: 'b',
        explanation: 'বৃত্তের ব্যাসার্ধ r হলে পরিধি C = 2πr।',
      },
      {
        serialNumber: 32,
        questionText: 'সূর্যের উন্নতি কোণ ৩০° থেকে বৃদ্ধি পেয়ে ৬০° হলে একটি মিনারের ছায়ার দৈর্ঘ্য—',
        optionA: 'বৃদ্ধি পাবে',
        optionB: 'হ্রাস পাবে',
        optionC: 'অপরিবর্তিত থাকবে',
        optionD: 'দ্বিগুণ হবে',
        correctOption: 'b',
        explanation: 'উন্নতি কোণ বাড়লে ছায়া খাটো হয়ে যায়, অর্থাৎ দৈর্ঘ্য হ্রাস পায়।',
      },
      {
        serialNumber: 33,
        questionText: 'ক্রমযোজিত গণসংখ্যা সারণির প্রয়োজন হয় কোনটি নির্ণয়ে?',
        optionA: 'গড়',
        optionB: 'মধ্যক',
        optionC: 'প্রচুরক',
        optionD: 'পরিসর',
        correctOption: 'b',
        explanation: 'শ্রেণিকৃত উপাত্তের মধ্যক ও অজিভ রেখা অঙ্কনে ক্রমযোজিত গণসংখ্যার প্রয়োজন হয়।',
      },
      {
        serialNumber: 34,
        questionText: 'একটি চাকার ব্যাস ১.৪ মিটার হলে চাকাটি একবার ঘুরলে কত দূরত্ব অতিক্রম করবে? (π = 22/7)',
        optionA: '২.২ মিটার',
        optionB: '৪.৪ মিটার',
        optionC: '৮.৮ মিটার',
        optionD: '১.৪ মিটার',
        correctOption: 'b',
        explanation: 'এক ঘূর্ণনে দূরত্ব = পরিধি = πd = (22/7) × 1.4 = 4.4 মিটার।',
      },
      {
        serialNumber: 35,
        questionText: 'কোন ভগ্নাংশের লব ও হরকে একই অশূন্য সংখ্যা দ্বারা গুণ বা ভাগ করলে ভগ্নাংশটির মান—',
        optionA: 'অপরিবর্তিত থাকে',
        optionB: 'বৃদ্ধি পায়',
        optionC: 'হ্রাস পায়',
        optionD: 'শূন্য হয়',
        correctOption: 'a',
        explanation: 'সমতুল ভগ্নাংশের ধর্ম অনুযায়ী লব ও হরকে একই অশূন্য সংখ্যা দিয়ে গুণ বা ভাগ করলে মান একই থাকে।',
      },
      {
        serialNumber: 36,
        questionText: 'ত্রিভুজের যেকোনো দুই বাহুর সমষ্টি তার তৃতীয় বাহু অপেক্ষা—',
        optionA: 'ক্ষুদ্রতর',
        optionB: 'বৃহত্তর',
        optionC: 'সমান',
        optionD: 'অর্ধেক',
        correctOption: 'b',
        explanation: 'জ্যামিতির মৌলিক নীতি অনুযায়ী ত্রিভুজের যেকোনো দুই বাহুর যোগফল তৃতীয় বাহু অপেক্ষা বৃহত্তর।',
      },
      {
        serialNumber: 37,
        questionText: 'বৃত্তস্থ চতুর্ভুজের বিপরীত কোণদ্বয়ের সমষ্টি কত?',
        optionA: '৯০°',
        optionB: '১৮০° বা ২ সমকোণ',
        optionC: '২৭০°',
        optionD: '৩৬০°',
        correctOption: 'b',
        explanation: 'বৃত্তে অন্তর্লিখিত চতুর্ভুজের যেকোনো দুটি বিপরীত কোণের সমষ্টি সম্পূরক বা ১৮০°।',
      },
      {
        serialNumber: 38,
        questionText: 'ক্যালকুলেটরে e এর মান কত?',
        optionA: '৩.১৪১৬',
        optionB: '২.৭১৮২৮...',
        optionC: '১.৪১৪',
        optionD: '১.৭৩২',
        correctOption: 'b',
        explanation: 'স্বাভাবিক লগারিদমের ভিত্তি অয়লার ধ্রুবক e এর মান প্রায় ২.৭১৮২৮।',
      },
      {
        serialNumber: 39,
        questionText: 'একটি সিলিন্ডারের ভূমির ব্যাসার্ধ r এবং উচ্চতা h হলে এর আয়তনের সূত্র কোনটি?',
        optionA: 'πr²h',
        optionB: '2πrh',
        optionC: '(1/3)πr²h',
        optionD: '4/3 πr³',
        correctOption: 'a',
        explanation: 'বেলন বা সিলিন্ডারের আয়তন = ভূমির ক্ষেত্রফল × উচ্চতা = πr²h।',
      },
      {
        serialNumber: 40,
        questionText: 'সার্বিক সেট U এবং সেট A হলে, A ∩ A′ এর মান কোনটি?',
        optionA: 'U',
        optionB: '∅ (ফাঁকা সেট)',
        optionC: 'A',
        optionD: 'A′',
        correctOption: 'b',
        explanation: 'একটি সেট এবং তার পূরক সেটের মধ্যে কোনো সাধারণ উপাদান থাকে না, তাই এদের ছেদ ফাঁকা সেট ∅।',
      },
    ],
  },
];

export async function runSsc2016BoardQuestionSeeder() {
  const client = await pool.connect();
  try {
    console.log('🚀 Starting SSC 2016 Board Questions Safe Ingestion...');

    for (const examData of ssc2016BoardExams) {
      // 1. Find the matching SSC subject
      const subRes = await client.query(
        `SELECT id, name_bn FROM subjects WHERE name = $1 AND academic_level = 'ssc' LIMIT 1`,
        [examData.subjectName]
      );

      if (subRes.rowCount === 0) {
        console.warn(`⚠️ Subject not found for: ${examData.subjectName}. Skipping.`);
        continue;
      }

      const subjectId = subRes.rows[0].id;
      const subjectNameBn = subRes.rows[0].name_bn;

      // 2. Check if this exact board exam already exists
      const existingExamRes = await client.query(
        `SELECT id FROM exams WHERE subject_id = $1 AND title = $2 LIMIT 1`,
        [subjectId, examData.title]
      );

      let examId: string;
      if (existingExamRes.rowCount && existingExamRes.rowCount > 0) {
        examId = existingExamRes.rows[0].id;
        console.log(`ℹ️ Board exam already exists: "${examData.title}". Updating metadata...`);
        await client.query(
          `UPDATE exams
           SET exam_type = 'board_question', board_name = $1, exam_year = $2,
               duration_minutes = $3, total_marks = $4, negative_mark = $5, is_published = TRUE
           WHERE id = $6`,
          [
            examData.boardName,
            examData.examYear,
            examData.durationMinutes,
            examData.totalMarks,
            examData.negativeMark,
            examId,
          ]
        );
      } else {
        const insertExamRes = await client.query(
          `INSERT INTO exams (
             subject_id, title, serial_number, duration_minutes, total_marks,
             negative_mark, instructions, is_published, curriculum_version,
             academic_level, exam_type, board_name, exam_year
           )
           VALUES ($1, $2, 1, $3, $4, $5, $6, TRUE, 'bangla', 'ssc', 'board_question', $7, $8)
           RETURNING id`,
          [
            subjectId,
            examData.title,
            examData.durationMinutes,
            examData.totalMarks,
            examData.negativeMark,
            examData.instructions,
            examData.boardName,
            examData.examYear,
          ]
        );
        examId = insertExamRes.rows[0].id;
        console.log(`✅ Created board exam: "${examData.title}" (ID: ${examId}) for ${subjectNameBn}`);
      }

      // 3. Insert questions safely if not already present
      const qCountRes = await client.query(`SELECT count(*) FROM questions WHERE exam_id = $1`, [examId]);
      const currentQCount = parseInt(qCountRes.rows[0].count, 10);

      if (currentQCount < examData.questions.length) {
        console.log(`📥 Inserting ${examData.questions.length} questions for "${examData.title}"...`);
        for (const q of examData.questions) {
          const qExists = await client.query(
            `SELECT id FROM questions WHERE exam_id = $1 AND serial_number = $2`,
            [examId, q.serialNumber]
          );

          if (qExists.rowCount === 0) {
            await client.query(
              `INSERT INTO questions (
                 exam_id, question_text, option_a, option_b, option_c, option_d,
                 correct_option, explanation, serial_number
               )
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
              [
                examId,
                q.questionText,
                q.optionA,
                q.optionB,
                q.optionC,
                q.optionD,
                q.correctOption,
                q.explanation,
                q.serialNumber,
              ]
            );
          }
        }
        console.log(`✅ Questions successfully populated for: ${examData.title}`);
      } else {
        console.log(`ℹ️ All questions already seeded for: ${examData.title}`);
      }
    }

    console.log('🎉 SSC 2016 Board Questions Safe Ingestion Complete!');
  } catch (err) {
    console.error('❌ Error during SSC board question seeding:', err);
    throw err;
  } finally {
    client.release();
  }
}

// Auto-run when executed directly via tsx
if (process.argv[1]?.endsWith('seed_ssc_2016_board_questions.ts')) {
  runSsc2016BoardQuestionSeeder()
    .then(() => {
      console.log('Done!');
      process.exit(0);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
