import { pool } from './db.js';

export interface RawBoardQuestion {
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: 'a' | 'b' | 'c' | 'd';
  explanation: string;
  serialNumber: number;
}

export interface ComprehensiveBoardExamData {
  academicLevel: 'ssc' | 'hsc';
  subjectName: string; // Matches subjects.name in DB
  boardName: string; // e.g. 'ঢাকা বোর্ড', 'সমন্বিত বোর্ড (সকল)', 'কুমিল্লা বোর্ড', 'রাজশাহী বোর্ড', 'চট্টগ্রাম বোর্ড'
  examYear: number; // 2018 - 2025
  title: string;
  durationMinutes: number;
  totalMarks: number;
  negativeMark: number;
  instructions: string;
  stream: 'science' | 'commerce' | 'humanities' | 'common' | 'optional';
  questions: RawBoardQuestion[];
}

export const comprehensiveBoardExams: ComprehensiveBoardExamData[] = [
  // =========================================================================
  // --- SSC BOARD QUESTIONS (2018 - 2025) ---
  // =========================================================================

  // [1] SSC 2018 - General Mathematics (ঢাকা বোর্ড) - Common Compulsory
  {
    academicLevel: 'ssc',
    subjectName: 'SSC General Mathematics',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2018,
    title: 'SSC 2018: সাধারণ গণিত (ঢাকা বোর্ড)',
    durationMinutes: 30,
    totalMarks: 30,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ৩০ মিনিট।',
    stream: 'common',
    questions: [
      {
        serialNumber: 1,
        questionText: 'যদি A = {1, 2, 3} এবং B = {2, 3, 4} হয়, তবে A ∩ B = কত?',
        optionA: '{1, 4}',
        optionB: '{2, 3}',
        optionC: '{1, 2, 3, 4}',
        optionD: '∅',
        correctOption: 'b',
        explanation: 'উভয় সেটের সাধারণ উপাদান (common elements) হলো ২ এবং ৩। অতএব A ∩ B = {2, 3}।',
      },
      {
        serialNumber: 2,
        questionText: 'কোনো বৃত্তের ব্যাসার্ধ 7 সেমি হলে তার পরিধি কত সেমি? (π = 22/7)',
        optionA: '২২',
        optionB: '৪৪',
        optionC: '৮৮',
        optionD: '১৫৪',
        correctOption: 'b',
        explanation: 'বৃত্তের পরিধি = 2πr = 2 × (22/7) × 7 = 44 সেমি।',
      },
      {
        serialNumber: 3,
        questionText: 'log₂ 16 এর মান কত?',
        optionA: '২',
        optionB: '৩',
        optionC: '৪',
        optionD: '৮',
        correctOption: 'c',
        explanation: '১৬ = ২⁴; সুতরাং log₂ (২⁴) = ৪ log₂ ২ = ৪ × ১ = ৪।',
      },
      {
        serialNumber: 4,
        questionText: 'x² - 5x + 6 = 0 সমীকরণের মূলদ্বয় কোনটি?',
        optionA: '1, 6',
        optionB: '2, 3',
        optionC: '-2, -3',
        optionD: '-1, 6',
        correctOption: 'b',
        explanation: 'x² - 2x - 3x + 6 = 0 ⇒ (x - 2)(x - 3) = 0 ⇒ x = 2, 3।',
      },
      {
        serialNumber: 5,
        questionText: 'sin² 45° + cos² 45° এর মান কত?',
        optionA: '০',
        optionB: '১/২',
        optionC: '১',
        optionD: '২',
        correctOption: 'c',
        explanation: 'যেকোনো কোণ θ-এর জন্য ত্রিকোণমিতিক অভেদ sin²θ + cos²θ = ১।',
      },
      {
        serialNumber: 6,
        questionText: 'একটি সমবাহু ত্রিভুজের প্রতি বাহুর দৈর্ঘ্য 4 সেমি হলে এর ক্ষেত্রফল কত বর্গ সেমি?',
        optionA: '4√3',
        optionB: '8√3',
        optionC: '16√3',
        optionD: '2√3',
        correctOption: 'a',
        explanation: 'সমবাহু ত্রিভুজের ক্ষেত্রফল = (√3 / 4) a² = (√3 / 4) × 16 = 4√3 বর্গ সেমি।',
      },
      {
        serialNumber: 7,
        questionText: 'একটি ঘনকের ধার 3 সেমি হলে তার মোট পৃষ্ঠের ক্ষেত্রফল কত বর্গ সেমি?',
        optionA: '৯',
        optionB: '২৭',
        optionC: '৫৪',
        optionD: '৮১',
        correctOption: 'c',
        explanation: 'ঘনকের পৃষ্ঠের মোট ক্ষেত্রফল = 6a² = 6 × 3² = 6 × 9 = 54 বর্গ সেমি।',
      },
      {
        serialNumber: 8,
        questionText: 'tan 60° এর সঠিক মান কোনটি?',
        optionA: '1/√3',
        optionB: '১',
        optionC: '√3',
        optionD: 'অসংজ্ঞায়িত',
        correctOption: 'c',
        explanation: 'ত্রিকোণমিতিক কোণানুপাত সারণী অনুযায়ী tan 60° = √3।',
      },
      {
        serialNumber: 9,
        questionText: 'প্রথম 10টি স্বাভাবিক সংখ্যার সমষ্টি কত?',
        optionA: '৪৫',
        optionB: '৫৫',
        optionC: '৬৫',
        optionD: '১০০',
        correctOption: 'b',
        explanation: 'স্বাভাবিক সংখ্যার সমষ্টি সূত্র S = n(n+1)/2 = 10(11)/2 = 55।',
      },
      {
        serialNumber: 10,
        questionText: 'কোনো সমকোণী ত্রিভুজের সূক্ষ্মকোণদ্বয়ের যোগফল কত ডিগ্রি?',
        optionA: '৪৫°',
        optionB: '৬০°',
        optionC: '৯০°',
        optionD: '১৮০°',
        correctOption: 'c',
        explanation: 'ত্রিভুজের তিন কোণের সমষ্টি ১৮০°। একটি কোণ ৯০° সমকোণ হওয়ায় অপর দুই সূক্ষ্মকোণের সমষ্টি ৯০°।',
      },
    ],
  },

  // [2] SSC 2019 - Physics (পদার্থবিজ্ঞান - ঢাকা বোর্ড) - Science
  {
    academicLevel: 'ssc',
    subjectName: 'SSC Physics',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2019,
    title: 'SSC 2019: পদার্থবিজ্ঞান (ঢাকা বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'তড়িৎ আধানের এসআই (SI) একক কোনটি?',
        optionA: 'অ্যাম্পিয়ার',
        optionB: 'ভোল্ট',
        optionC: 'কুলম্ব',
        optionD: 'ওহম',
        correctOption: 'c',
        explanation: 'তড়িৎ আধানের আন্তর্জাতিক (SI) একক হলো কুলম্ব (Coulomb, C)।',
      },
      {
        serialNumber: 2,
        questionText: 'শব্দ কোন ধরনের তরঙ্গ?',
        optionA: 'অনুদৈর্ঘ্য তরঙ্গ',
        optionB: 'অনুপ্রস্থ তরঙ্গ',
        optionC: 'তাড়িতচৌম্বক তরঙ্গ',
        optionD: 'স্থির তরঙ্গ',
        correctOption: 'a',
        explanation: 'শব্দ মাধ্যমের কণার কম্পনের সমান্তরালে সঞ্চালিত হয়, তাই এটি যান্ত্রিক অনুদৈর্ঘ্য (Longitudinal) তরঙ্গ।',
      },
      {
        serialNumber: 3,
        questionText: 'কোন রঙের আলোর তরঙ্গদৈর্ঘ্য সবচেয়ে বেশি?',
        optionA: 'বেগুনী',
        optionB: 'নীল',
        optionC: 'সবুজ',
        optionD: 'লাল',
        correctOption: 'd',
        explanation: 'দৃশ্যমান বর্ণালীর মধ্যে লাল রঙের আলোর তরঙ্গদৈর্ঘ্য সবচেয়ে বেশি (প্রায় ৭০০ ন্যানোমিটার)।',
      },
      {
        serialNumber: 4,
        questionText: 'একটি উত্তল লেন্সের ফোকাস দূরত্ব 20 সেমি হলে এর ক্ষমতা (Power) কত ডায়োপ্টার?',
        optionA: '+5 D',
        optionB: '-5 D',
        optionC: '+2 D',
        optionD: '+0.05 D',
        correctOption: 'a',
        explanation: 'ক্ষমতা P = 1/f(মিটার) = 1/0.2 = +5 D (উত্তল লেন্সের ক্ষমতা ধনাত্মক)।',
      },
      {
        serialNumber: 5,
        questionText: 'পদার্থের চতুর্থ অবস্থার নাম কী?',
        optionA: 'কঠিন',
        optionB: 'তরল',
        optionC: 'বায়বীয়',
        optionD: 'প্লাজমা',
        correctOption: 'd',
        explanation: 'অতি উচ্চ তাপমাত্রায় আয়নিত গ্যাসীয় অবস্থাকে পদার্থের চতুর্থ অবস্থা বা প্লাজমা অবস্থা বলা হয়।',
      },
      {
        serialNumber: 6,
        questionText: 'কোন বিজ্ঞানী মহাকর্ষ সূত্র আবিষ্কার করেন?',
        optionA: 'আইনস্টাইন',
        optionB: 'স্যার আইজ্যাক নিউটন',
        optionC: 'গ্যালিলিও',
        optionD: 'আর্কিমিডিস',
        correctOption: 'b',
        explanation: '১৬৮৭ সালে স্যার আইজ্যাক নিউটন তাঁর অমর গ্রন্থ ফিলোসফিয়া ন্যাচারালিস প্রিন্সিপিয়া ম্যাথামেটিকা-তে মহাকর্ষ সূত্র প্রকাশ করেন।',
      },
      {
        serialNumber: 7,
        questionText: 'রোধের এসআই একক কোনটি?',
        optionA: 'ওহম',
        optionB: 'ভোল্ট',
        optionC: 'ওয়াট',
        optionD: 'জুল',
        correctOption: 'a',
        explanation: 'বিজ্ঞানী জর্জ সাইমন ওহমের নামানুসারে পরিবাহীর রোধের এসআই একক ওহম (Ω)।',
      },
      {
        serialNumber: 8,
        questionText: 'অভিকর্ষজ ত্বরণ g এর আদর্শ মান কত?',
        optionA: '9.8 ms⁻²',
        optionB: '9.80665 ms⁻²',
        optionC: '9.83 ms⁻²',
        optionD: '9.78 ms⁻²',
        correctOption: 'b',
        explanation: '৪৫° অক্ষাংশে সমুদ্র সমতলে g এর প্রমাণ ও প্রমিত মান ৯.৮০৬৬৫ মি/সে² (সাধারণত ৯.৮ মি/সে² ধরা হয়)।',
      },
      {
        serialNumber: 9,
        questionText: 'নিচের কোনটি ভেক্টর রাশি?',
        optionA: 'ভর',
        optionB: 'দূরত্ব',
        optionC: 'বেগ',
        optionD: 'কাজ',
        correctOption: 'c',
        explanation: 'বেগের মান এবং নির্দিষ্ট দিক উভয়ই রয়েছে, তাই এটি ভেক্টর রাশি।',
      },
      {
        serialNumber: 10,
        questionText: 'কাজ করার সামর্থ্যকে কী বলে?',
        optionA: 'ক্ষমতা',
        optionB: 'শক্তি',
        optionC: 'বল',
        optionD: 'ত্বরণ',
        correctOption: 'b',
        explanation: 'কাজ করার সামর্থ্যকে শক্তি এবং কাজ করার হারকে ক্ষমতা বলে।',
      },
    ],
  },

  // [3] SSC 2020 - Accounting (হিসাববিজ্ঞান - কুমিল্লা বোর্ড) - Commerce
  {
    academicLevel: 'ssc',
    subjectName: 'SSC Accounting',
    boardName: 'কুমিল্লা বোর্ড',
    examYear: 2020,
    title: 'SSC 2020: হিসাববিজ্ঞান (কুমিল্লা বোর্ড)',
    durationMinutes: 30,
    totalMarks: 30,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ৩০ মিনিট।',
    stream: 'commerce',
    questions: [
      {
        serialNumber: 1,
        questionText: 'আধুনিক হিসাববিজ্ঞানের মূল সমীকরণ কোনটি?',
        optionA: 'A = L + E',
        optionB: 'A = L - E',
        optionC: 'L = A + E',
        optionD: 'E = A + L',
        correctOption: 'a',
        explanation: 'সম্পদ = দায় + মালিকানাস্বত্ব অর্থাৎ Assets (A) = Liabilities (L) + Equity (E)।',
      },
      {
        serialNumber: 2,
        questionText: 'কোনটি অনগদ লেনদেনের উদাহরণ?',
        optionA: 'পণ্য ক্রয়',
        optionB: 'আসবাবপত্রের অবচয়',
        optionC: 'বেতন প্রদান',
        optionD: 'ব্যাংক জমা',
        correctOption: 'b',
        explanation: 'স্থায়ী সম্পত্তির ব্যবহারজনিত ক্ষয় বা অবচয় (Depreciation) একটি অনগদ অভ্যন্তরীণ অনানুষ্ঠানিক লেনদেন।',
      },
      {
        serialNumber: 3,
        questionText: 'হিসাব চক্রের প্রথম ধাপ কোনটি?',
        optionA: 'জাবেদাভুক্তকরণ',
        optionB: 'লেনদেন শনাক্তকরণ',
        optionC: 'খতিয়ানভুক্তকরণ',
        optionD: 'রেওয়ামিল প্রস্তুতকরণ',
        correctOption: 'b',
        explanation: 'হিসাব চক্রের প্রথম ও প্রারম্ভিক ধাপ হলো সংঘটিত ঘটনাগুলো থেকে আর্থিক লেনদেন সঠিকভাবে শনাক্ত করা।',
      },
      {
        serialNumber: 4,
        questionText: 'লেনদেনের ডেবিট ও ক্রেডিট নির্ণয়ের সর্বজনীন পদ্ধতির নাম কী?',
        optionA: 'একতরফা দাখিলা পদ্ধতি',
        optionB: 'দুতরফা দাখিলা পদ্ধতি',
        optionC: 'নগদান পদ্ধতি',
        optionD: 'ব্যাংক সমন্বয় পদ্ধতি',
        correctOption: 'b',
        explanation: '১৪৯৪ সালে লুকা প্যাসিওলি উদ্ভাবিত বিজ্ঞানসম্মত দ্বৈতসত্ত্বা পদ্ধতিকে দুতরফা দাখিলা পদ্ধতি বলা হয়।',
      },
      {
        serialNumber: 5,
        questionText: 'রেওয়ামিল প্রস্তুতের মূল উদ্দেশ্য কী?',
        optionA: 'লাভ-ক্ষতি নির্ণয়',
        optionB: 'গাণিতিক নির্ভুলতা যাচাই',
        optionC: 'আর্থিক অবস্থা প্রকাশ',
        optionD: 'নগদ উদ্বৃত্ত জানা',
        correctOption: 'b',
        explanation: 'খতিয়ানের জেরগুলোর ডেবিট ও ক্রেডিট সমান হয়েছে কি না অর্থাৎ হিসাবের গাণিতিক শুদ্ধতা যাচাই করাই রেওয়ামিলের মূল লক্ষ্য।',
      },
      {
        serialNumber: 6,
        questionText: 'ব্যাংক হিসাব বিবরণী এবং নগদান বইয়ের ব্যাংক জেরের অমিলের কারণ লিপিবদ্ধ হয় কোন বিবরণীতে?',
        optionA: 'রেওয়ামিল',
        optionB: 'ব্যাংক সমন্বয় বিবরণী',
        optionC: 'আর্থিক বিবরণী',
        optionD: 'নগদ প্রবাহ বিবরণী',
        correctOption: 'b',
        explanation: 'ব্যাংক সমন্বয় বিবরণী (Bank Reconciliation Statement) এর মাধ্যমে দুটি জেরের অমিলের কারণ সমন্বয় করা হয়।',
      },
      {
        serialNumber: 7,
        questionText: 'নিচের কোনটি চলতি দায় (Current Liability)?',
        optionA: 'প্রদেয় হিসাব (পাওনাদার)',
        optionB: 'বন্ধকী ঋণ',
        optionC: 'মূলধন',
        optionD: 'যন্ত্রপাতি',
        correctOption: 'a',
        explanation: 'প্রদেয় হিসাব স্বল্পমেয়াদে (১ বছরের মধ্যে) পরিশোধযোগ্য দায়, তাই এটি চলতি দায়।',
      },
      {
        serialNumber: 8,
        questionText: 'পণ্য বিক্রয়লব্ধ অর্থ কোন জাতীয় আয়?',
        optionA: 'মূলধন জাতীয়',
        optionB: 'মুনাফা জাতীয়',
        optionC: 'বিলম্বিত মুনাফা জাতীয়',
        optionD: 'অনুপার্জিত আয়',
        correctOption: 'b',
        explanation: 'নিয়মিত ব্যবসায়িক পরিচালন কার্যক্রম থেকে যে আয় নিয়মিত অর্জিত হয় তা মুনাফা জাতীয় আয়।',
      },
      {
        serialNumber: 9,
        questionText: 'সম্পদ বৃদ্ধি পেলে কী হয়?',
        optionA: 'ডেবিট',
        optionB: 'ক্রেডিট',
        optionC: 'উদ্বৃত্ত বাড়ে না',
        optionD: 'শূন্য হয়',
        correctOption: 'a',
        explanation: 'দুতরফা দাখিলা পদ্ধতির নিয়ম অনুযায়ী সম্পদ বৃদ্ধি পেলে ডেবিট এবং হ্রাস পেলে ক্রেডিট হয়।',
      },
      {
        serialNumber: 10,
        questionText: 'ব্যবসায়ের নিট লাভ কোথায় স্থানান্তরিত হয়?',
        optionA: 'ক্রয় হিসাবে',
        optionB: 'নগদান হিসাবে',
        optionC: 'মালিকানাস্বত্ব বা মূলধন হিসাবে',
        optionD: 'ব্যাংক হিসাবে',
        correctOption: 'c',
        explanation: 'নিট মুনাফা মালিকানাস্বত্ব বৃদ্ধি করে, তাই তা মূলধন তহবিলের সাথে যোগ করা হয়।',
      },
    ],
  },

  // [4] SSC 2021 - Geography & Environment (ভূগোল ও পরিবেশ - রাজশাহী বোর্ড) - Humanities
  {
    academicLevel: 'ssc',
    subjectName: 'SSC Geography & Environment',
    boardName: 'রাজশাহী বোর্ড',
    examYear: 2021,
    title: 'SSC 2021: ভূগোল ও পরিবেশ (রাজশাহী বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'humanities',
    questions: [
      {
        serialNumber: 1,
        questionText: 'সৌরজগতের বৃহত্তম গ্রহ কোনটি?',
        optionA: 'বুধ',
        optionB: 'শনি',
        optionC: 'বৃহস্পতি',
        optionD: 'মঙ্গল',
        correctOption: 'c',
        explanation: 'সৌরজগতের সবচেয়ে বড় এবং ভারী গ্রহ হলো বৃহস্পতি (Jupiter)।',
      },
      {
        serialNumber: 2,
        questionText: 'পাকশী হার্ডিঞ্জ ব্রিজ কোন নদীর ওপর অবস্থিত?',
        optionA: 'পদ্মা',
        optionB: 'মেঘনা',
        optionC: 'যমুনা',
        optionD: 'কর্ণফুলী',
        correctOption: 'a',
        explanation: 'কুষ্টিয়া ও পাবনা জেলার সংযোগস্থলে পদ্মা নদীর ওপর ঐতিহাসিক হার্ডিঞ্জ ব্রিজ ও লালন শাহ সেতু অবস্থিত।',
      },
      {
        serialNumber: 3,
        questionText: 'বাংলাদেশের জলবায়ু প্রধানত কোন প্রকৃতির?',
        optionA: 'উষ্ণ নাতিশীতোষ্ণ',
        optionB: 'ক্রান্তীয় মৌসুমী জলবায়ু',
        optionC: 'ভূমধ্যসাগরীয়',
        optionD: 'মরুজ জলবায়ু',
        correctOption: 'b',
        explanation: 'কর্কটক্রান্তি রেখা বাংলাদেশের ওপর দিয়ে অতিক্রম করায় এবং মৌসুমী বায়ুর প্রভাবে এদেশের জলবায়ু ক্রান্তীয় মৌসুমী জলবায়ু নামে পরিচিত।',
      },
      {
        serialNumber: 4,
        questionText: 'গ্রিনহাউস গ্যাসের প্রধান উপাদান কোনটি?',
        optionA: 'কার্বন ডাই-অক্সাইড (CO₂)',
        optionB: 'অক্সিজেন',
        optionC: 'নাইট্রোজেন',
        optionD: 'হিলিয়াম',
        correctOption: 'a',
        explanation: 'বৈশ্বিক উষ্ণায়ন ও গ্রিনহাউস প্রভাব সৃষ্টির প্রধান গ্যাস হলো কার্বন ডাই-অক্সাইড (CO₂)।',
      },
      {
        serialNumber: 5,
        questionText: 'বাংলাদেশের একমাত্র প্রবাল দ্বীপ কোনটি?',
        optionA: 'সন্দ্বীপ',
        optionB: 'হাতিয়া',
        optionC: 'সেন্টমার্টিন',
        optionD: 'মহেশখালী',
        correctOption: 'c',
        explanation: 'বঙ্গোপসাগরের উত্তর-পূর্বাংশে অবস্থিত সেন্টমার্টিন বাংলাদেশের একমাত্র প্রবাল প্রাচীরযুক্ত দ্বীপ।',
      },
      {
        serialNumber: 6,
        questionText: 'অশ্মমণ্ডলের নিচে অবস্থিত গলিত শিলাস্তরকে কী বলা হয়?',
        optionA: 'কেন্দ্রমণ্ডল',
        optionB: 'গুরুমণ্ডল বা ম্যাগমা চেম্বার',
        optionC: 'ভূত্বক',
        optionD: 'বায়ুমণ্ডল',
        correctOption: 'b',
        explanation: 'অশ্মমণ্ডলের তলদেশে অত্যধিক তাপে গলিত শিলার সান্দ্র স্তরটিকে গুরুমণ্ডল বা অ্যাসথেনোস্ফিয়ার বলা হয়।',
      },
      {
        serialNumber: 7,
        questionText: 'কোন পর্বত ভঙ্গিল (Folded) পর্বতের উদাহরণ?',
        optionA: 'হিমালয় পর্বত',
        optionB: 'ব্ল্যাক ফরেস্ট',
        optionC: 'কিলিমাঞ্জারো',
        optionD: 'ফুজিয়ামা',
        correctOption: 'a',
        explanation: 'টেকটনিক প্লেটের পার্শ্বচাপের ফলে ভাঁজ পড়ে হিমালয়, আল্পস ও রকি ভঙ্গিল পর্বতের সৃষ্টি হয়েছে।',
      },
      {
        serialNumber: 8,
        questionText: 'পৃথিবীর আহ্নিক গতির কারণে কী সংঘটিত হয়?',
        optionA: 'দিন ও রাত',
        optionB: 'ঋতু পরিবর্তন',
        optionC: 'সূর্যগ্রহণ',
        optionD: 'বছর গণনা',
        correctOption: 'a',
        explanation: 'নিজ মেরুদণ্ডের ওপর পৃথিবীর ২৪ ঘণ্টার ঘূর্ণন বা আহ্নিক গতির কারণে দিন ও রাতের সৃষ্টি হয়।',
      },
      {
        serialNumber: 9,
        questionText: 'জোয়ার-ভাটার মূল কারণ কোনটি?',
        optionA: 'সূর্যের আকর্ষণ',
        optionB: 'চাঁদের আকর্ষণ ও কেন্দ্রাতিগ বল',
        optionC: 'বায়ুপ্রবাহ',
        optionD: 'পৃথিবীর তাপ বিকিরণ',
        correctOption: 'b',
        explanation: 'পৃথিবীর জলভাগের ওপর চাঁদের প্রত্যক্ষ মহাকর্ষীয় আকর্ষণ এবং পৃথিবীর ঘূর্ণনজনিত কেন্দ্রাতিগ বলের কারণে জোয়ার-ভাটা হয়।',
      },
      {
        serialNumber: 10,
        questionText: 'কর্কটক্রান্তি রেখার মান কত ডিগ্রি উত্তর অক্ষাংশ?',
        optionA: '২৩.৫° উত্তর',
        optionB: '৬৬.৫° উত্তর',
        optionC: '০° বিষুবরেখা',
        optionD: '৯০° উত্তর মেরু',
        correctOption: 'a',
        explanation: '২৩.৫° উত্তর অক্ষাংশ রেখাকে কর্কটক্রান্তি রেখা (Tropic of Cancer) বলা হয় যা বাংলাদেশের মধ্য দিয়ে গেছে।',
      },
    ],
  },

  // [5] SSC 2022 - Bangla 1st Paper (বাংলা ১ম পত্র - চট্টগ্রাম বোর্ড) - Common
  {
    academicLevel: 'ssc',
    subjectName: 'SSC Bangla 1st Paper',
    boardName: 'চট্টগ্রাম বোর্ড',
    examYear: 2022,
    title: 'SSC 2022: বাংলা ১ম পত্র (চট্টগ্রাম বোর্ড)',
    durationMinutes: 30,
    totalMarks: 30,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ৩০ মিনিট।',
    stream: 'common',
    questions: [
      {
        serialNumber: 1,
        questionText: '‘বইপড়া’ প্রবন্ধটি প্রমথ চৌধুরীর কোন গ্রন্থ থেকে নেওয়া হয়েছে?',
        optionA: 'বীরবলের হালখাতা',
        optionB: 'প্রবন্ধ সংগ্রহ',
        optionC: 'রায়তের কথা',
        optionD: 'চার-ইয়ারী কথা',
        correctOption: 'b',
        explanation: 'প্রমথ চৌধুরীর বিখ্যাত ‘বইপড়া’ প্রবন্ধটি তাঁর ‘প্রবন্ধ সংগ্রহ’ ১ম খণ্ড থেকে সংকলিত হয়েছে।',
      },
      {
        serialNumber: 2,
        questionText: '‘কপোতাক্ষ নদ’ কবিতাটি কোন জাতীয় রচনা?',
        optionA: 'মহাকাব্য',
        optionB: 'গীতিকবিতা',
        optionC: 'চতুর্দশপদী (সনেট)',
        optionD: 'ব্যঙ্গকাব্য',
        correctOption: 'c',
        explanation: 'মাইকেল মধুসূদন দত্তের ‘কপোতাক্ষ নদ’ একটি অমর স্মৃতিকাতরতামূলক চতুর্দশপদী কবিতা বা সনেট।',
      },
      {
        serialNumber: 3,
        questionText: '‘মানুষ মুহম্মদ (স.)’ প্রবন্ধে মহানবীর কোন গুণের ওপর বিশেষ গুরুত্ব দেওয়া হয়েছে?',
        optionA: 'অলৌকিক ক্ষমতা',
        optionB: 'মানবিক গুণাবলী ও ক্ষমাশীলতা',
        optionC: 'রণকৌশল',
        optionD: 'বাগ্মিতা',
        correctOption: 'b',
        explanation: 'মোহাম্মদ ওয়াজেদ আলী মহানবী (সা.)-এর ঐতিহাসিক সত্যনিষ্ঠ মানবিক রূপ ও অসীম ক্ষমাশীলতা উপস্থাপন করেছেন।',
      },
      {
        serialNumber: 4,
        questionText: '‘বঙ্গবাণী’ কবিতার রচয়িতা কে?',
        optionA: 'আব্দুল হাকিম',
        optionB: 'আলাওল',
        optionC: 'কাজী নজরুল ইসলাম',
        optionD: 'রবীন্দ্রনাথ ঠাকুর',
        correctOption: 'a',
        explanation: 'মধ্যযুগের প্রখ্যাত কবি আব্দুল হাকিম মাতৃভাষার প্রতি নিখাদ অনুরাগে তাঁর নূরনামা কাব্যের অন্তর্গত ‘বঙ্গবাণী’ কবিতাটি রচনা করেন।',
      },
      {
        serialNumber: 5,
        questionText: '‘তোমাকে পাওয়ার জন্যে, হে স্বাধীনতা’ কবিতায় স্বাধীনতাকে পাওয়ার জন্য কার কপাল ভাঙল?',
        optionA: 'সাকিনা বিবির',
        optionB: 'হরিদাসীর',
        optionC: 'রহিমা বেগমের',
        optionD: 'শহীদ জননীর',
        correctOption: 'a',
        explanation: 'কবি শামসুর রাহমানের পংক্তি: "সাকিনা বিবির কপাল ভাঙল, সিঁথির সিঁদুর মুছে গেল হরিদাসীর।"',
      },
      {
        serialNumber: 6,
        questionText: '‘একাত্তরের দিনগুলি’ স্মৃতিচারণমূলক রচনায় শহীদ রুমী কোন যুদ্ধে সক্রিয় অংশ নিয়েছিলেন?',
        optionA: 'মুক্তিবাহিনীর গেরিলা অপারেশন (ক্র্যাক প্লাটুন)',
        optionB: 'নৌ কমান্ডো অপারেশন',
        optionC: 'বিমান বাহিনীর যুদ্ধ',
        optionD: 'সীমান্ত সম্মুখযুদ্ধ',
        correctOption: 'a',
        explanation: 'জাহানারা ইমামের জ্যেষ্ঠ পুত্র বীর মুক্তিযোদ্ধা রুমী ঢাকায় ক্র্যাক প্লাটুনের দুঃসাহসী গেরিলা যুদ্ধে অংশ নিয়েছিলেন।',
      },
      {
        serialNumber: 7,
        questionText: 'বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস কোনটি?',
        optionA: 'আলালের ঘরের দুলাল',
        optionB: 'দুর্গেশনন্দিনী',
        optionC: 'কপালকুণ্ডলা',
        optionD: 'পদ্মরাগ',
        correctOption: 'b',
        explanation: '১৮৬৫ সালে প্রকাশিত বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের ‘দুর্গেশনন্দিনী’ বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস।',
      },
      {
        serialNumber: 8,
        questionText: 'জীবনানন্দ দাশকে মূলত কোন প্রকৃতির কবি বলা হয়?',
        optionA: 'বিদ্রোহী কবি',
        optionB: 'রূপসী বাংলার বা তিমিরহননের কবি',
        optionC: 'পল্লীকবি',
        optionD: 'স্বভাব কবি',
        correctOption: 'b',
        explanation: 'বাংলার অতুলনীয় শ্যামল সৌন্দর্য ও নির্জনতার নিখুঁত রূপায়ণের জন্য জীবনানন্দ দাশ রূপসী বাংলার কবি হিসেবে খ্যাত।',
      },
      {
        serialNumber: 9,
        questionText: '‘শুভা’ গল্পে শুভার প্রকৃত নাম কী ছিল?',
        optionA: 'সুভাষিণী',
        optionB: 'সুহাসিনী',
        optionC: 'সুকেশী',
        optionD: 'সুমতি',
        correctOption: 'a',
        explanation: 'রবীন্দ্রনাথ ঠাকুরের ‘শুভা’ গল্পের বোবা মেয়েটির আনুষ্ঠানিক নাম রাখা হয়েছিল সুভাষিণী।',
      },
      {
        serialNumber: 10,
        questionText: '‘আম-আঁটির ভেঁপু’ শীর্ষাংশটি বিভূতিভূষণ বন্দ্যোপাধ্যায়ের কোন বিখ্যাত উপন্যাসের অংশ?',
        optionA: 'আরণ্যক',
        optionB: 'পথের পাঁচালী',
        optionC: 'অপরাজিত',
        optionD: 'ইছামতী',
        correctOption: 'b',
        explanation: 'অপু ও দুর্গার শৈশবস্মৃতিবিজড়িত ‘আম-আঁটির ভেঁপু’ অংশটি কালজয়ী ‘পথের পাঁচালী’ উপন্যাস থেকে গৃহীত।',
      },
    ],
  },

  // [6] SSC 2023 - Chemistry (রসায়ন - ঢাকা বোর্ড) - Science
  {
    academicLevel: 'ssc',
    subjectName: 'SSC Chemistry',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2023,
    title: 'SSC 2023: রসায়ন (ঢাকা বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'পানির অণুতে বন্ধন কোণের মান কত ডিগ্রি?',
        optionA: '১০৪.৫°',
        optionB: '১০৯.৫°',
        optionC: '১২০°',
        optionD: '১৮০°',
        correctOption: 'a',
        explanation: 'অক্সিজেনের দুটি মুক্তজোড় ইলেকট্রনের বিকর্ষণের কারণে পানির (H₂O) বন্ধন কোণ হ্রাস পেয়ে ১০৪.৫° হয়।',
      },
      {
        serialNumber: 2,
        questionText: 'পর্যায় সারণীর কোন গ্রুপের মৌলসমূহকে ক্ষার ধাতু বলা হয়?',
        optionA: 'গ্রুপ ১',
        optionB: 'গ্রুপ ২',
        optionC: 'গ্রুপ ১৭',
        optionD: 'গ্রুপ ১৮',
        correctOption: 'a',
        explanation: 'গ্রুপ ১ এর মৌলগুলো (Li, Na, K ইত্যাদি) পানির সাথে বিক্রিয়া করে তীব্র ক্ষার উৎপন্ন করে বিধায় এদের ক্ষার ধাতু বলে।',
      },
      {
        serialNumber: 3,
        questionText: 'অ্যাভোগ্যাড্রো সংখ্যার মান কত?',
        optionA: '6.023 × 10²³',
        optionB: '6.023 × 10⁻²³',
        optionC: '3.0 × 10⁸',
        optionD: '1.6 × 10⁻¹⁹',
        correctOption: 'a',
        explanation: 'যেকোনো পদার্থের ১ মোলে উপস্থিত কণার সংখ্যাকে অ্যাভোগ্যাড্রো সংখ্যা বলে, যার মান ৬.০২৩ × ১০²³।',
      },
      {
        serialNumber: 4,
        questionText: 'ভিনেগারে অ্যাসিটিক অ্যাসিডের শতকরা পরিমাণ কত থাকে?',
        optionA: '৪% - ১০%',
        optionB: '১৫% - ২০%',
        optionC: '৫০%',
        optionD: '১০০%',
        correctOption: 'a',
        explanation: 'অ্যাসিটিক অ্যাসিডের ৪-১০% জলীয় দ্রবণকে ভিনেগার বা সিরকা বলা হয়।',
      },
      {
        serialNumber: 5,
        questionText: 'মরিচার সঠিক রাসায়নিক সংকেত কোনটি?',
        optionA: 'Fe₂O₃ · nH₂O',
        optionB: 'Fe₃O₄',
        optionC: 'FeO',
        optionD: 'Fe(OH)₂',
        correctOption: 'a',
        explanation: 'লোহার আর্দ্র ফেরিক অক্সাইডকে মরিচা বলে, যার রাসায়নিক সংকেত Fe₂O₃ · nH₂O।',
      },
      {
        serialNumber: 6,
        questionText: 'নিষ্ক্রিয় গ্যাস সমূহের সর্বশেষ কক্ষপথে সাধারণত কয়টি ইলেকট্রন থাকে?',
        optionA: '২টি',
        optionB: '৮টি',
        optionC: '১৮টি',
        optionD: '৩২টি',
        correctOption: 'b',
        explanation: 'হিলিয়াম ব্যতিত (যার হিলিয়াম দ্বিত্ব ২) অন্যান্য সকল নিষ্ক্রিয় গ্যাসের সর্ববহিঃস্থ স্তরে স্থিতিশীল ৮টি ইলেকট্রন থাকে।',
      },
      {
        serialNumber: 7,
        questionText: 'কোন অ্যাসিডকে রাসায়নিকের রাজা (King of Chemicals) বলা হয়?',
        optionA: 'HCl',
        optionB: 'H₂SO₄',
        optionC: 'HNO₃',
        optionD: 'CH₃COOH',
        correctOption: 'b',
        explanation: 'শিল্পক্ষেত্রে ব্যাপক ব্যবহার ও চাহিদার কারণে সালফিউরিক অ্যাসিডকে (H₂SO₄) রসায়নের রাজা বলা হয়।',
      },
      {
        serialNumber: 8,
        questionText: 'অ্যালকেনের সাধারণ সংকেত কোনটি?',
        optionA: 'CnH2n+2',
        optionB: 'CnH2n',
        optionC: 'CnH2n-2',
        optionD: 'CnH2n+1OH',
        correctOption: 'a',
        explanation: 'সম্পৃক্ত হাইড্রোকার্বন বা অ্যালকেনের সাধারণ আণবিক সংকেত CnH2n+2 (যেমন মিথেন CH₄)।',
      },
      {
        serialNumber: 9,
        questionText: 'কার্বনের সবচেয়ে কঠিন প্রাকৃতিক রূপভেদ কোনটি?',
        optionA: 'গ্রাফাইট',
        optionB: 'হীরক (হীরা)',
        optionC: 'কয়লা',
        optionD: 'ফুলারিন',
        correctOption: 'b',
        explanation: 'ত্রিমাত্রিক টেট্রাহেড্রাল সমযোজী জালক গঠনের কারণে হীরা প্রকৃতির সবচেয়ে শক্ত কঠিন পদার্থ।',
      },
      {
        serialNumber: 10,
        questionText: 'তুঁতের (ব্লু ভিট্রিওল) কেলাস পানির সংখ্যা কয়টি?',
        optionA: '২',
        optionB: '৫',
        optionC: '৭',
        optionD: '১০',
        correctOption: 'b',
        explanation: 'তুঁতের রাসায়নিক সংকেত CuSO₄ · 5H₂O, অর্থাৎ এতে ৫ অণু কেলাস পানি রয়েছে।',
      },
    ],
  },

  // [7] SSC 2024 - Biology (জীববিজ্ঞান - সকল বোর্ড) - Science
  {
    academicLevel: 'ssc',
    subjectName: 'SSC Biology',
    boardName: 'সমন্বিত বোর্ড (সকল)',
    examYear: 2024,
    title: 'SSC 2024: জীববিজ্ঞান (সকল বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'কোষের শক্তিঘর (Powerhouse of the cell) কাকে বলা হয়?',
        optionA: 'মাইটোকন্ড্রিয়া',
        optionB: 'রাইবোসোম',
        optionC: 'গলগি বডি',
        optionD: 'লাইসোজোম',
        correctOption: 'a',
        explanation: 'শ্বসনের ক্রেবস চক্র এবং অক্সিডেটিভ ফসফোরাইলেশনের মাধ্যমে এটিপি তৈরি হওয়ায় মাইটোকন্ড্রিয়াকে কোষের শক্তিঘর বলে।',
      },
      {
        serialNumber: 2,
        questionText: 'সালোকসংশ্লেষণ প্রক্রিয়ায় উপজাত (Byproduct) হিসেবে কোন গ্যাসটি নির্গত হয়?',
        optionA: 'কার্বন ডাই-অক্সাইড',
        optionB: 'অক্সিজেন (O₂)',
        optionC: 'নাইট্রোজেন',
        optionD: 'হাইড্রোজেন',
        correctOption: 'b',
        explanation: 'পানির আলোক বিভাজনের (ফটোলাইসিস) ফলে উপজাত হিসেবে প্রাণিকুলের জীবনধারণের জন্য প্রয়োজনীয় O₂ গ্যাস মুক্ত হয়।',
      },
      {
        serialNumber: 3,
        questionText: 'রক্তের সার্বজনীন গ্রহীতা (Universal Recipient) কোন গ্রুপের রক্ত?',
        optionA: 'A',
        optionB: 'B',
        optionC: 'AB',
        optionD: 'O',
        correctOption: 'c',
        explanation: 'AB গ্রুপের রক্তে কোনো অ্যান্টিবডি (Anti-A বা Anti-B) না থাকায় এটি যেকোনো গ্রুপের রক্ত গ্রহণ করতে পারে।',
      },
      {
        serialNumber: 4,
        questionText: 'মানবদেহের রেচনের প্রধান অঙ্গ কোনটি?',
        optionA: 'যকৃৎ',
        optionB: 'ফুসফুস',
        optionC: 'বৃক্ক (Kidney)',
        optionD: 'ত্বক',
        correctOption: 'c',
        explanation: 'বৃক্ক বা কিডনি রক্তের নাইট্রোজেনঘটিত ক্ষতিকর বর্জ্য (ইউরিয়া, ইউরিক এসিড) মূত্র আকারে নিষ্কাশনের প্রধান অঙ্গ।',
      },
      {
        serialNumber: 5,
        questionText: 'কোন ভিটামিনের অভাবে শিশুদের রিকেটস রোগ হয়?',
        optionA: 'ভিটামিন এ',
        optionB: 'ভিটামিন সি',
        optionC: 'ভিটামিন ডি',
        optionD: 'ভিটামিন কে',
        correctOption: 'c',
        explanation: 'ক্যালসিয়াম শোষণে সহায়ক ভিটামিন ডি-এর ঘাটতি হলে হাড় নরম ও বাঁকা হয়ে রিকেটস রোগ দেখা দেয়।',
      },
      {
        serialNumber: 6,
        questionText: 'ডিএনএ (DNA) এর দ্বি-সূত্রক মডেলের আবিষ্কারক কারা?',
        optionA: 'ওয়াটসন ও ক্রিক',
        optionB: 'রবার্ট হুক',
        optionC: 'গ্রেগর জোহান মেন্ডেল',
        optionD: 'ডারউইন',
        correctOption: 'a',
        explanation: '১৯৫৩ সালে জেমস ওয়াটসন ও ফ্রান্সিস ক্রিক বিখ্যাত ডাবল হেলিক্স ডিএনএ মডেলের প্রস্তাবনা দিয়ে নোবেল পান।',
      },
      {
        serialNumber: 7,
        questionText: 'মানবদেহে ক্রোমোজোমের মোট সংখ্যা কয়টি?',
        optionA: '২৩টি',
        optionB: '৪৬টি (২৩ জোড়া)',
        optionC: '৪৪টি',
        optionD: '৪৮টি',
        correctOption: 'b',
        explanation: 'মানুষের দেহকোষে মোট ৪৬টি বা ২৩ জোড়া ক্রোমোজোম বিদ্যমান (২২ জোড়া অটোসোম ও ১ জোড়া সেক্স ক্রোমোজোম)।',
      },
      {
        serialNumber: 8,
        questionText: 'উদ্ভিদে পাতায় তৈরি খাদ্য কিসের মাধ্যমে সারা দেহে পরিবাহিত হয়?',
        optionA: 'জাইলেম',
        optionB: 'ফ্লোয়েম',
        optionC: 'ক্যাম্বিয়াম',
        optionD: 'মূলরোম',
        correctOption: 'b',
        explanation: 'জাইলেম পানি ও খনিজ লবণ পরিবহন করে এবং ফ্লোয়েম টিস্যু পাতায় প্রস্তুতকৃত খাদ্য দেহের সকল অংশে পৌঁছে দেয়।',
      },
      {
        serialNumber: 9,
        questionText: 'পিত্তরস (Bile) কোথায় উৎপন্ন হয়?',
        optionA: 'পাকস্থলী',
        optionB: 'যকৃৎ (Liver)',
        optionC: 'অগ্ন্যাশয়',
        optionD: 'পিত্তথলি',
        correctOption: 'b',
        explanation: 'যকৃতে পিত্তরস তৈরি হয় এবং তা পিত্তথলিতে (Gallbladder) সাময়িকভাবে জমা থাকে।',
      },
      {
        serialNumber: 10,
        questionText: 'ব্যাকটেরিয়া কোন রাজ্যের অন্তর্গত জীব?',
        optionA: 'মনেরা (Monera)',
        optionB: 'প্রোটিস্টা',
        optionC: 'ফাঞ্জাই',
        optionD: 'প্ল্যান্টি',
        correctOption: 'a',
        explanation: 'হুইটেকারের পাঁচ জগৎ শ্রেণিবিন্যাসে সুনির্দিষ্ট নিউক্লিয়াসবিহীন আদিকোষী এককোষী জীবদের মনেরা রাজ্যে রাখা হয়েছে।',
      },
    ],
  },

  // [8] SSC 2025 - Information and Communication Technology (আইসিটি - ঢাকা বোর্ড) - Common
  {
    academicLevel: 'ssc',
    subjectName: 'SSC Information and Communication Technology',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2025,
    title: 'SSC 2025: তথ্য ও যোগাযোগ প্রযুক্তি (ঢাকা বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'common',
    questions: [
      {
        serialNumber: 1,
        questionText: 'কম্পিউটার ভাইরাসের পূর্ণরূপ কোনটি?',
        optionA: 'Vital Information Resources Under Siege',
        optionB: 'Very Important Record User System',
        optionC: 'Visual Information Resource Unit Software',
        optionD: 'Virtual Internet Remote User System',
        correctOption: 'a',
        explanation: '১৯৮৩ সালে বিজ্ঞানী ফ্রেড কোহেন VIRUS শব্দটির পূর্ণরূপ দেন Vital Information Resources Under Siege।',
      },
      {
        serialNumber: 2,
        questionText: 'নিচের কোনটি ওপেন সোর্স অপারেটিং সিস্টেম?',
        optionA: 'উইন্ডোজ ১০',
        optionB: 'লিনাক্স (Linux)',
        optionC: 'ম্যাক ওএস',
        optionD: 'আইওএস',
        correctOption: 'b',
        explanation: 'লিনাক্স একটি জনপ্রিয় উন্মুক্ত ও ফ্রি ওপেন সোর্স (Open Source) অপারেটিং সিস্টেম।',
      },
      {
        serialNumber: 3,
        questionText: 'স্প্রেডশিট সফটওয়্যারের প্রধান কাজ কোনটি?',
        optionA: 'ছবি সম্পাদনা',
        optionB: 'হিসাব-নিকাশ ও বিশ্লেষণ',
        optionC: 'অ্যানিমেশন তৈরি',
        optionD: 'ওয়েব ব্রাউজিং',
        correctOption: 'b',
        explanation: 'এমএস এক্সেল বা স্প্রেডশিট সফটওয়্যার বড় বড় গাণিতিক হিসাব ও আর্থিক উপাত্ত বিশ্লেষণের জন্য ব্যবহৃত হয়।',
      },
      {
        serialNumber: 4,
        questionText: 'ই-কমার্স (E-commerce) বলতে কী বোঝায়?',
        optionA: 'ইলেকট্রনিক ডাকব্যবস্থা',
        optionB: 'ইন্টারনেটের মাধ্যমে ব্যবসা-বাণিজ্য ও কেনাবেচা',
        optionC: 'অনলাইন ক্লাস করা',
        optionD: 'ইলেকট্রনিক ভোটিং',
        correctOption: 'b',
        explanation: 'ইন্টারনেট ও ইলেকট্রনিক মাধ্যম ব্যবহার করে পণ্য ক্রয়-বিক্রয় ও আর্থিক লেনদেনকে ই-কমার্স বলে।',
      },
      {
        serialNumber: 5,
        questionText: 'এইচটিএমএল (HTML) এর পূর্ণরূপ কোনটি?',
        optionA: 'Hyper Text Markup Language',
        optionB: 'High Tech Modern Language',
        optionC: 'Hyperlink Transfer Machine Level',
        optionD: 'Home Tool Media Link',
        correctOption: 'a',
        explanation: 'ওয়েব পেজের কাঠামো নির্মাণের জন্য ব্যবহৃত ভাষার নাম Hyper Text Markup Language (HTML)।',
      },
      {
        serialNumber: 6,
        questionText: 'ডেটাবেজের ফিল্ডগুলোর সমষ্টিকে কী বলা হয়?',
        optionA: 'রেকর্ড (Record)',
        optionB: 'টেবিল',
        optionC: 'কোয়ারি',
        optionD: 'ফাইল',
        correctOption: 'a',
        explanation: 'পরস্পর সম্পর্কযুক্ত কতগুলো ফিল্ড নিয়ে একটি পূর্ণাঙ্গ রেকর্ড গঠিত হয়।',
      },
      {
        serialNumber: 7,
        questionText: 'কম্পিউটারের প্রধান স্মৃতি (Primary Memory) কোনটি?',
        optionA: 'হার্ডডিস্ক',
        optionB: 'পেনড্রাইভ',
        optionC: 'র‍্যাম (RAM)',
        optionD: 'সিডি-রম',
        correctOption: 'c',
        explanation: 'র‍্যান্ডম অ্যাক্সেস মেমোরি বা র‍্যাম (RAM) প্রসেসরের সরাসরি সংযোগযুক্ত প্রাথমিক প্রধান স্মৃতি।',
      },
      {
        serialNumber: 8,
        questionText: 'কোন পাসওয়ার্ডটি তুলনামূলকভাবে সবচেয়ে বেশি শক্তিশালী ও নিরাপদ?',
        optionA: '12345678',
        optionB: 'bangladesh',
        optionC: 'P@ssw0rd#2025',
        optionD: 'abcd1234',
        correctOption: 'c',
        explanation: 'বড় ও ছোট হাতের অক্ষর, সংখ্যা এবং বিশেষ প্রতীকের মিশ্রণে গঠিত পাসওয়ার্ড সাইবার আক্রমণ থেকে সবচেয়ে নিরাপদ।',
      },
      {
        serialNumber: 9,
        questionText: 'স্মার্ট বাংলাদেশের কয়টি মূল স্তম্ভ রয়েছে?',
        optionA: '২টি',
        optionB: '৩টি',
        optionC: '৪টি',
        optionD: '৫টি',
        correctOption: 'c',
        explanation: 'স্মার্ট বাংলাদেশের ৪টি ভিত্তি: স্মার্ট সিটিজেন, স্মার্ট সোসাইটি, স্মার্ট ইকোনমি এবং স্মার্ট গভর্নমেন্ট।',
      },
      {
        serialNumber: 10,
        questionText: 'ই-লার্নিং (e-Learning) এর পূর্ণ অর্থ কী?',
        optionA: 'Easy Learning',
        optionB: 'Electronic Learning',
        optionC: 'Efficient Learning',
        optionD: 'Everyday Learning',
        correctOption: 'b',
        explanation: 'ইন্টারনেট ও ইলেকট্রনিক মাধ্যম ব্যবহার করে পাঠদান ও শিক্ষার প্রক্রিয়াকে ইলেকট্রনিক লার্নিং (e-Learning) বলে।',
      },
    ],
  },

  // =========================================================================
  // --- HSC BOARD QUESTIONS (2018 - 2025) ---
  // =========================================================================

  // [9] HSC 2018 - Physics 1st Paper (পদার্থবিজ্ঞান ১ম পত্র - ঢাকা বোর্ড) - Science
  {
    academicLevel: 'hsc',
    subjectName: 'Physics 1st Paper',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2018,
    title: 'HSC 2018: পদার্থবিজ্ঞান ১ম পত্র (ঢাকা বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'দুটি ভেক্টর A ও B পরস্পর সমান্তরাল হলে তাদের ক্রস গুণফল কত হবে?',
        optionA: '০ (শূন্য)',
        optionB: '|A||B|',
        optionC: '১',
        optionD: '-১',
        correctOption: 'a',
        explanation: 'সমান্তরাল ভেক্টরের অন্তর্ভুক্ত কোণ θ = 0° বা 180°। ফলে sin(0°) = 0 হওয়ার কারণে A × B = 0 হয়।',
      },
      {
        serialNumber: 2,
        questionText: 'পৃথিবীপৃষ্ঠ হতে কোনো বস্তুর মুক্তিবেগের (Escape Velocity) মান কত?',
        optionA: '9.8 km/s',
        optionB: '11.2 km/s',
        optionC: '7.9 km/s',
        optionD: '11.2 m/s',
        correctOption: 'b',
        explanation: 'মুক্তিবেগ Ve = √(2gR) ≈ 11.2 কিমি/সেকেন্ড। এই বেগে কোনো বস্তু নিক্ষেপ করলে তা আর পৃথিবীতে ফিরে আসে না।',
      },
      {
        serialNumber: 3,
        questionText: 'সরল ছন্দিত স্পন্দনরত কণার সাম্যাবস্থানে কোনটির মান সর্বোচ্চ হয়?',
        optionA: 'গতিশক্তি',
        optionB: 'বিভব শক্তি',
        optionC: 'ত্বরণ',
        optionD: 'সরণ',
        correctOption: 'a',
        explanation: 'সাম্যাবস্থানে কণার বেগ v সর্বোচ্চ হওয়ায় গতিশক্তি (Ek = 1/2 mv²) সর্বোচ্চ এবং বিভব শক্তি শূন্য হয়।',
      },
      {
        serialNumber: 4,
        questionText: 'আদর্শ গ্যাসের অণুগুলোর গড় গতিশক্তি কিসের সমানুপাতিক?',
        optionA: 'পরম তাপমাত্রা (T)',
        optionB: 'চাপ (P)',
        optionC: 'আয়তন (V)',
        optionD: 'ঘনত্ব (ρ)',
        correctOption: 'a',
        explanation: 'আদর্শ গ্যাস সমীকরণ মতে ১ মোল গ্যাসের গড় গতিশক্তি E = (3/2) RT, অর্থাৎ গতিশক্তি পরম তাপমাত্রা T এর সমানুপাতিক।',
      },
      {
        serialNumber: 5,
        questionText: 'সান্দ্রতা গুণাঙ্কের (Coefficient of Viscosity) এসআই একক কোনটি?',
        optionA: 'N s m⁻² বা Pa·s',
        optionB: 'N m⁻²',
        optionC: 'kg m⁻¹',
        optionD: 'J s',
        correctOption: 'a',
        explanation: 'সান্দ্রতা গুণাঙ্ক η এর এসআই একক প্যাসকেল-সেকেন্ড (Pa·s) বা N·s·m⁻²।',
      },
      {
        serialNumber: 6,
        questionText: 'কোন তাপমাত্রায় সেলসিয়াস ও ফারেনহাইট স্কেলে একই পাঠ প্রদর্শন করে?',
        optionA: '-40°',
        optionB: '0°',
        optionC: '40°',
        optionD: '100°',
        correctOption: 'a',
        explanation: 'C/5 = (F - 32)/9 সমীকরণে C = F = x বসালে সমাধান পাওয়া যায় x = -40°।',
      },
      {
        serialNumber: 7,
        questionText: 'পৈঁশর অনুপাতের (Poisson\'s Ratio) তাত্ত্বিক সীমার মান কত?',
        optionA: '-1 থেকে 0.5',
        optionB: '0 থেকে 0.5',
        optionC: '-0.5 থেকে 1',
        optionD: '0 থেকে 1',
        correctOption: 'a',
        explanation: 'পার্শ্ব বিকৃতি ও দৈর্ঘ্য বিকৃতির অনুপাতকে পৈঁশর অনুপাত বলে, যার তাত্ত্বিক সীমা -১ < σ < ০.৫ এবং ব্যবহারিক সীমা ০ < σ < ০.৫।',
      },
      {
        serialNumber: 8,
        questionText: 'কৌণিক ভরবেগের মাত্রা সমীকরণ কোনটি?',
        optionA: '[ML²T⁻¹]',
        optionB: '[MLT⁻¹]',
        optionC: '[ML²T⁻²]',
        optionD: '[MLT⁻²]',
        correctOption: 'a',
        explanation: 'কৌণিক ভরবেগ L = r × p = r × (mv); মাত্রা = L × [M][LT⁻¹] = [ML²T⁻¹]।',
      },
      {
        serialNumber: 9,
        questionText: 'প্রাসের গতিপথের সর্বোচ্চ উচ্চতায় উলম্ব বেগের মান কত?',
        optionA: '০ (শূন্য)',
        optionB: 'v₀ cos θ',
        optionC: 'v₀ sin θ',
        optionD: 'v₀',
        correctOption: 'a',
        explanation: 'সর্বোচ্চ উচ্চতায় অভিকর্ষের বিপরীতে বস্তুর উলম্ব বেগ Vy = 0 হয়, কেবল আনুভূমিক বেগ Vx অপরিবর্তিত থাকে।',
      },
      {
        serialNumber: 10,
        questionText: 'রুদ্ধতাপীয় প্রক্রিয়ায় কোন ভৌত রাশি স্থির থাকে?',
        optionA: 'তাপমাত্রা',
        optionB: 'চাপ',
        optionC: 'আয়তন',
        optionD: 'মোট তাপ (এন্ট্রপি)',
        correctOption: 'd',
        explanation: 'রুদ্ধতাপীয় (Adiabatic) প্রক্রিয়ায় সিস্টেম ও পরিবেশের মধ্যে তাপের কোনো আদান-প্রদান ঘটে না (dQ = 0)।',
      },
    ],
  },

  // [10] HSC 2019 - Chemistry 1st Paper (রসায়ন ১ম পত্র - ঢাকা বোর্ড) - Science
  {
    academicLevel: 'hsc',
    subjectName: 'Chemistry 1st Paper',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2019,
    title: 'HSC 2019: রসায়ন ১ম পত্র (ঢাকা বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'একটি অরবিটালে বিপরীত স্পিনের সর্বোচ্চ কয়টি ইলেকট্রন থাকতে পারে?',
        optionA: '১টি',
        optionB: '২টি',
        optionC: '৬টি',
        optionD: '১০টি',
        correctOption: 'b',
        explanation: 'পাউলির বর্জন নীতি অনুযায়ী একটি পরমাণুর যেকোনো দুটি ইলেকট্রনের চারটি কোয়ান্টাম সংখ্যার মান কখনোই এক হতে পারে না। তাই ১টি অরবিটালে সর্বোচ্চ ২টি বিপরীতমুখী স্পিনের ইলেকট্রন থাকতে পারে।',
      },
      {
        serialNumber: 2,
        questionText: 'হাইড্রোজেন পরমাণুর বামার (Balmer) সিরিজের বর্ণালী কোন অঞ্চলে দেখা যায়?',
        optionA: 'অতিবেগুনি অঞ্চল (UV)',
        optionB: 'দৃশ্যমান অঞ্চল (Visible)',
        optionC: 'অবলোহিত অঞ্চল (IR)',
        optionD: 'এক্স-রে অঞ্চল',
        correctOption: 'b',
        explanation: 'উচ্চ শক্তিস্তর থেকে ২য় শক্তিস্তরে (n₁ = 2) ইলেকট্রন স্থানান্তরিত হলে বামার সিরিজ তৈরি হয়, যা দৃশ্যমান আলো হিসেবে দেখা যায়।',
      },
      {
        serialNumber: 3,
        questionText: 'পানির আয়নিক গুণফলের (Kw) মান ২৫° সেলসিয়াস তাপমাত্রায় কত?',
        optionA: '1.0 × 10⁻¹⁴',
        optionB: '1.0 × 10⁻⁷',
        optionC: '1.0 × 10⁻¹⁰',
        optionD: '7.0',
        correctOption: 'a',
        explanation: '২৫°C এ বিশুদ্ধ পানির Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ mol² L⁻²।',
      },
      {
        serialNumber: 4,
        questionText: 'কোন যৌগের কেন্দ্রীয় পরমাণুতে sp³d সংকরণ (Hybridization) ঘটে?',
        optionA: 'CH₄',
        optionB: 'PCl₅',
        optionC: 'SF₆',
        optionD: 'BeCl₂',
        correctOption: 'b',
        explanation: 'ফসফরাস পেন্টাক্লোরাইডে (PCl₅) কেন্দ্রীয় P পরমাণুর চারপাশের পাঁচটি সমযোজী বন্ধনের জন্য sp³d সংকরণ ঘটে।',
      },
      {
        serialNumber: 5,
        questionText: 'লা-শাতেলিয়ার নীতি কোন ধরনের সাম্যাবস্থার ওপর প্রযোজ্য?',
        optionA: 'একমুখী বিক্রিয়ায়',
        optionB: 'উভমুখী বিক্রিয়ায়',
        optionC: 'কেবল গ্যাসীয় বিক্রিয়ায়',
        optionD: 'কেবল তাপোৎপাদী বিক্রিয়ায়',
        correctOption: 'b',
        explanation: 'লা-শাতেলিয়ার নীতি মূলত গতিশীল রাসায়নিক উভমুখী সাম্যাবস্থায় নিয়ামকের প্রভাব ব্যাখ্যা করে।',
      },
      {
        serialNumber: 6,
        questionText: 'বাফার দ্রবণের পিএইচ (pH) গণনায় কোন সমীকরণ ব্যবহৃত হয়?',
        optionA: 'হেনডারসন-হ্যাসেলবাল্ক সমীকরণ',
        optionB: 'ভ্যান্ট হফ সমীকরণ',
        optionC: 'নার্নস্ট সমীকরণ',
        optionD: 'আর্হেনিয়াস সমীকরণ',
        correctOption: 'a',
        explanation: 'অম্লীয় বা ক্ষারীয় বাফার দ্রবণের pH নির্ণয়ে Henderson-Hasselbalch সমীকরণ (pH = pKa + log([লবণ]/[অম্ল])) ব্যবহৃত হয়।',
      },
      {
        serialNumber: 7,
        questionText: 'সবচেয়ে বেশি তড়িৎ-ঋণাত্মক (Electronegative) মৌল কোনটি?',
        optionA: 'ক্লোরিন',
        optionB: 'ফ্লোরিন (F)',
        optionC: 'অক্সিজেন',
        optionD: 'নাইট্রোজেন',
        correctOption: 'b',
        explanation: 'পাউলিং স্কেলে ফ্লোরিনের তড়িৎ-ঋণাত্মকতার মান সর্বোচ্চ ৪.০।',
      },
      {
        serialNumber: 8,
        questionText: 'ল্যাবরেটরিতে পরিবেশবান্ধব পরিচ্ছন্নতাকারী মিশ্রণ কোনটি?',
        optionA: 'ঘন H₂SO₄',
        optionB: 'ক্রোমিক অ্যাসিড মিশ্রণ',
        optionC: 'ডিটর্জেন্ট দ্রবণ',
        optionD: 'অ্যালকোহল',
        correctOption: 'b',
        explanation: 'পটাশিয়াম ডাইক্রোমেট ও ঘন সালফিউরিক অ্যাসিডের মিশ্রণ (K₂Cr₂O₇ + H₂SO₄) কাচপাত্রের গ্রিজ ও ময়লা জারণে অত্যন্ত কার্যকর ক্রোমিক মিশ্রণ।',
      },
      {
        serialNumber: 9,
        questionText: 'শিখা পরীক্ষায় ক্যালসিয়াম আয়ন (Ca²⁺) বুনসেন শিখায় কী বর্ণ প্রদর্শন করে?',
        optionA: 'ইটের মতো লাল (Brick Red)',
        optionB: 'সোনালী হলুদ',
        optionC: 'হালকা বেগুনি',
        optionD: 'উজ্জ্বল সবুজ',
        correctOption: 'a',
        explanation: 'ক্যালসিয়াম আয়ন শিখা পরীক্ষায় বৈশিষ্টপূর্ণ ইটের মতো লাল শিখা প্রদর্শন করে।',
      },
      {
        serialNumber: 10,
        questionText: 'মানুষের রক্তের স্বাভাবিক pH এর মান কত?',
        optionA: '6.4',
        optionB: '7.4 (7.35 - 7.45)',
        optionC: '8.4',
        optionD: '7.0',
        correctOption: 'b',
        explanation: 'মানুষের রক্তের pH অত্যন্ত সুনির্দিষ্ট এবং এর সামান্য ক্ষারীয় মাত্রা গড়ে ৭.৪।',
      },
    ],
  },

  // [11] HSC 2020 - Information and Communication Technology (আইসিটি - সকল বোর্ড) - Common
  {
    academicLevel: 'hsc',
    subjectName: 'Information and Communication Technology (ICT)',
    boardName: 'সমন্বিত বোর্ড (সকল)',
    examYear: 2020,
    title: 'HSC 2020: তথ্য ও যোগাযোগ প্রযুক্তি (সকল বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'common',
    questions: [
      {
        serialNumber: 1,
        questionText: 'ব্যক্তির চোখের রেটিনা বা আইরিশ স্ক্যান করে শনাক্তকরণ প্রযুক্তিকে কী বলে?',
        optionA: 'বায়োমেট্রিক্স',
        optionB: 'বায়োইনফরমেটিক্স',
        optionC: 'রোবোটিক্স',
        optionD: 'ন্যানোটেকনোলজি',
        correctOption: 'a',
        explanation: 'মানুষের শারীরিক গঠন ও আচরণগত বৈশিষ্ট্য বিশ্লেষণ করে অদ্বিতীয়ভাবে ব্যক্তি শনাক্তকরণ পদ্ধতিকে বায়োমেট্রিক্স বলে।',
      },
      {
        serialNumber: 2,
        questionText: 'ক্লাউড কম্পিউটিংয়ের কোন সেবাটিতে সফটওয়্যার ব্যবহারের সুবিধা দেওয়া হয়?',
        optionA: 'IaaS',
        optionB: 'PaaS',
        optionC: 'SaaS (Software as a Service)',
        optionD: 'DaaS',
        correctOption: 'c',
        explanation: 'SaaS বা Software as a Service মডেলে ব্যবহারকারী কোনো সফটওয়্যার ডাউনলোড না করে অনলাইনেই সরাসরি ব্রাউজারে ব্যবহার করতে পারে (যেমন গুগল ডক্স)।',
      },
      {
        serialNumber: 3,
        questionText: 'কোন নেটওয়ার্ক টপোলজিতে একটি কেন্দ্রীয় হাব বা সুইচ ব্যবহৃত হয়?',
        optionA: 'বাস টপোলজি',
        optionB: 'রিং টপোলজি',
        optionC: 'স্টার টপোলজি (Star)',
        optionD: 'মেশ টপোলজি',
        correctOption: 'c',
        explanation: 'স্টার টপোলজির কেন্দ্রে একটি কেন্দ্রীয় ডিভাইস (Switch বা Hub) থাকে যার সাথে অন্যান্য সকল ওয়ার্কস্টেশন যুক্ত থাকে।',
      },
      {
        serialNumber: 4,
        questionText: 'বাইনারি সংখ্যা 1011₂ এর ডেসিমাল (দশমিক) মান কত?',
        optionA: '৯',
        optionB: '১১',
        optionC: '১৩',
        optionD: '১৫',
        correctOption: 'b',
        explanation: '1×2³ + 0×2² + 1×2¹ + 1×2⁰ = 8 + 0 + 2 + 1 = 11।',
      },
      {
        serialNumber: 5,
        questionText: 'হেক্সাডেসিমাল সংখ্যা পদ্ধতিতে ‘F’ এর সমতুল্য দশমিক মান কত?',
        optionA: '১০',
        optionB: '১২',
        optionC: '১৪',
        optionD: '১৫',
        correctOption: 'd',
        explanation: 'হেক্সাডেসিমালে A=10, B=11, C=12, D=13, E=14 এবং F=15।',
      },
      {
        serialNumber: 6,
        questionText: 'সি (C) ভাষায় চলকের নামকরণে নিচের কোনটি সঠিক নয়?',
        optionA: 'int _total;',
        optionB: 'int totalMarks;',
        optionC: 'int 1st_roll;',
        optionD: 'int roll_no;',
        correctOption: 'c',
        explanation: 'সি ভাষায় চলকের (variable) নাম কখনো সংখ্যা বা ডিজিট দিয়ে শুরু হতে পারে না।',
      },
      {
        serialNumber: 7,
        questionText: 'ন্যানোটেকনোলজির পরিসীমা কত মিটার পর্যন্ত?',
        optionA: '1 থেকে 100 ন্যানোমিটার (10⁻⁹ m)',
        optionB: '1 থেকে 100 মাইক্রোমিটার',
        optionC: '10⁻⁶ থেকে 10⁻³ মিটার',
        optionD: '10⁻¹² মিটার',
        correctOption: 'a',
        explanation: 'পারমাণবিক বা আণবিক স্কেলে ১ থেকে ১০০ ন্যানোমিটার আকৃতির উপাদান নিয়ন্ত্রণ ও তৈরিকরণই ন্যানোপ্রযুক্তি।',
      },
      {
        serialNumber: 8,
        questionText: 'কোন লজিক গেটের সকল ইনপুট ১ হলে আউটপুট ০ হয়?',
        optionA: 'AND গেট',
        optionB: 'NAND গেট',
        optionC: 'OR গেট',
        optionD: 'XOR গেট',
        correctOption: 'b',
        explanation: 'NAND গেট হলো AND গেটের বিপরীত। সব ইনপুট ১ হলে AND গেট ১ দেয়, ফলে NAND গেট ০ প্রদান করে।',
      },
      {
        serialNumber: 9,
        questionText: 'ইন্টারনেট প্রটোকল সংস্করণ ৪ (IPv4) এর অ্যাড্রেস কত বিটের?',
        optionA: '১৬ বিট',
        optionB: '৩২ বিট (4 বাইট)',
        optionC: '৬৪ বিট',
        optionD: '১২৮ বিট',
        correctOption: 'b',
        explanation: 'IPv4 অ্যাড্রেস ৩২ বিট দৈর্ঘ্যের হয়ে থাকে (৪টি অক্টেট), অন্যদিকে IPv6 অ্যাড্রেস ১২৮ বিটের।',
      },
      {
        serialNumber: 10,
        questionText: 'ক্রায়োসার্জারিতে অস্বাভাবিক বা রোগাক্রান্ত টিস্যু ধ্বংস করতে কোন উপাদানটি সর্বাধিক ব্যবহৃত হয়?',
        optionA: 'তরল নাইট্রোজেন ও আর্গন গ্যাস',
        optionB: 'তরল অক্সিজেন',
        optionC: 'কার্বন ডাই-অক্সাইড গ্যাস',
        optionD: 'ক্লোরিন গ্যাস',
        correctOption: 'a',
        explanation: 'ক্রায়োসার্জারিতে অত্যধিক নিম্ন তাপমাত্রা (-১৯৬°C পর্যন্ত) তৈরিতে তরল নাইট্রোজেন স্প্রে করা হয়।',
      },
    ],
  },

  // [12] HSC 2021 - Accounting 1st Paper (হিসাববিজ্ঞান ১ম পত্র - ঢাকা বোর্ড) - Commerce
  {
    academicLevel: 'hsc',
    subjectName: 'Accounting 1st Paper',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2021,
    title: 'HSC 2021: হিসাববিজ্ঞান ১ম পত্র (ঢাকা বোর্ড)',
    durationMinutes: 30,
    totalMarks: 30,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ৩০ মিনিট।',
    stream: 'commerce',
    questions: [
      {
        serialNumber: 1,
        questionText: 'ব্যবসায়ের সকল খরচ ও ক্ষতি কোন ধরণের হিসাব?',
        optionA: 'নামিক বা নামমাত্র হিসাব (Nominal Account)',
        optionB: 'ব্যক্তিবাচক হিসাব',
        optionC: 'সম্পত্তিবাচক হিসাব',
        optionD: 'দায়বাচক হিসাব',
        correctOption: 'a',
        explanation: 'ব্যবসায়ের আয়, ব্যয়, লাভ ও ক্ষতি সম্পর্কিত সকল হিসাবকে নামিক বা নামমাত্র হিসাব বলে।',
      },
      {
        serialNumber: 2,
        questionText: 'স্থায়ী সম্পত্তির সরলরৈখিক পদ্ধতিতে অবচয়ের ক্ষেত্রে কোনটি সত্য?',
        optionA: 'প্রতি বছর অবচয়ের পরিমাণ ভিন্ন হয়',
        optionB: 'প্রতি বছর অবচয়ের পরিমাণ সমান থাকে',
        optionC: 'অবচয় হার প্রতি বছর বৃদ্ধি পায়',
        optionD: 'কোনো অবচয় ধার্য হয় না',
        correctOption: 'b',
        explanation: 'সরলরৈখিক (Straight-line) পদ্ধতিতে সম্পত্তির কার্যকর আয়ুষ্কাল জুড়ে প্রতি বছর সমপরিমাণ অবচয় ধার্য করা হয়।',
      },
      {
        serialNumber: 3,
        questionText: 'অগ্রিম প্রদত্ত বীমা সেলামি কোন জাতীয় হিসাব?',
        optionA: 'চলতি সম্পদ',
        optionB: 'চলতি দায়',
        optionC: 'ব্যয় হিসাব',
        optionD: 'মালিকানাস্বত্ব',
        correctOption: 'a',
        explanation: 'অগ্রিম প্রদত্ত খরচ থেকে ভবিষ্যতে সুবিধা পাওয়া যাবে, তাই এটি প্রতিষ্ঠানের চলতি সম্পদ।',
      },
      {
        serialNumber: 4,
        questionText: 'যে ভুলের কারণে রেওয়ামিল মিলে যায় কিন্তু হিসাবের খাতায় ভুল থেকে যায়, তাকে কী বলে?',
        optionA: 'করনিক ভুল ও নীতিগত ভুল (সীমাবদ্ধতা)',
        optionB: 'শুধুমাত্র টাকার অঙ্কের ভুল',
        optionC: 'যোগফল ভুল',
        optionD: 'খতিয়ান পোস্টিং ভুল',
        correctOption: 'a',
        explanation: 'বাদ পড়ার ভুল, লেখার ভুল, পরিপূরক ভুল ও নীতিগত ভুলের মতো দ্বিপাক্ষিক ভুলের ক্ষেত্রেও রেওয়ামিলের দুই দিক মিলে যায়।',
      },
      {
        serialNumber: 5,
        questionText: 'কার্যপত্র (Worksheet) প্রস্তুত করা কী বাধ্যতামূলক?',
        optionA: 'হ্যাঁ, বাধ্যতামূলক আইনগত নথি',
        optionB: 'না, এটি একটি ঐচ্ছিক খসড়া বিবরণী',
        optionC: 'ব্যাংক হিসাবের জন্য বাধ্যতামূলক',
        optionD: 'কর কর্তৃপক্ষের জন্য বাধ্যতামূলক',
        correctOption: 'b',
        explanation: 'কার্যপত্র আনুষ্ঠানিক আর্থিক বিবরণী প্রস্তুতির সহায়ক একটি বহুঘরবিশিষ্ট ঐচ্ছিক কার্যপত্রিকা।',
      },
      {
        serialNumber: 6,
        questionText: 'কোন ধারণা অনুযায়ী ব্যবসায়ের জীবনকালকে বিভিন্ন নির্দিষ্ট আর্থিক বছরে ভাগ করা হয়?',
        optionA: 'হিসাবকাল ধারণা (Periodicity Assumption)',
        optionB: 'চলমান প্রতিষ্ঠান ধারণা',
        optionC: 'ব্যবসায়িক সত্ত্বা ধারণা',
        optionD: 'রক্ষণশীলতার নীতি',
        correctOption: 'a',
        explanation: 'হিসাবকাল ধারণা অনুসারে অনির্দিষ্টকালের ব্যবসায়ের ফলাফল নিয়মিত পর্যালোচনার জন্য নির্দিষ্ট সময় পর পর ভাগ করা হয়।',
      },
      {
        serialNumber: 7,
        questionText: 'খুচরা নগদান বই সংরক্ষণের জনপ্রিয় পদ্ধতির নাম কী?',
        optionA: 'অগ্রদত্ত পদ্ধতি (Imprest System)',
        optionB: 'চলতি জের পদ্ধতি',
        optionC: 'একতরফা পদ্ধতি',
        optionD: 'দ্বৈত জের পদ্ধতি',
        correctOption: 'a',
        explanation: 'ছোটখাটো দৈনন্দিন খরচ নির্বাহের জন্য অগ্রদত্ত খুচরা নগদান পদ্ধতি বিশ্বজুড়ে ব্যাপকভাবে প্রচলিত।',
      },
      {
        serialNumber: 8,
        questionText: 'অনুপার্জিত আয় (Unearned Revenue) প্রতিষ্ঠানের জন্য কী?',
        optionA: 'সম্পদ',
        optionB: 'চলতি দায় (Liability)',
        optionC: 'মুনাফা',
        optionD: 'মালিকানাস্বত্ব বৃদ্ধি',
        correctOption: 'b',
        explanation: 'সেবা প্রদানের পূর্বে অগ্রিম প্রাপ্ত অর্থ অর্জিত না হওয়া পর্যন্ত গ্রাহকের প্রতি দায় হিসেবে বিবেচিত হয়।',
      },
      {
        serialNumber: 9,
        questionText: 'আসবাবপত্র ক্রয় ৫০,০০০ টাকা ভুলে ক্রয় হিসাবে লেখা হলে এটি কোন ধরনের ভুল?',
        optionA: 'নীতিগত ভুল (Error of Principle)',
        optionB: 'বাদ পড়ার ভুল',
        optionC: 'বেদাখিলার ভুল',
        optionD: 'পরিপূরক ভুল',
        correctOption: 'a',
        explanation: 'মূলধন জাতীয় ব্যয়কে মুনাফা জাতীয় ব্যয় হিসেবে লিপিবদ্ধ করা হিসাববিজ্ঞানের মৌলিক নীতি লঙ্ঘনজনিত ভুল বা নীতিগত ভুল।',
      },
      {
        serialNumber: 10,
        questionText: 'কুঋণ বা অনাদায়ী পাওনা সঞ্চিতি কোন হিসাবের বিপরীতে তৈরি করা হয়?',
        optionA: 'প্রাপ্য হিসাব (দেনাদার)',
        optionB: 'প্রদেয় হিসাব',
        optionC: 'নগদান হিসাব',
        optionD: 'ব্যাংক হিসাব',
        correctOption: 'a',
        explanation: 'দেনাদার বা প্রাপ্য হিসাব থেকে সম্ভাব্য আদায়-অযোগ্য অর্থের ঝুঁকি মেটাতে কুঋণ সঞ্চিতি রাখা হয়।',
      },
    ],
  },

  // [13] HSC 2022 - Economics 1st Paper (অর্থনীতি ১ম পত্র - ঢাকা বোর্ড) - Humanities
  {
    academicLevel: 'hsc',
    subjectName: 'Economics 1st Paper',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2022,
    title: 'HSC 2022: অর্থনীতি ১ম পত্র (ঢাকা বোর্ড)',
    durationMinutes: 30,
    totalMarks: 30,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ৩০ মিনিট।',
    stream: 'humanities',
    questions: [
      {
        serialNumber: 1,
        questionText: 'অর্থনীতির মৌলিক সমস্যা কয়টি?',
        optionA: '২টি',
        optionB: '৩টি',
        optionC: '৪টি',
        optionD: '৫টি',
        correctOption: 'b',
        explanation: 'অধ্যাপক পি এ স্যামুয়েলসনের মতে ৩টি মৌলিক সমস্যা: কী উৎপাদন করতে হবে, কীভাবে উৎপাদন করতে হবে এবং কার জন্য উৎপাদন করতে হবে।',
      },
      {
        serialNumber: 2,
        questionText: 'চাহিদা রেখা সাধারণত কোন দিকে ঢালু হয়?',
        optionA: 'বাম থেকে ডানে নিম্নগামী',
        optionB: 'বাম থেকে ডানে ঊর্ধ্বগামী',
        optionC: 'উলম্ব রেখা',
        optionD: 'আনুভূমিক রেখা',
        correctOption: 'a',
        explanation: 'দাম বাড়লে চাহিদা কমে এবং দাম কমলে চাহিদা বাড়ে; এই বিপরীত সম্পর্কের কারণে চাহিদা রেখা বাম থেকে ডানে নিম্নগামী হয়।',
      },
      {
        serialNumber: 3,
        questionText: 'কোন বাজারে ক্রেতা ও বিক্রেতার সংখ্যা অসংখ্য থাকে এবং দাম স্থির থাকে?',
        optionA: 'পূর্ণ প্রতিযোগিতামূলক বাজার',
        optionB: 'একচেটিয়া বাজার',
        optionC: 'অলিগোপলি বাজার',
        optionD: 'ডুয়োপলি বাজার',
        correctOption: 'a',
        explanation: 'পূর্ণ প্রতিযোগিতামূলক বাজারে সমজাতীয় পণ্য থাকে এবং কোনো একক ক্রেতা বা বিক্রেতা বাজার দর প্রভাবিত করতে পারে না।',
      },
      {
        serialNumber: 4,
        questionText: 'উপযোগের (Utility) আধুনিক পরিমাপ কোনটি?',
        optionA: 'পর্যায়গত উপযোগ (Ordinal Utility)',
        optionB: 'সংখ্যাগত উপযোগ',
        optionC: 'মুদ্রাগত উপযোগ',
        optionD: 'কাল্পনিক উপযোগ',
        correctOption: 'a',
        explanation: 'জে আর হিকস ও অ্যালেন উপযোগকে সংখ্যার পরিবর্তে পছন্দক্রম বা পর্যায়গতভাবে ক্রমবিন্যাসের মাধ্যমে বিশ্লেষণ করেন।',
      },
      {
        serialNumber: 5,
        questionText: 'মোট উপযোগ যখন সর্বোচ্চ হয়, তখন প্রান্তিক উপযোগ (Marginal Utility) কত হয়?',
        optionA: 'সর্বোচ্চ',
        optionB: '০ (শূন্য)',
        optionC: 'ঋণাত্মক',
        optionD: '১',
        correctOption: 'b',
        explanation: 'ক্রমহ্রাসমান প্রান্তিক উপযোগ বিধিতে মোট উপযোগ TU যখন চূড়ায় পৌঁছায়, তখন প্রান্তিক উপযোগ MU শূন্য হয়।',
      },
      {
        serialNumber: 6,
        questionText: 'একচেটিয়া বাজারে ফার্মের ভারসাম্য বিন্দুতে কোনটি সমান হতে হয়?',
        optionA: 'MR = MC',
        optionB: 'AR = AC',
        optionC: 'P = MC',
        optionD: 'TR = TC',
        correctOption: 'a',
        explanation: 'সর্বোচ্চ মুনাফা অর্জনের জন্য ভারসাম্য বিন্দুতে প্রান্তিক আয় (MR) প্রান্তিক ব্যয় (MC)-এর সমান হতে হবে।',
      },
      {
        serialNumber: 7,
        questionText: 'উৎপাদনের মৌলিক উপাদান কয়টি?',
        optionA: '৩টি',
        optionB: '৪টি',
        optionC: '৫টি',
        optionD: '৬টি',
        correctOption: 'b',
        explanation: 'উৎপাদনের প্রধান ৪টি উপাদান হলো: ভূমি, শ্রম, মূলধন এবং সংগঠন।',
      },
      {
        serialNumber: 8,
        questionText: 'সুযোগ ব্যয় (Opportunity Cost) বলতে কী বোঝায়?',
        optionA: 'কোনো দ্রব্যের অতিরিক্ত এক একক পাওয়ার জন্য অপর দ্রব্যের যে পরিমাণ ত্যাগ করতে হয়',
        optionB: 'দ্রব্যের উৎপাদন মূল্য',
        optionC: 'বাজারের মুনাফা',
        optionD: 'সরকারি ভর্তুকি',
        correctOption: 'a',
        explanation: 'সীমিত সম্পদের সর্বোত্তম ব্যবহারের লক্ষ্যে কোনো সুযোগ গ্রহণের জন্য বিকল্প সেরা সুযোগ পরিত্যাগের মূল্যই সুযোগ ব্যয়।',
      },
      {
        serialNumber: 9,
        questionText: 'কোন অর্থব্যবস্থায় ভোক্তার সার্বভৌমত্ব বজায় থাকে এবং দাম স্বয়ংক্রিয়ভাবে নির্ধারিত হয়?',
        optionA: 'ধনতান্ত্রিক বা পুঁজিবাদী অর্থব্যবস্থা',
        optionB: 'সমাজতান্ত্রিক অর্থব্যবস্থা',
        optionC: 'মিশ্র অর্থব্যবস্থা',
        optionD: 'ইসলামী অর্থব্যবস্থা',
        correctOption: 'a',
        explanation: 'ধনতান্ত্রিক অর্থনীতিতে মুক্ত বাজার, ব্যক্তিমালিকানা এবং স্বয়ংক্রিয় দাম প্রক্রিয়ার ওপর সবকিছু নির্ধারিত হয়।',
      },
      {
        serialNumber: 10,
        questionText: 'যোগানের স্থিতিস্থাপকতা শূন্য হলে যোগান রেখাটি কেমন হবে?',
        optionA: 'উলম্ব রেখা (Vertical)',
        optionB: 'আনুভূমিক রেখা',
        optionC: 'ঊর্ধ্বগামী রেখা',
        optionD: 'মূলবিন্দুগামী রেখা',
        correctOption: 'a',
        explanation: 'দামের পরিবর্তনে যোগানের কোনো পরিবর্তন না হলে যোগান সম্পূর্ণ অস্থিতিস্থাপক (e=0) এবং রেখাটি উলম্ব হয়।',
      },
    ],
  },

  // [14] HSC 2023 - Higher Mathematics 1st Paper (উচ্চতর গণিত ১ম পত্র - ঢাকা বোর্ড) - Science
  {
    academicLevel: 'hsc',
    subjectName: 'Higher Mathematics 1st Paper',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2023,
    title: 'HSC 2023: উচ্চতর গণিত ১ম পত্র (ঢাকা বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'ম্যাট্রিক্স A = [[2, 4], [1, 2]] এর নির্ণায়কের (Determinant) মান কত?',
        optionA: '০',
        optionB: '২',
        optionC: '৪',
        optionD: '৮',
        correctOption: 'a',
        explanation: '|A| = (2 × 2) - (4 × 1) = 4 - 4 = 0। এর নির্ণায়কের মান শূন্য হওয়ায় এটি একটি ব্যতিক্রমী ম্যাট্রিক্স।',
      },
      {
        serialNumber: 2,
        questionText: 'lim (x → 0) (sin x / x) এর সঠিক মান কত?',
        optionA: '০',
        optionB: '১',
        optionC: 'অসীম (∞)',
        optionD: '-১',
        correctOption: 'b',
        explanation: 'ক্যালকুলাসের অন্যতম মৌলিক স্ট্যান্ডার্ড লিমিট উপপাদ্য অনুযায়ী lim (x → 0) (sin x / x) = 1।',
      },
      {
        serialNumber: 3,
        questionText: 'd/dx (ln x) এর অন্তরজ (Derivative) কোনটি?',
        optionA: '1/x',
        optionB: 'x',
        optionC: 'eˣ',
        optionD: '1/x²',
        correctOption: 'a',
        explanation: 'স্বাভাবিক লগারিদম ফাংশন ln(x) এর ১ম অন্তরজ d/dx (ln x) = 1/x।',
      },
      {
        serialNumber: 4,
        questionText: '∫ (1 / x) dx এর সমাকলন (Integral) কোনটি?',
        optionA: 'ln |x| + c',
        optionB: 'x + c',
        optionC: '-1/x² + c',
        optionD: 'eˣ + c',
        correctOption: 'a',
        explanation: 'সমাকলনের মৌলিক সূত্রানুসারে 1/x এর অনির্দিষ্ট যোগজ হলো ln|x| + c।',
      },
      {
        serialNumber: 5,
        questionText: 'y = 2x + 5 সরলরেখাটির ঢাল (Slope) কত?',
        optionA: '২',
        optionB: '৫',
        optionC: '-২',
        optionD: '১/২',
        correctOption: 'a',
        explanation: 'y = mx + c সমীকরণে m হলো রেখার ঢাল। এখানে m = 2।',
      },
      {
        serialNumber: 6,
        questionText: 'বৃত্তের সাধারণ সমীকরণ x² + y² - 4x - 6y + 9 = 0 এর কেন্দ্র কত?',
        optionA: '(2, 3)',
        optionB: '(-2, -3)',
        optionC: '(4, 6)',
        optionD: '(1, 2)',
        correctOption: 'a',
        explanation: 'বৃত্তের কেন্দ্র (-g, -f)। এখানে 2g = -4 ⇒ g = -2 এবং 2f = -6 ⇒ f = -3। অতএব কেন্দ্র (2, 3)।',
      },
      {
        serialNumber: 7,
        questionText: 'cos 2A এর ত্রিকোণমিতিক রূপ কোনটি?',
        optionA: 'cos²A - sin²A',
        optionB: 'cos²A + sin²A',
        optionC: '2 sin A cos A',
        optionD: '1 - 2 cos²A',
        correctOption: 'a',
        explanation: 'cos 2A = cos²A - sin²A = 2cos²A - 1 = 1 - 2sin²A।',
      },
      {
        serialNumber: 8,
        questionText: 'দুটি সরলরেখা পরস্পরের ওপর লম্ব হওয়ার শর্ত কী?',
        optionA: 'm₁ × m₂ = -1',
        optionB: 'm₁ = m₂',
        optionC: 'm₁ + m₂ = 0',
        optionD: 'm₁ / m₂ = 1',
        correctOption: 'a',
        explanation: 'দুটি সরলরেখা পরস্পর লম্ব হলে তাদের ঢালদ্বয়ের গুণফল সর্বদা -১ হয়।',
      },
      {
        serialNumber: 9,
        questionText: '∫ sin x dx এর মান কত?',
        optionA: '-cos x + c',
        optionB: 'cos x + c',
        optionC: 'sec x + c',
        optionD: '-sin x + c',
        correctOption: 'a',
        explanation: 'd/dx (cos x) = -sin x হওয়ায়, ∫ sin x dx = -cos x + c।',
      },
      {
        serialNumber: 10,
        questionText: 'একটি একক ম্যাট্রিক্সের (Identity Matrix) নির্ণায়কের মান কত?',
        optionA: '০',
        optionB: '১',
        optionC: '-১',
        optionD: 'অনির্ণেয়',
        correctOption: 'b',
        explanation: 'যেকোনো ক্রমের অভেদক বা একক ম্যাট্রিক্স I এর নির্ণায়কের মান সর্বদা ১।',
      },
    ],
  },

  // [15] HSC 2024 - Biology 1st Paper (উদ্ভিদবিজ্ঞান - ঢাকা বোর্ড) - Science
  {
    academicLevel: 'hsc',
    subjectName: 'Biology 1st Paper (Botany)',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2024,
    title: 'HSC 2024: জীববিজ্ঞান ১ম পত্র - উদ্ভিদবিজ্ঞান (ঢাকা বোর্ড)',
    durationMinutes: 25,
    totalMarks: 25,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ২৫ মিনিট।',
    stream: 'science',
    questions: [
      {
        serialNumber: 1,
        questionText: 'কোষ প্রাচীরের প্রধান গাঠনিক উপাদান কোনটি?',
        optionA: 'সেলুলোজ',
        optionB: 'লিপিড',
        optionC: 'প্রোটিন',
        optionD: 'গ্লাইকোজেন',
        correctOption: 'a',
        explanation: 'উদ্ভিদ কোষ প্রাচীরের মূল গাঠনিক পলিস্যাকারাইড হলো সেলুলোজ যা বিটা-ডি গ্লুকোজ পলিমার।',
      },
      {
        serialNumber: 2,
        questionText: 'মায়োসিস (Meiosis) কোষ বিভাজনের কোন উপপর্যায়ে ক্রসিং ওভার ঘটে?',
        optionA: 'প্যাকাইটিন (Pachytene)',
        optionB: 'লেপ্টোটিন',
        optionC: 'জাইগোটিন',
        optionD: 'ডিপ্লোটিন',
        correctOption: 'a',
        explanation: 'প্রফেজ-১ এর প্যাকাইটিন উপপর্যায়ে নন-সিস্টার ক্রোমাটিডদ্বয়ের মধ্যে অংশের বিনিময় বা ক্রসিং ওভার সম্পন্ন হয়।',
      },
      {
        serialNumber: 3,
        questionText: 'C₄ উদ্ভিদের প্রথম স্থায়ী পদার্থ কোনটি?',
        optionA: 'অক্সালোঅ্যাসিটিক অ্যাসিড (OAA)',
        optionB: '৩-ফসফোগ্লিসারিক অ্যাসিড (3-PGA)',
        optionC: 'ম্যালিক অ্যাসিড',
        optionD: 'গ্লুকোজ',
        correctOption: 'a',
        explanation: 'হ্যাচ ও স্ল্যাক চক্রে কার্বন ডাই-অক্সাইড গ্রহণের পর প্রথম স্থায়ী যৌগ হিসেবে ৪ কার্বনযুক্ত অক্সালোঅ্যাসিটিক অ্যাসিড তৈরি হয়।',
      },
      {
        serialNumber: 4,
        questionText: 'অরীয় ভাস্কুলার বান্ডল (Radial Vascular Bundle) কোথায় পাওয়া যায়?',
        optionA: 'উদ্ভিদের মূলে (Root)',
        optionB: 'দ্বিবীজপত্রী কাণ্ডে',
        optionC: 'একবীজপত্রী কাণ্ডে',
        optionD: 'পাতায়',
        correctOption: 'a',
        explanation: 'জাইলেম ও ফ্লোয়েম গুচ্ছ ভিন্ন ভিন্ন ব্যাসার্ধে পর্যায়ক্রমে সজ্জিত থাকলে তাকে অরীয় বান্ডল বলে, যা মূলে দেখা যায়।',
      },
      {
        serialNumber: 5,
        questionText: 'ফার্নের শুক্রাণু কোন প্রকৃতির?',
        optionA: 'বহুকশাবিশিষ্ট (Multiflagellated)',
        optionB: 'দ্বিকশাবিশিষ্ট',
        optionC: 'কশাহীন',
        optionD: 'এককশাবিশিষ্ট',
        correctOption: 'a',
        explanation: 'টেরিডোফাইটা বা ফার্নজাতীয় উদ্ভিদের পুংজননকোষ বা শুক্রাণু প্যাঁচানো ও বহু ফ্ল্যাজেলাযুক্ত।',
      },
      {
        serialNumber: 6,
        questionText: 'টিস্যু কালচারের জনক কে?',
        optionA: 'গটলিব হেবারল্যান্ডট',
        optionB: 'রবার্ট হুক',
        optionC: 'গ্রেগর মেন্ডেল',
        optionD: 'ক্যালভিন',
        correctOption: 'a',
        explanation: '১৯০২ সালে অস্ট্রিয়ান বিজ্ঞানী Gottlieb Haberlandt প্রথম টিস্যু কালচার ধারণার সূচনা করেন।',
      },
      {
        serialNumber: 7,
        questionText: 'কোন অঙ্গাণুকে প্রোটিন ফ্যাক্টরি (Protein Factory) বলা হয়?',
        optionA: 'রাইবোসোম',
        optionB: 'লাইসোজোম',
        optionC: 'মাইটোকন্ড্রিয়া',
        optionD: 'পারঅক্সিসোম',
        correctOption: 'a',
        explanation: 'মেসেঞ্জার আরএনএ এর সংকেত অনুযায়ী অ্যামিনো অ্যাসিড জোড়া লাগিয়ে প্রোটিন তৈরির কাজ রাইবোসোমে হয়।',
      },
      {
        serialNumber: 8,
        questionText: 'ম্যালেরিয়া জীবাণুর সুপ্তাবস্থা মানবদেহের কোন অঙ্গে ঘটে?',
        optionA: 'যকৃৎ ও লোহিত রক্তকণিকা',
        optionB: 'ফুসফুস',
        optionC: 'হৃদপিণ্ড',
        optionD: 'কিডনি',
        correctOption: 'a',
        explanation: 'প্লাজমোডিয়াম জীবাণু মানুষের যকৃতে হেপাটিক সাইজোগনি ও লোহিত কণিকায় এরিথ্রোসাইটিক সাইজোগনি সম্পন্ন করে।',
      },
      {
        serialNumber: 9,
        questionText: 'ভাইরাসের বাধ্যতামূলক পরজীবীতার প্রধান কারণ কী?',
        optionA: 'নিজস্ব কোনো বিপাকীয় এনজাইম ও সাইটোপ্লাজম নেই',
        optionB: 'DNA থাকে না',
        optionC: 'খুব ছোট আকৃতি',
        optionD: 'ক্যাপসিড থাকে না',
        correctOption: 'a',
        explanation: 'ভাইরাস অকোষীয় হওয়ায় পোষক কোষের বাইরে জীবনের কোনো লক্ষণ দেখায় না এবং সম্পূর্ণ নিষ্ক্রিয় থাকে।',
      },
      {
        serialNumber: 10,
        questionText: 'ক্রেবস চক্র কোষের কোথায় সংঘটিত হয়?',
        optionA: 'মাইটোকন্ড্রিয়ার ম্যাট্রিক্সে',
        optionB: 'সাইটোপ্লাজমে',
        optionC: 'নিউক্লিয়াসে',
        optionD: 'গলগি বডিতে',
        correctOption: 'a',
        explanation: 'সবাত শ্বসনের সবচেয়ে গুরুত্বপূর্ণ ক্রেবস চক্র মাইটোকন্ড্রিয়াল ম্যাট্রিক্সে অবস্থিত এনজাইমের সাহায্যে ঘটে।',
      },
    ],
  },

  // [16] HSC 2025 - Bangla 1st Paper (বাংলা ১ম পত্র - ঢাকা বোর্ড) - Common
  {
    academicLevel: 'hsc',
    subjectName: 'Bangla 1st Paper',
    boardName: 'ঢাকা বোর্ড',
    examYear: 2025,
    title: 'HSC 2025: বাংলা ১ম পত্র (ঢাকা বোর্ড)',
    durationMinutes: 30,
    totalMarks: 30,
    negativeMark: 0.25,
    instructions: 'প্রতিটি সঠিক উত্তরের জন্য ১ নম্বর। প্রতিটি ভুল উত্তরের জন্য ০.২৫ নম্বর কাটা যাবে। সময় ৩০ মিনিট।',
    stream: 'common',
    questions: [
      {
        serialNumber: 1,
        questionText: '‘অপরিচিতা’ গল্পে কল্যাণীর বাবার নাম কী?',
        optionA: 'শম্ভুনাথ সেন',
        optionB: 'হরিশ',
        optionC: 'অনুপম',
        optionD: 'বিনু দাদা',
        correctOption: 'a',
        explanation: 'রবীন্দ্রনাথ ঠাকুরের ‘অপরিচিতা’ গল্পের বলিষ্ঠ আত্মমর্যাদাসম্পন্ন পিতার নাম শম্ভুনাথ সেন।',
      },
      {
        serialNumber: 2,
        questionText: '‘বিলাসী’ গল্পটি কোন পত্রিকায় প্রথম প্রকাশিত হয়েছিল?',
        optionA: 'ভারতী',
        optionB: 'সবুজপত্র',
        optionC: 'প্রবাসী',
        optionD: 'কল্লোল',
        correctOption: 'a',
        explanation: 'শরৎচন্দ্র চট্টোপাধ্যায়ের কালজয়ী ‘বিলাসী’ গল্পটি ১৩২৫ বঙ্গাব্দের বৈশাখ সংখ্যা ‘ভারতী’ পত্রিকায় আত্মপ্রকাশ করে।',
      },
      {
        serialNumber: 3,
        questionText: '‘আমার পথ’ প্রবন্ধে কাজী নজরুল ইসলাম নিজেকে কার অভিশাপগ্রাহী বলেছেন?',
        optionA: 'সত্যের',
        optionB: 'ভণ্ডের',
        optionC: 'সমাজের',
        optionD: 'ধর্মের',
        correctOption: 'a',
        explanation: 'নজরুল তাঁর ‘আমার পথ’ প্রবন্ধে লিখেছেন: "আমি সত্যের অভিশাপগ্রাহী—মিথ্যার জয়গান আমার নয়।"',
      },
      {
        serialNumber: 4,
        questionText: '‘বায়ান্নর দিনগুলো’ কার আত্মজীবনীমূলক গ্রন্থ থেকে গৃহীত?',
        optionA: 'বঙ্গবন্ধু শেখ মুজিবুর রহমান',
        optionB: 'মওলানা ভাসানী',
        optionC: 'তাজউদ্দীন আহমদ',
        optionD: 'শেরে বাংলা এ কে ফজলুল হক',
        correctOption: 'a',
        explanation: 'জাতির পিতা বঙ্গবন্ধু শেখ মুজিবুর রহমানের অমর ‘অসমাপ্ত আত্মজীবনী’ গ্রন্থ থেকে ১৯৫২ সালের স্মৃতিচারণটি সংকলিত।',
      },
      {
        serialNumber: 5,
        questionText: '‘রক্তে আমার অনাদি অস্থি’ কার রচিত কবিতা?',
        optionA: 'দিলওয়ার',
        optionB: 'শামসুর রাহমান',
        optionC: 'আল মাহমুদ',
        optionD: 'সৈয়দ শামসুল হক',
        correctOption: 'a',
        explanation: 'গণমানুষের কবি দিলওয়ারের দেশাত্মবোধক অমর কবিতা ‘রক্তে আমার অনাদি অস্থি’।',
      },
      {
        serialNumber: 6,
        questionText: '‘বিভীষণের প্রতি মেঘনাদ’ কাব্যাংশটি মাইকেল মধুসূদন দত্তের কোন কাব্যের অংশ?',
        optionA: 'মেঘনাদবধ কাব্য (ষষ্ঠ সর্গ)',
        optionB: 'তিলোত্তমাসম্ভব কাব্য',
        optionC: 'বীরাঙ্গনা কাব্য',
        optionD: 'ব্রজাঙ্গনা কাব্য',
        correctOption: 'a',
        explanation: 'বাংলা সাহিত্যের প্রথম সার্থক মহাকাব্য ‘মেঘনাদবধ কাব্য’-এর ষষ্ঠ সর্গ ‘বধো’ অংশ থেকে এ রচনাটি সংকলিত।',
      },
      {
        serialNumber: 7,
        questionText: '‘সোনার তরী’ কবিতায় ধান কেটে কবি কার অপেক্ষায় ঘাটে বসে ছিলেন?',
        optionA: 'তরীর মাঝির',
        optionB: 'কৃষকের',
        optionC: 'বন্ধুর',
        optionD: 'প্রকৃতির',
        correctOption: 'a',
        explanation: 'মহাকালের প্রতীক নিঃসঙ্গ নদী ও নৌকার মাঝির জন্য শূন্য নদীর তীরে কবি একাকী অপেক্ষায় থাকেন।',
      },
      {
        serialNumber: 8,
        questionText: '‘ফেব্রুয়ারি ১৯৬৯’ কবিতায় কৃষ্ণচূড়া ফুল কিসের প্রতীক হিসেবে চিহ্নিত?',
        optionA: 'শহীদের আত্মদান ও চেতনার রং',
        optionB: 'বসন্তের আগমন',
        optionC: 'সৌন্দর্যের প্রতীক',
        optionD: 'প্রেমের প্রতীক',
        correctOption: 'a',
        explanation: 'শামসুর রাহমান সালাম, বরকত ও ৬৯-এর গণঅভ্যুত্থানের রক্তঝরা আত্মদানকে কৃষ্ণচূড়ার রক্তের রঙের সাথে তুলনা করেছেন।',
      },
      {
        serialNumber: 9,
        questionText: '‘লালসালু’ উপন্যাসে মজিদের দ্বিতীয় স্ত্রীর নাম কী?',
        optionA: 'জমিলা',
        optionB: 'রহিমা',
        optionC: 'আমেনা বিবি',
        optionD: 'হাসুনির মা',
        correctOption: 'a',
        explanation: 'সৈয়দ ওয়ালীউল্লাহর ‘লালসালু’ উপন্যাসে প্রতিবাদী তরুণী দ্বিতীয় স্ত্রীর নাম জমিলা।',
      },
      {
        serialNumber: 10,
        questionText: '‘সিরাজউদ্দৌলা’ নাটকে নবাবের বিশ্বস্ত সেনাপতি কে ছিলেন?',
        optionA: 'মীর মদন ও মোহনলাল',
        optionB: 'মীর জাফর',
        optionC: 'রায় দুর্লভ',
        optionD: 'ইয়ার লতিফ',
        correctOption: 'a',
        explanation: 'পলাশীর প্রান্তরে বিশ্বাসঘাতকতার মাঝেও বীর সেনাপতি মীর মদন ও মোহনলাল নবাবের পক্ষে আমৃত্যু লড়েছিলেন।',
      },
    ],
  },
];

export async function runComprehensiveBoardQuestionSeeder() {
  const client = await pool.connect();
  try {
    console.log('🚀 Starting Comprehensive HSC & SSC Board Questions Safe Seeder (2018-2025)...');

    let seededCount = 0;
    let questionsSeeded = 0;

    for (const examData of comprehensiveBoardExams) {
      // 1. Resolve target subject from subjects table
      const subRes = await client.query(
        `SELECT id, name_bn, stream, academic_level FROM subjects WHERE name = $1 AND academic_level = $2 LIMIT 1`,
        [examData.subjectName, examData.academicLevel]
      );

      if (subRes.rowCount === 0) {
        console.warn(`⚠️ Subject not found for: "${examData.subjectName}" (${examData.academicLevel}). Skipping.`);
        continue;
      }

      const subjectId = subRes.rows[0].id;
      const subjectNameBn = subRes.rows[0].name_bn;

      // 2. Check if this exact board exam already exists
      const existingExamRes = await client.query(
        `SELECT id FROM exams WHERE subject_id = $1 AND title = $2 LIMIT 1`,
        [subjectId, examData.title]
      );

      let examId: string;
      if (existingExamRes.rowCount && existingExamRes.rowCount > 0) {
        examId = existingExamRes.rows[0].id;
        console.log(`ℹ️ Board exam already exists: "${examData.title}". Updating metadata...`);
        await client.query(
          `UPDATE exams
           SET exam_type = 'board_question', board_name = $1, exam_year = $2,
               duration_minutes = $3, total_marks = $4, negative_mark = $5, is_published = TRUE,
               academic_level = $6, curriculum_version = 'bangla'
           WHERE id = $7`,
          [
            examData.boardName,
            examData.examYear,
            examData.durationMinutes,
            examData.totalMarks,
            examData.negativeMark,
            examData.academicLevel,
            examId,
          ]
        );
      } else {
        const insertExamRes = await client.query(
          `INSERT INTO exams (
             subject_id, title, serial_number, duration_minutes, total_marks,
             negative_mark, instructions, is_published, curriculum_version,
             academic_level, exam_type, board_name, exam_year
           )
           VALUES ($1, $2, 1, $3, $4, $5, $6, TRUE, 'bangla', $7, 'board_question', $8, $9)
           RETURNING id`,
          [
            subjectId,
            examData.title,
            examData.durationMinutes,
            examData.totalMarks,
            examData.negativeMark,
            examData.instructions,
            examData.academicLevel,
            examData.boardName,
            examData.examYear,
          ]
        );
        examId = insertExamRes.rows[0].id;
        seededCount++;
        console.log(`✅ Created board exam: "${examData.title}" (ID: ${examId}) for ${subjectNameBn}`);
      }

      // 3. Insert questions safely without duplicates
      for (const q of examData.questions) {
        const qExists = await client.query(
          `SELECT id FROM questions WHERE exam_id = $1 AND serial_number = $2`,
          [examId, q.serialNumber]
        );

        if (qExists.rowCount === 0) {
          await client.query(
            `INSERT INTO questions (
               exam_id, question_text, option_a, option_b, option_c, option_d,
               correct_option, explanation, serial_number
             )
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
            [
              examId,
              q.questionText,
              q.optionA,
              q.optionB,
              q.optionC,
              q.optionD,
              q.correctOption,
              q.explanation,
              q.serialNumber,
            ]
          );
          questionsSeeded++;
        }
      }
    }

    console.log(`🎉 Comprehensive Board Questions Seeder finished! Created ${seededCount} new exams, added ${questionsSeeded} questions.`);
  } catch (err) {
    console.error('❌ Error seeding comprehensive board questions:', err);
    throw err;
  } finally {
    client.release();
  }
}

// Auto-run if executed directly via tsx
if (process.argv[1]?.endsWith('seed_comprehensive_board_questions.ts')) {
  runComprehensiveBoardQuestionSeeder()
    .then(() => {
      console.log('Done!');
      process.exit(0);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
